// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/computedresources

package app

import (
	"net/http"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource/waystation/pkg/computedresources"
	"github.com/cccteam/ccc/resource/waystation/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
)

func (a *App) StationStatusBoards() http.HandlerFunc {
	type stationStatusBoard struct {
		FacilityID    ccc.UUID  `json:"facilityId"    perm:"-"`
		Metric        string    `json:"metric"        perm:"-"`
		FacilityName  string    `json:"facilityName"`
		WaystationID  string    `json:"waystationId"`
		LatestReading float64   `json:"latestReading"`
		RecordedAt    time.Time `json:"recordedAt"`
	}

	type response []map[string]any

	decoder := NewComputedQueryDecoder[computedresources.StationStatusBoard, stationStatusBoard](accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		resp := response{}
		for row, err := range computedresources.ListStationStatusBoard(ctx, querySet, a.ResourceClient(), a.ComputedClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*stationStatusBoard)(row)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "FacilityID":
					rmap["facilityId"] = rec.FacilityID
				case "Metric":
					rmap["metric"] = rec.Metric
				case "FacilityName":
					rmap["facilityName"] = rec.FacilityName
				case "WaystationID":
					rmap["waystationId"] = rec.WaystationID
				case "LatestReading":
					rmap["latestReading"] = rec.LatestReading
				case "RecordedAt":
					rmap["recordedAt"] = rec.RecordedAt
				}
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
func (a *App) StationStatusBoard() http.HandlerFunc {
	type response struct {
		FacilityID    ccc.UUID  `json:"facilityId"    perm:"-"`
		Metric        string    `json:"metric"        perm:"-"`
		FacilityName  string    `json:"facilityName"`
		WaystationID  string    `json:"waystationId"`
		LatestReading float64   `json:"latestReading"`
		RecordedAt    time.Time `json:"recordedAt"`
	}

	decoder := NewComputedQueryDecoder[computedresources.StationStatusBoard, response](accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		facilityID := httpio.Param[ccc.UUID](r, router.StationStatusBoardFacilityID)
		metric := httpio.Param[string](r, router.StationStatusBoardMetric)

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		row, err := computedresources.ReadStationStatusBoard(ctx, facilityID, metric, querySet, a.ResourceClient(), a.ComputedClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		if row == nil {
			return httpio.NewEncoder(w).Ok(nil)
		}
		rec := (*response)(row)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "FacilityID":
				rmap["facilityId"] = rec.FacilityID
			case "Metric":
				rmap["metric"] = rec.Metric
			case "FacilityName":
				rmap["facilityName"] = rec.FacilityName
			case "WaystationID":
				rmap["waystationId"] = rec.WaystationID
			case "LatestReading":
				rmap["latestReading"] = rec.LatestReading
			case "RecordedAt":
				rmap["recordedAt"] = rec.RecordedAt
			}
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}
