// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/waystation/pkg/resources"
	"github.com/cccteam/ccc/resource/waystation/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
)

func (a *App) SensorReadings() http.HandlerFunc {
	type sensorReading struct {
		ID           ccc.UUID  `json:"id"           index:"true" perm:"-"`
		WaystationID string    `json:"waystationId" index:"true"`
		FacilityID   ccc.UUID  `json:"facilityId"   index:"true"`
		Metric       string    `json:"metric"`
		Reading      float64   `json:"reading"`
		RecordedAt   time.Time `json:"recordedAt"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[resources.SensorReading, sensorReading](accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewSensorReadingQueryFromQuerySet(querySet)

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*sensorReading)(&row.Data)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "ID":
					if !row.Masked("id") {
						rmap["id"] = rec.ID
					}
				case "WaystationID":
					if !row.Masked("waystationId") {
						rmap["waystationId"] = rec.WaystationID
					}
				case "FacilityID":
					if !row.Masked("facilityId") {
						rmap["facilityId"] = rec.FacilityID
					}
				case "Metric":
					if !row.Masked("metric") {
						rmap["metric"] = rec.Metric
					}
				case "Reading":
					if !row.Masked("reading") {
						rmap["reading"] = rec.Reading
					}
				case "RecordedAt":
					if !row.Masked("recordedAt") {
						rmap["recordedAt"] = rec.RecordedAt
					}
				}
			}
			if capabilities := row.Capabilities(); capabilities != nil {
				rmap[resource.CapabilitiesProperty] = capabilities
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
