// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"

	"github.com/cccteam/ccc/resource"
)

// PermissionDigest serves the session user's per-scope permission digest — the
// structural grant enumeration the frontend renders navigation and forms from.
// The scope is the request's input (?domain= names a tenant partition, absent
// means global) and the payload is advisory and fail-closed: denied targets are
// absent. The generated router registers it at GET /api/permission-digest.
func (a *App) PermissionDigest() http.HandlerFunc {
	return resource.PermissionDigestHandler(a.UserPermissions)
}
