// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"

	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/waystation/pkg/virtualresources"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
	"github.com/shopspring/decimal"
)

func (a *App) SpendByCategories() http.HandlerFunc {
	type spendByCategory struct {
		Category      string          `json:"category"      index:"true" perm:"-"`
		LineCount     int64           `json:"lineCount"`
		TotalQuantity int64           `json:"totalQuantity"`
		TotalSpend    decimal.Decimal `json:"totalSpend"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[virtualresources.SpendByCategory, spendByCategory](accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.GlobalScope())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := virtualresources.NewSpendByCategoryQueryFromQuerySet(querySet)

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*spendByCategory)(&row.Data)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "Category":
					if !row.Masked("category") {
						rmap["category"] = rec.Category
					}
				case "LineCount":
					if !row.Masked("lineCount") {
						rmap["lineCount"] = rec.LineCount
					}
				case "TotalQuantity":
					if !row.Masked("totalQuantity") {
						rmap["totalQuantity"] = rec.TotalQuantity
					}
				case "TotalSpend":
					if !row.Masked("totalSpend") {
						rmap["totalSpend"] = rec.TotalSpend
					}
				}
			}
			if capabilities := row.Capabilities(); capabilities != nil {
				rmap[resource.CapabilitiesProperty] = capabilities
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
