// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/rpc

package app

import (
	"context"
	"net/http"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/waystation/pkg/router"
	"github.com/cccteam/ccc/resource/waystation/pkg/rpc"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
	"github.com/go-playground/errors/v5"
)

func (a *App) NudgeWorkOrder() http.HandlerFunc {
	type request struct {
		WorkOrderID ccc.UUID `json:"workOrderId"`
	}

	decoder := NewRPCDecoder[rpc.NudgeWorkOrder, request](a, accesstypes.Execute)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		params, err := decoder.Decode(r, accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		p := (*rpc.NudgeWorkOrder)(params)
		if err := a.ResourceClient().ExecuteFunc(ctx, func(ctx context.Context, txn resource.ReadWriteTransaction) error {
			if err := p.Execute(ctx, txn, a.RPCClient()); err != nil {
				return errors.Wrap(err, "Transaction.Execute()")
			}

			return nil
		}); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, errors.Wrap(err, "spanner.Client.ReadWriteTransaction()"))
		}

		return httpio.NewEncoder(w).Ok(nil)
	})
}
