// Code generated by resourcegeneration. DO NOT EDIT.
// Source: apps/console/pkg/resources

package authz

import (
	"net/http"
	"net/http/httptest"
	"slices"
	"strings"
	"testing"

	"github.com/cccteam/ccc/accesstypes"
)

// grants scripts the permission table for one test: the permissions the test user
// holds on every resource. Permissions not present are denied.
type grants map[accesstypes.Permission]bool

// TestGeneratedAuthorizationMatrix drives every generated route through the generated
// test router and pins that each one fails closed: without the required permission the
// pipeline must refuse the request with 403.
//
// Query routes (list, read) also carry a granted case: with exactly the required
// permission the request must reach data access — 200, or 404 when the empty schema
// has no row. Mutation routes (patch create/update/delete operations, consolidated
// dispatch arms, RPC methods) are denied-only: each body is the minimum that reaches
// the operation's enforcement gate — buffer time for patch sets, decode time for RPC —
// which runs before required-field validation, defaults, or row reads. Mutation
// success paths need valid request bodies the generator does not synthesize yet and
// are left to manual testing. A transaction-form RPC method carries a second denied
// case under X-Dry-Run: a dry run refuses exactly as the real call does.
//
// The suite runs on the migrated schema alone; no seed data is required, so it grows
// with the schema on every regeneration.
//
// The package must define
//
//	newTestHandler(t *testing.T, db *initiator.SpannerDB, g grants) http.Handler
//
// constructing the application around the test database with the scripted grants and
// composing it through the generated router.NewTestRouter. For domain-scoped routes,
// the application's tenancy seam must recognize the suite's domain value "testDomain"
// (DomainExists; with concealed domains, DomainVisible — which must also honor the
// scripted grants, so a case with no grants is answered as if the domain did not
// exist).
func TestGeneratedAuthorizationMatrix(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		grants       grants
		method       string
		target       string
		body         string
		headers      map[string]string
		wantStatuses []int
	}{
		{
			name:         "Announcements denied",
			method:       http.MethodGet,
			target:       "/api/tenants/testDomain/announcements",
			wantStatuses: []int{http.StatusNotFound},
		},
		{
			name:         "Announcements granted",
			grants:       grants{accesstypes.List: true},
			method:       http.MethodGet,
			target:       "/api/tenants/testDomain/announcements",
			wantStatuses: []int{http.StatusOK, http.StatusNotFound},
		},
		{
			name:         "Announcement denied",
			method:       http.MethodGet,
			target:       "/api/tenants/testDomain/announcements/00000000-0000-0000-0000-000000000001",
			wantStatuses: []int{http.StatusNotFound},
		},
		{
			name:         "Announcement granted",
			grants:       grants{accesstypes.Read: true},
			method:       http.MethodGet,
			target:       "/api/tenants/testDomain/announcements/00000000-0000-0000-0000-000000000001",
			wantStatuses: []int{http.StatusOK, http.StatusNotFound},
		},
		{
			name:         "Tenants denied",
			method:       http.MethodGet,
			target:       "/api/tenants",
			wantStatuses: []int{http.StatusForbidden},
		},
		{
			name:         "Tenants granted",
			grants:       grants{accesstypes.List: true},
			method:       http.MethodGet,
			target:       "/api/tenants",
			wantStatuses: []int{http.StatusOK, http.StatusNotFound},
		},
		{
			name:         "Tenant denied",
			method:       http.MethodGet,
			target:       "/api/tenants/authz-test-key",
			wantStatuses: []int{http.StatusForbidden},
		},
		{
			name:         "Tenant granted",
			grants:       grants{accesstypes.Read: true},
			method:       http.MethodGet,
			target:       "/api/tenants/authz-test-key",
			wantStatuses: []int{http.StatusOK, http.StatusNotFound},
		},
		{
			name:         "PatchResources Announcement create denied",
			method:       http.MethodPatch,
			target:       "/api/resources",
			body:         `[{"op":"add","path":"/tenants/testDomain/announcements","value":{}}]`,
			wantStatuses: []int{http.StatusBadRequest},
		},
		{
			name:         "PatchResources Announcement update denied",
			method:       http.MethodPatch,
			target:       "/api/resources",
			body:         `[{"op":"patch","path":"/tenants/testDomain/announcements/00000000-0000-0000-0000-000000000001","value":{"kindId":"authz-test-value"}}]`,
			wantStatuses: []int{http.StatusBadRequest},
		},
		{
			name:         "PatchResources Announcement delete denied",
			method:       http.MethodPatch,
			target:       "/api/resources",
			body:         `[{"op":"remove","path":"/tenants/testDomain/announcements/00000000-0000-0000-0000-000000000001"}]`,
			wantStatuses: []int{http.StatusBadRequest},
		},
		{
			name:         "PatchResources Tenant create denied",
			method:       http.MethodPatch,
			target:       "/api/resources",
			body:         `[{"op":"add","path":"/tenants/authz-test-key","value":{}}]`,
			wantStatuses: []int{http.StatusForbidden},
		},
		{
			name:         "PatchResources Tenant update denied",
			method:       http.MethodPatch,
			target:       "/api/resources",
			body:         `[{"op":"patch","path":"/tenants/authz-test-key","value":{"name":"authz-test-value"}}]`,
			wantStatuses: []int{http.StatusForbidden},
		},
		{
			name:         "PatchResources Tenant delete denied",
			method:       http.MethodPatch,
			target:       "/api/resources",
			body:         `[{"op":"remove","path":"/tenants/authz-test-key"}]`,
			wantStatuses: []int{http.StatusForbidden},
		},
	}

	db, err := prepareDatabase(t.Context(), t)
	if err != nil {
		t.Fatalf("prepareDatabase() error = %v", err)
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			h := newTestHandler(t, db, tt.grants)

			req := httptest.NewRequestWithContext(t.Context(), tt.method, tt.target, strings.NewReader(tt.body))
			for name, value := range tt.headers {
				req.Header.Set(name, value)
			}
			rr := httptest.NewRecorder()
			h.ServeHTTP(rr, req)

			if !slices.Contains(tt.wantStatuses, rr.Result().StatusCode) {
				t.Errorf("status = %d, want one of %v; body: %s", rr.Result().StatusCode, tt.wantStatuses, rr.Body.String())
			}
		})
	}
}
