version: '2'
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 25
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/go-playground/errors/v5
            - github.com/gofrs/uuid
            - github.com/google/go-cmp/cmp
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 25
    godox:
      keywords:
        - TODO
        - BUG
    lll:
      line-length: 200
    misspell:
      locale: US
    nestif:
      min-complexity: 10
    tagliatelle:
      case:
        rules:
          json: camel
        use-field-name: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .Cause(
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - goconst
          - gocyclo
          - lll
          - mnd
          - nlreturn
          - scopelint
        path: _test\.go
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'Message' want 'message'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'MessageId' want 'messageId'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'Signature' want 'signature'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'SignatureVersion' want 'SignatureVersion'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'SigningCertURL' want 'signingCertURL'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'SubscribeURL' want 'subscribeURL'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'Subject' want 'subject'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'Timestamp' want 'timestamp'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'Token' want 'token'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'TopicArn' want 'topicArn'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'Type' want 'type'
      - linters:
          - tagliatelle
        path: sns\.go
        text: got 'UnsubscribeURL' want 'unsubscribeURL'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
