// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package virtualresources

import (
	"context"
	"iter"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/google/go-cmp/cmp"
)

func (PilotAssignment) Resource() accesstypes.Resource {
	return "PilotAssignments"
}

func (PilotAssignment) DefaultConfig() resource.Config {
	return resource.Config{}
}

// pilotAssignmentRead mirrors the wire shape the resource routes list
// and read, so a query armed with Enforce meets the field permissions the routes
// enforce; pilotAssignmentReadSets holds one Set per read operation.
type pilotAssignmentRead struct {
	SquadronID   ccc.UUID `json:"squadronId"   perm:"-"`
	UserID       string   `json:"userId"       perm:"-"`
	SectorID     string   `json:"sectorId"`
	SquadronName string   `json:"squadronName"`
	WingName     string   `json:"wingName"`
}

var pilotAssignmentReadSets resource.SetCache[PilotAssignment, pilotAssignmentRead]

type PilotAssignmentQuery struct {
	qSet *resource.QuerySet[PilotAssignment]
	// caller arms Read and List against a request's caller; nil runs them trusted.
	caller *resource.Caller
}

func NewPilotAssignmentQuery() *PilotAssignmentQuery {
	return &PilotAssignmentQuery{qSet: resource.NewQuerySet(resource.NewMetadata[PilotAssignment]())}
}

func NewPilotAssignmentQueryFromQuerySet(qSet *resource.QuerySet[PilotAssignment]) *PilotAssignmentQuery {
	return &PilotAssignmentQuery{qSet: qSet}
}

// Enforce arms the query against the caller a generated handler stamped on the
// context (resource.CallerFrom): Read runs the routes' Read permission gate and List
// the List gate — resource, then the requested fields, conditional grants riding the
// query — before touching the database. Without it the query runs trusted.
func (q *PilotAssignmentQuery) Enforce(caller *resource.Caller) *PilotAssignmentQuery {
	q.caller = caller

	return q
}

func (q *PilotAssignmentQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[PilotAssignment], error) {
	if q.caller != nil {
		q.qSet.Enforce(q.caller, pilotAssignmentReadSets.For(accesstypes.Read), accesstypes.Read)
	}

	return q.qSet.Read(ctx, txn)
}

func (q *PilotAssignmentQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[PilotAssignment], error] {
	if q.caller != nil {
		q.qSet.Enforce(q.caller, pilotAssignmentReadSets.For(accesstypes.List), accesstypes.List)
	}

	return q.qSet.List(ctx, txn)
}

func (q *PilotAssignmentQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[PilotAssignment], error]] {
	if q.caller != nil {
		q.qSet.Enforce(q.caller, pilotAssignmentReadSets.For(accesstypes.List), accesstypes.List)
	}

	return q.qSet.BatchList(ctx, client, size)
}

func (q *PilotAssignmentQuery) AddColumns(c *PilotAssignmentColumns) *PilotAssignmentQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *PilotAssignmentQuery) Where(c PilotAssignmentQueryClause) *PilotAssignmentQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *PilotAssignmentQuery) Sort(sort *PilotAssignmentSort) *PilotAssignmentQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *PilotAssignmentQuery) Limit(n uint64) *PilotAssignmentQuery {
	q.qSet.SetLimit(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *PilotAssignmentQuery) Diff(got *PilotAssignmentQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type PilotAssignmentColumns struct {
	fields []accesstypes.Field
}

func NewPilotAssignmentColumns() *PilotAssignmentColumns {
	return &PilotAssignmentColumns{}
}

func (c *PilotAssignmentColumns) All() *PilotAssignmentColumns {
	c.fields = []accesstypes.Field{
		"SquadronID",
		"UserID",
		"SectorID",
		"SquadronName",
		"WingName",
	}

	return c
}

func (c *PilotAssignmentColumns) SquadronID() *PilotAssignmentColumns {
	c.fields = append(c.fields, "SquadronID")

	return c
}

func (c *PilotAssignmentColumns) UserID() *PilotAssignmentColumns {
	c.fields = append(c.fields, "UserID")

	return c
}

func (c *PilotAssignmentColumns) SectorID() *PilotAssignmentColumns {
	c.fields = append(c.fields, "SectorID")

	return c
}

func (c *PilotAssignmentColumns) SquadronName() *PilotAssignmentColumns {
	c.fields = append(c.fields, "SquadronName")

	return c
}

func (c *PilotAssignmentColumns) WingName() *PilotAssignmentColumns {
	c.fields = append(c.fields, "WingName")

	return c
}

type PilotAssignmentQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewPilotAssignmentQueryClause() PilotAssignmentQueryPartialClause {
	return PilotAssignmentQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p PilotAssignmentQueryPartialClause) Group(qc PilotAssignmentQueryClause) PilotAssignmentQueryClause {
	return PilotAssignmentQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p PilotAssignmentQueryPartialClause) SquadronID() PilotAssignmentQueryIdent[ccc.UUID] {
	return PilotAssignmentQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("SquadronID", p.partialClause, true)}
}

func (p PilotAssignmentQueryPartialClause) UserID() PilotAssignmentQueryIdent[string] {
	return PilotAssignmentQueryIdent[string]{Ident: resource.NewIdent[string]("UserID", p.partialClause, true)}
}

func (p PilotAssignmentQueryPartialClause) SectorID() PilotAssignmentQueryIdent[string] {
	return PilotAssignmentQueryIdent[string]{Ident: resource.NewIdent[string]("SectorID", p.partialClause, true)}
}

func (p PilotAssignmentQueryPartialClause) SquadronName() PilotAssignmentQueryIdent[string] {
	return PilotAssignmentQueryIdent[string]{Ident: resource.NewIdent[string]("SquadronName", p.partialClause, true)}
}

func (p PilotAssignmentQueryPartialClause) WingName() PilotAssignmentQueryIdent[string] {
	return PilotAssignmentQueryIdent[string]{Ident: resource.NewIdent[string]("WingName", p.partialClause, true)}
}

type PilotAssignmentQueryClause struct {
	clause resource.QueryClause
}

func (qc PilotAssignmentQueryClause) And() PilotAssignmentQueryPartialClause {
	return PilotAssignmentQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc PilotAssignmentQueryClause) Or() PilotAssignmentQueryPartialClause {
	return PilotAssignmentQueryPartialClause{partialClause: qc.clause.Or()}
}

type PilotAssignmentQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i PilotAssignmentQueryIdent[T]) Equal(v ...T) PilotAssignmentQueryClause {
	return PilotAssignmentQueryClause{clause: i.Ident.Equal(v...)}
}

func (i PilotAssignmentQueryIdent[T]) NotEqual(v ...T) PilotAssignmentQueryClause {
	return PilotAssignmentQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i PilotAssignmentQueryIdent[T]) GreaterThan(v T) PilotAssignmentQueryClause {
	return PilotAssignmentQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i PilotAssignmentQueryIdent[T]) GreaterThanEq(v T) PilotAssignmentQueryClause {
	return PilotAssignmentQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i PilotAssignmentQueryIdent[T]) LessThan(v T) PilotAssignmentQueryClause {
	return PilotAssignmentQueryClause{clause: i.Ident.LessThan(v)}
}

func (i PilotAssignmentQueryIdent[T]) LessThanEq(v T) PilotAssignmentQueryClause {
	return PilotAssignmentQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i PilotAssignmentQueryIdent[T]) IsNull() PilotAssignmentQueryClause {
	return PilotAssignmentQueryClause{clause: i.Ident.IsNull()}
}

func (i PilotAssignmentQueryIdent[T]) IsNotNull() PilotAssignmentQueryClause {
	return PilotAssignmentQueryClause{clause: i.Ident.IsNotNull()}
}

type PilotAssignmentSortBuilder struct {
	*pilotAssignmentSort
}

func NewPilotAssignmentSort() *PilotAssignmentSortBuilder {
	return &PilotAssignmentSortBuilder{pilotAssignmentSort: &pilotAssignmentSort{}}
}

type pilotAssignmentSort struct {
	sortFields []resource.SortField
}

func (c *pilotAssignmentSort) addField(field string) *PilotAssignmentSort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &PilotAssignmentSort{pilotAssignmentSort: c}
}

func (c *pilotAssignmentSort) SquadronID() *PilotAssignmentSort {
	return c.addField("SquadronID")
}

func (c *pilotAssignmentSort) UserID() *PilotAssignmentSort {
	return c.addField("UserID")
}

func (c *pilotAssignmentSort) SectorID() *PilotAssignmentSort {
	return c.addField("SectorID")
}

func (c *pilotAssignmentSort) SquadronName() *PilotAssignmentSort {
	return c.addField("SquadronName")
}

func (c *pilotAssignmentSort) WingName() *PilotAssignmentSort {
	return c.addField("WingName")
}

type PilotAssignmentSort struct {
	*pilotAssignmentSort
}

func (s *PilotAssignmentSort) Asc() *PilotAssignmentSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *PilotAssignmentSort) Desc() *PilotAssignmentSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}
