// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package virtualresources

import (
	"context"
	"iter"

	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/google/go-cmp/cmp"
)

func (FeeByKind) Resource() accesstypes.Resource {
	return "FeeByKinds"
}

func (FeeByKind) DefaultConfig() resource.Config {
	return resource.Config{}
}

type FeeByKindQuery struct {
	qSet *resource.QuerySet[FeeByKind]
}

func NewFeeByKindQuery() *FeeByKindQuery {
	return &FeeByKindQuery{qSet: resource.NewQuerySet(resource.NewMetadata[FeeByKind]())}
}

func NewFeeByKindQueryFromQuerySet(qSet *resource.QuerySet[FeeByKind]) *FeeByKindQuery {
	return &FeeByKindQuery{qSet: qSet}
}

func (q *FeeByKindQuery) SetKindID(v string) *FeeByKindQuery {
	q.qSet.SetKey("KindID", v)

	return q
}

func (q *FeeByKindQuery) KindID() string {
	v, _ := q.qSet.Key("KindID").(string)

	return v
}

func (q *FeeByKindQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[FeeByKind], error) {
	return q.qSet.Read(ctx, txn)
}

func (q *FeeByKindQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[FeeByKind], error] {
	return q.qSet.List(ctx, txn)
}

func (q *FeeByKindQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[FeeByKind], error]] {
	return q.qSet.BatchList(ctx, client, size)
}

func (q *FeeByKindQuery) AddColumns(c *FeeByKindColumns) *FeeByKindQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *FeeByKindQuery) Where(c FeeByKindQueryClause) *FeeByKindQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *FeeByKindQuery) Sort(sort *FeeByKindSort) *FeeByKindQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *FeeByKindQuery) Limit(n uint64) *FeeByKindQuery {
	q.qSet.SetLimit(&n)

	return q
}

func (q *FeeByKindQuery) Offset(n uint64) *FeeByKindQuery {
	q.qSet.SetOffset(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *FeeByKindQuery) Diff(got *FeeByKindQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type FeeByKindColumns struct {
	fields []accesstypes.Field
}

func NewFeeByKindColumns() *FeeByKindColumns {
	return &FeeByKindColumns{}
}

func (c *FeeByKindColumns) All() *FeeByKindColumns {
	c.fields = []accesstypes.Field{
		"KindID",
		"MissionCount",
		"TotalFee",
		"TopFee",
	}

	return c
}

func (c *FeeByKindColumns) KindID() *FeeByKindColumns {
	c.fields = append(c.fields, "KindID")

	return c
}

func (c *FeeByKindColumns) MissionCount() *FeeByKindColumns {
	c.fields = append(c.fields, "MissionCount")

	return c
}

func (c *FeeByKindColumns) TotalFee() *FeeByKindColumns {
	c.fields = append(c.fields, "TotalFee")

	return c
}

func (c *FeeByKindColumns) TopFee() *FeeByKindColumns {
	c.fields = append(c.fields, "TopFee")

	return c
}

type FeeByKindQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewFeeByKindQueryClause() FeeByKindQueryPartialClause {
	return FeeByKindQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p FeeByKindQueryPartialClause) Group(qc FeeByKindQueryClause) FeeByKindQueryClause {
	return FeeByKindQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p FeeByKindQueryPartialClause) KindID() FeeByKindQueryIdent[string] {
	return FeeByKindQueryIdent[string]{Ident: resource.NewIdent[string]("KindID", p.partialClause, true)}
}

type FeeByKindQueryClause struct {
	clause resource.QueryClause
}

func (qc FeeByKindQueryClause) And() FeeByKindQueryPartialClause {
	return FeeByKindQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc FeeByKindQueryClause) Or() FeeByKindQueryPartialClause {
	return FeeByKindQueryPartialClause{partialClause: qc.clause.Or()}
}

type FeeByKindQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i FeeByKindQueryIdent[T]) Equal(v ...T) FeeByKindQueryClause {
	return FeeByKindQueryClause{clause: i.Ident.Equal(v...)}
}

func (i FeeByKindQueryIdent[T]) NotEqual(v ...T) FeeByKindQueryClause {
	return FeeByKindQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i FeeByKindQueryIdent[T]) GreaterThan(v T) FeeByKindQueryClause {
	return FeeByKindQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i FeeByKindQueryIdent[T]) GreaterThanEq(v T) FeeByKindQueryClause {
	return FeeByKindQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i FeeByKindQueryIdent[T]) LessThan(v T) FeeByKindQueryClause {
	return FeeByKindQueryClause{clause: i.Ident.LessThan(v)}
}

func (i FeeByKindQueryIdent[T]) LessThanEq(v T) FeeByKindQueryClause {
	return FeeByKindQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i FeeByKindQueryIdent[T]) IsNull() FeeByKindQueryClause {
	return FeeByKindQueryClause{clause: i.Ident.IsNull()}
}

func (i FeeByKindQueryIdent[T]) IsNotNull() FeeByKindQueryClause {
	return FeeByKindQueryClause{clause: i.Ident.IsNotNull()}
}

type FeeByKindSortBuilder struct {
	*feeByKindSort
}

func NewFeeByKindSort() *FeeByKindSortBuilder {
	return &FeeByKindSortBuilder{feeByKindSort: &feeByKindSort{}}
}

type feeByKindSort struct {
	sortFields []resource.SortField
}

func (c *feeByKindSort) addField(field string) *FeeByKindSort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &FeeByKindSort{feeByKindSort: c}
}

func (c *feeByKindSort) KindID() *FeeByKindSort {
	return c.addField("KindID")
}

func (c *feeByKindSort) MissionCount() *FeeByKindSort {
	return c.addField("MissionCount")
}

func (c *feeByKindSort) TotalFee() *FeeByKindSort {
	return c.addField("TotalFee")
}

func (c *feeByKindSort) TopFee() *FeeByKindSort {
	return c.addField("TopFee")
}

type FeeByKindSort struct {
	*feeByKindSort
}

func (s *FeeByKindSort) Asc() *FeeByKindSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *FeeByKindSort) Desc() *FeeByKindSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}
