// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/computedresources

package app

import (
	"net/http"

	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource/lodestar/pkg/computedresources"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
	"github.com/shopspring/decimal"
)

func (a *App) ServiceLedgers() http.HandlerFunc {
	type serviceLedger struct {
		SectorID        string          `json:"sectorId"        perm:"-"`
		Name            string          `json:"name"`
		OpenMissions    int64           `json:"openMissions"`
		FeesOutstanding decimal.Decimal `json:"feesOutstanding"`
		Settlements     decimal.Decimal `json:"settlements"`
	}

	type response []map[string]any

	decoder := NewComputedQueryDecoder[computedresources.ServiceLedger, serviceLedger](accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.GlobalScope())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		resp := response{}
		for row, err := range computedresources.ListServiceLedger(ctx, querySet, a.ResourceClient(), a.ComputedClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*serviceLedger)(row)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "SectorID":
					rmap["sectorId"] = rec.SectorID
				case "Name":
					rmap["name"] = rec.Name
				case "OpenMissions":
					rmap["openMissions"] = rec.OpenMissions
				case "FeesOutstanding":
					rmap["feesOutstanding"] = rec.FeesOutstanding
				case "Settlements":
					rmap["settlements"] = rec.Settlements
				}
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
