// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/lodestar/pkg/resources"
	"github.com/cccteam/ccc/resource/lodestar/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
)

func (a *App) Ships() http.HandlerFunc {
	type ship struct {
		ID          ccc.UUID   `json:"id"          index:"true" perm:"-"`
		HangarID    ccc.UUID   `json:"hangarId"    index:"true"`
		ClassID     ccc.UUID   `json:"classId"     index:"true"`
		Registry    string     `json:"registry"    index:"true"`
		Name        string     `json:"name"`
		LastRefitAt *time.Time `json:"lastRefitAt"`
		UpdatedAt   *time.Time `json:"updatedAt"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[resources.Ship, ship](accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewShipQueryFromQuerySet(querySet)

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*ship)(&row.Data)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "ID":
					if !row.Masked("id") {
						rmap["id"] = rec.ID
					}
				case "HangarID":
					if !row.Masked("hangarId") {
						rmap["hangarId"] = rec.HangarID
					}
				case "ClassID":
					if !row.Masked("classId") {
						rmap["classId"] = rec.ClassID
					}
				case "Registry":
					if !row.Masked("registry") {
						rmap["registry"] = rec.Registry
					}
				case "Name":
					if !row.Masked("name") {
						rmap["name"] = rec.Name
					}
				case "LastRefitAt":
					if !row.Masked("lastRefitAt") {
						rmap["lastRefitAt"] = rec.LastRefitAt
					}
				case "UpdatedAt":
					if !row.Masked("updatedAt") {
						rmap["updatedAt"] = rec.UpdatedAt
					}
				}
			}
			if capabilities := row.Capabilities(); capabilities != nil {
				rmap[resource.CapabilitiesProperty] = capabilities
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}

func (a *App) Ship() http.HandlerFunc {
	type response struct {
		ID          ccc.UUID   `json:"id"          index:"true" perm:"-"`
		HangarID    ccc.UUID   `json:"hangarId"`
		ClassID     ccc.UUID   `json:"classId"`
		Registry    string     `json:"registry"    index:"true"`
		Name        string     `json:"name"`
		LastRefitAt *time.Time `json:"lastRefitAt"`
		UpdatedAt   *time.Time `json:"updatedAt"`
	}

	decoder := NewQueryDecoder[resources.Ship, response](accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		id := httpio.Param[ccc.UUID](r, router.ShipID)

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewShipQueryFromQuerySet(querySet).SetID(id)

		row, err := res.Read(ctx, a.ResourceClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		rec := (*response)(&row.Data)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "ID":
				if !row.Masked("id") {
					rmap["id"] = rec.ID
				}
			case "HangarID":
				if !row.Masked("hangarId") {
					rmap["hangarId"] = rec.HangarID
				}
			case "ClassID":
				if !row.Masked("classId") {
					rmap["classId"] = rec.ClassID
				}
			case "Registry":
				if !row.Masked("registry") {
					rmap["registry"] = rec.Registry
				}
			case "Name":
				if !row.Masked("name") {
					rmap["name"] = rec.Name
				}
			case "LastRefitAt":
				if !row.Masked("lastRefitAt") {
					rmap["lastRefitAt"] = rec.LastRefitAt
				}
			case "UpdatedAt":
				if !row.Masked("updatedAt") {
					rmap["updatedAt"] = rec.UpdatedAt
				}
			}
		}
		if capabilities := row.Capabilities(); capabilities != nil {
			rmap[resource.CapabilitiesProperty] = capabilities
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}
