// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"
	"slices"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/lodestar/pkg/resources"
	"github.com/cccteam/ccc/resource/lodestar/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
)

func (a *App) RefitTasks() http.HandlerFunc {
	type refitTask struct {
		RefitID      ccc.UUID `json:"refitId"      index:"true" perm:"-"`
		TaskNumber   int64    `json:"taskNumber"   perm:"-"`
		Instructions string   `json:"instructions"`
		Done         bool     `json:"done"`
		Notes        *string  `json:"notes"`
		PhotoKey     *string  `json:"-"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[resources.RefitTask, refitTask](a, accesstypes.List).
		WithPaging(resource.Paging{Order: []resource.SortField{{Field: "TaskNumber", Direction: resource.SortAscending}}, DefaultLimit: 25, MaxLimit: 200})

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewRefitTaskQueryFromQuerySet(querySet)

		// The page: a count first when asked, then the rows, one past the page size
		// so the Link header knows whether a next page exists.
		page := querySet.Page()
		if err := page.Count(ctx, a.ResourceClient()); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			if !page.Add(row) {
				break
			}
			rec := (*refitTask)(&row.Data)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "RefitID":
					if !row.Masked("refitId") {
						rmap["refitId"] = rec.RefitID
					}
				case "TaskNumber":
					if !row.Masked("taskNumber") {
						rmap["taskNumber"] = rec.TaskNumber
					}
				case "Instructions":
					if !row.Masked("instructions") {
						rmap["instructions"] = rec.Instructions
					}
				case "Done":
					if !row.Masked("done") {
						rmap["done"] = rec.Done
					}
				case "Notes":
					if !row.Masked("notes") {
						rmap["notes"] = rec.Notes
					}
				}
			}
			if capabilities := row.Capabilities(); capabilities != nil {
				rmap[resource.CapabilitiesProperty] = capabilities
			}
			resp = append(resp, rmap)
		}
		if page.Reversed() {
			slices.Reverse(resp)
		}
		if err := page.WriteHeaders(w, r); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}

func (a *App) RefitTask() http.HandlerFunc {
	type response struct {
		RefitID      ccc.UUID `json:"refitId"      index:"true" perm:"-"`
		TaskNumber   int64    `json:"taskNumber"   index:"true" perm:"-"`
		Instructions string   `json:"instructions"`
		Done         bool     `json:"done"`
		Notes        *string  `json:"notes"`
		PhotoKey     *string  `json:"-"`
	}

	decoder := NewQueryDecoder[resources.RefitTask, response](a, accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		refitID := httpio.Param[ccc.UUID](r, router.RefitTaskRefitID)
		taskNumber := httpio.Param[int64](r, router.RefitTaskTaskNumber)

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewRefitTaskQueryFromQuerySet(querySet).SetRefitID(refitID).SetTaskNumber(taskNumber)

		row, err := res.Read(ctx, a.ResourceClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		rec := (*response)(&row.Data)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "RefitID":
				if !row.Masked("refitId") {
					rmap["refitId"] = rec.RefitID
				}
			case "TaskNumber":
				if !row.Masked("taskNumber") {
					rmap["taskNumber"] = rec.TaskNumber
				}
			case "Instructions":
				if !row.Masked("instructions") {
					rmap["instructions"] = rec.Instructions
				}
			case "Done":
				if !row.Masked("done") {
					rmap["done"] = rec.Done
				}
			case "Notes":
				if !row.Masked("notes") {
					rmap["notes"] = rec.Notes
				}
			}
		}
		if capabilities := row.Capabilities(); capabilities != nil {
			rmap[resource.CapabilitiesProperty] = capabilities
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}

func (a *App) RefitTaskPhoto() http.HandlerFunc {
	// The frame's projection: the key, and the columns that deliver the file, read for
	// the frame itself without field grants. The gate is Read on the resource and on
	// photo, the route's own field.
	type request struct {
		RefitID    ccc.UUID `json:"refitId"    perm:"-"`
		TaskNumber int64    `json:"taskNumber" perm:"-"`
		PhotoKey   *string  `json:"-"          perm:"-"`
	}

	decoder := NewFileDecoder[resources.RefitTask, request](a, "photo")

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		refitID := httpio.Param[ccc.UUID](r, router.RefitTaskRefitID)
		taskNumber := httpio.Param[int64](r, router.RefitTaskTaskNumber)

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		// The row through the resource's own read path: absent, cross-tenant, or hidden
		// by the caller's Read condition is 404, as on the read route.

		row, err := resources.NewRefitTaskQueryFromQuerySet(querySet).SetRefitID(refitID).SetTaskNumber(taskNumber).Read(ctx, a.ResourceClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		source := &row.Data
		file := resource.StoredFile{}
		if source.PhotoKey != nil {
			file.Key = *source.PhotoKey
		}

		if err := resource.ServeStoredFile(ctx, w, r, a.FileStore(), file, "photo", "RefitTask", refitID, taskNumber); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		return nil
	})
}
