// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/computedresources

package app

import (
	"net/http"
	"slices"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/lodestar/pkg/computedresources"
	"github.com/cccteam/ccc/resource/lodestar/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
	"github.com/shopspring/decimal"
)

func (a *App) ExpenseManifests() http.HandlerFunc {
	type expenseManifest struct {
		MissionID ccc.UUID        `json:"missionId" perm:"-"`
		Title     string          `json:"title"`
		Sorties   int64           `json:"sorties"`
		Expenses  decimal.Decimal `json:"expenses"`
	}

	type response []map[string]any

	decoder := NewComputedQueryDecoder[computedresources.ExpenseManifest, expenseManifest](a, accesstypes.List).
		WithPaging(resource.Paging{Order: []resource.SortField{{Field: "Title", Direction: resource.SortAscending}}, DefaultLimit: 25, MaxLimit: 200})

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		// The handler applies whatever part of the query the List function did not
		// take — the filter, the sort, the cursor, the page — over the rows it yields.
		page, err := querySet.Collect(computedresources.ListExpenseManifest(ctx, querySet, a.ResourceClient(), a.ComputedClient()))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		resp := response{}
		for _, row := range page.Rows() {
			rec := (*expenseManifest)(row)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "MissionID":
					rmap["missionId"] = rec.MissionID
				case "Title":
					rmap["title"] = rec.Title
				case "Sorties":
					rmap["sorties"] = rec.Sorties
				case "Expenses":
					rmap["expenses"] = rec.Expenses
				}
			}
			resp = append(resp, rmap)
		}
		if page.Reversed() {
			slices.Reverse(resp)
		}
		if err := page.WriteHeaders(w, r); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
func (a *App) ExpenseManifest() http.HandlerFunc {
	type response struct {
		MissionID ccc.UUID        `json:"missionId" perm:"-"`
		Title     string          `json:"title"`
		Sorties   int64           `json:"sorties"`
		Expenses  decimal.Decimal `json:"expenses"`
	}

	decoder := NewComputedQueryDecoder[computedresources.ExpenseManifest, response](a, accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		missionID := httpio.Param[ccc.UUID](r, router.ExpenseManifestMissionID)

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		row, err := computedresources.ReadExpenseManifest(ctx, missionID, querySet, a.ResourceClient(), a.ComputedClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		if row == nil {
			return httpio.NewEncoder(w).Ok(nil)
		}
		rec := (*response)(row)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "MissionID":
				rmap["missionId"] = rec.MissionID
			case "Title":
				rmap["title"] = rec.Title
			case "Sorties":
				rmap["sorties"] = rec.Sorties
			case "Expenses":
				rmap["expenses"] = rec.Expenses
			}
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}

func (a *App) ExpenseManifestContent() http.HandlerFunc {
	// The frame's projection is the key alone; the content function renders the file.
	// The gate is Read on the resource and on content, the route's own field,
	// checked at decode as every computed resource's gate is.
	type request struct {
		MissionID ccc.UUID `json:"missionId" perm:"-"`
	}

	decoder := NewComputedFileDecoder[computedresources.ExpenseManifest, request](a, "content")

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		missionID := httpio.Param[ccc.UUID](r, router.ExpenseManifestMissionID)

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		// The content function is the read path: nil is 404, as an absent row is on the
		// read route, and the frame writes the response.
		content, err := computedresources.ExpenseManifestContent(ctx, missionID, querySet, a.ResourceClient(), a.ComputedClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		if err := resource.ServeRenderedFile(w, r, content, "content", "ExpenseManifest", missionID); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		return nil
	})
}
