// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/rpc

package app

import (
	"context"
	"net/http"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/lodestar/pkg/resources"
	"github.com/cccteam/ccc/resource/lodestar/pkg/router"
	"github.com/cccteam/ccc/resource/lodestar/pkg/rpc"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
	"github.com/go-playground/errors/v5"
)

func (a *App) ReleaseConsignment() http.HandlerFunc {
	type request struct {
		ConsignmentID ccc.UUID `json:"consignmentId"`
	}

	decoder := NewTargetedRPCDecoder[rpc.ReleaseConsignment, request](a, accesstypes.Execute)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		params, gate, err := decoder.Decode(r, accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		p := (*rpc.ReleaseConsignment)(params)
		if err := a.ResourceClient().ExecuteFunc(ctx, func(ctx context.Context, txn resource.ReadWriteTransaction) error {
			// Declared target: locate the row within the tenancy predicate
			// before the body runs.
			row, err := resources.NewConsignmentQuery().
				AddColumns(resources.NewConsignmentColumns().SectorID()).
				SetID(p.ConsignmentID).
				Read(ctx, txn)
			if err != nil {
				return errors.Wrap(err, "resources.ConsignmentQuery.Read()")
			}
			if row == nil {
				return httpio.NewNotFoundMessagef("Consignment %s does not exist", p.ConsignmentID)
			}
			if ok, err := resource.TenantKeyEquals(row.Data.SectorID, domain); err != nil {
				return errors.Wrap(err, "resource.TenantKeyEquals()")
			} else if !ok {
				return httpio.NewNotFoundMessagef("Consignment %s does not exist", p.ConsignmentID)
			}

			// A row-referencing condition on the caller's Execute grant
			// evaluates against the located row, in this transaction.
			if err := gate.Enforce(ctx, txn, resource.ExecuteTarget{Resource: "Consignments", Label: "Consignment", PKColumn: "Id"}, p.ConsignmentID); err != nil {
				return err
			}
			if err := p.Execute(ctx, txn, a.RPCClient()); err != nil {
				return errors.Wrap(err, "Transaction.Execute()")
			}

			return nil
		}); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, errors.Wrap(err, "spanner.Client.ReadWriteTransaction()"))
		}

		return httpio.NewEncoder(w).Ok(nil)
	})
}
