// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"context"
	"net/http"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/lodestar/pkg/resources"
	"github.com/cccteam/ccc/resource/lodestar/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
	"github.com/go-playground/errors/v5"
)

func (a *App) Hangars() http.HandlerFunc {
	type hangar struct {
		ID       ccc.UUID `json:"id"       index:"true" perm:"-"`
		SectorID string   `json:"sectorId" index:"true"`
		Name     string   `json:"name"`
		Zone     string   `json:"zone"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[resources.Hangar, hangar](accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewHangarQueryFromQuerySet(querySet)

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*hangar)(&row.Data)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "ID":
					if !row.Masked("id") {
						rmap["id"] = rec.ID
					}
				case "SectorID":
					if !row.Masked("sectorId") {
						rmap["sectorId"] = rec.SectorID
					}
				case "Name":
					if !row.Masked("name") {
						rmap["name"] = rec.Name
					}
				case "Zone":
					if !row.Masked("zone") {
						rmap["zone"] = rec.Zone
					}
				}
			}
			if capabilities := row.Capabilities(); capabilities != nil {
				rmap[resource.CapabilitiesProperty] = capabilities
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}

func (a *App) Hangar() http.HandlerFunc {
	type response struct {
		ID       ccc.UUID `json:"id"       index:"true" perm:"-"`
		SectorID string   `json:"sectorId"`
		Name     string   `json:"name"`
		Zone     string   `json:"zone"`
	}

	decoder := NewQueryDecoder[resources.Hangar, response](accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		id := httpio.Param[ccc.UUID](r, router.HangarID)

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewHangarQueryFromQuerySet(querySet).SetID(id)

		row, err := res.Read(ctx, a.ResourceClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		rec := (*response)(&row.Data)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "ID":
				if !row.Masked("id") {
					rmap["id"] = rec.ID
				}
			case "SectorID":
				if !row.Masked("sectorId") {
					rmap["sectorId"] = rec.SectorID
				}
			case "Name":
				if !row.Masked("name") {
					rmap["name"] = rec.Name
				}
			case "Zone":
				if !row.Masked("zone") {
					rmap["zone"] = rec.Zone
				}
			}
		}
		if capabilities := row.Capabilities(); capabilities != nil {
			rmap[resource.CapabilitiesProperty] = capabilities
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}

func (a *App) PatchHangars() http.HandlerFunc {
	type request struct {
		ID       ccc.UUID `json:"-"`
		SectorID string   `json:"-"`
		Name     string   `json:"name"`
		Zone     string   `json:"zone"`
	}

	type response struct {
		IDs []ccc.UUID `json:"iDs"`
	}

	decoder := NewDecoder[resources.Hangar, request](a, accesstypes.Create, accesstypes.Update, accesstypes.Delete)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)

		var resp response
		eventSource := resource.UserEvent(ctx)

		if err := a.ResourceClient().ExecuteFunc(ctx, func(ctx context.Context, txn resource.ReadWriteTransaction) error {
			resp = response{}
			r, err := resource.CloneRequest(r)
			if err != nil {
				return errors.Wrap(err, "resource.CloneRequest()")
			}

			for op, err := range resource.Operations(r, "/{id}") {
				if err != nil {
					return errors.Wrap(err, "resource.Operations()")
				}

				patchSet, err := decoder.DecodeOperation(op, a.UserPermissions(r), accesstypes.DomainScope(domain))
				if err != nil {
					return errors.Wrap(err, "decoder.DecodeOperation()")
				}

				switch op.Type {
				case resource.OperationCreate:
					patch, err := resources.NewHangarCreatePatchFromPatchSet(patchSet)
					if err != nil {
						return errors.Wrap(err, "resources.NewHangarCreatePatchFromPatchSet()")
					}
					if err := patch.Buffer(ctx, txn, eventSource); err != nil {
						return errors.Wrap(err, "resources.HangarCreatePatch.Buffer()")
					}
					resp.IDs = append(resp.IDs, patch.ID())
				case resource.OperationUpdate:
					id := httpio.Param[ccc.UUID](op.Req, "id")
					if err := resources.NewHangarUpdatePatchFromPatchSet(id, patchSet).Buffer(ctx, txn, eventSource); err != nil {
						return errors.Wrap(err, "resources.HangarUpdatePatch.Buffer()")
					}
				case resource.OperationDelete:
					id := httpio.Param[ccc.UUID](op.Req, "id")
					if err := resources.NewHangarDeletePatchFromPatchSet(id, patchSet).Buffer(ctx, txn, eventSource); err != nil {
						return errors.Wrap(err, "resources.HangarDeletePatch.Buffer()")
					}
				}
			}

			return nil
		}); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
