// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"

	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/lodestar/pkg/resources"
	"github.com/cccteam/ccc/resource/lodestar/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
)

func (a *App) PilotCertifications() http.HandlerFunc {
	type pilotCertification struct {
		UserID          string `json:"userId"          index:"true" perm:"-"`
		CertificationID string `json:"certificationId" index:"true" perm:"-"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[resources.PilotCertification, pilotCertification](accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.GlobalScope())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewPilotCertificationQueryFromQuerySet(querySet)

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*pilotCertification)(&row.Data)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "UserID":
					if !row.Masked("userId") {
						rmap["userId"] = rec.UserID
					}
				case "CertificationID":
					if !row.Masked("certificationId") {
						rmap["certificationId"] = rec.CertificationID
					}
				}
			}
			if capabilities := row.Capabilities(); capabilities != nil {
				rmap[resource.CapabilitiesProperty] = capabilities
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}

func (a *App) PilotCertification() http.HandlerFunc {
	type response struct {
		UserID          string `json:"userId"          index:"true" perm:"-"`
		CertificationID string `json:"certificationId" index:"true" perm:"-"`
	}

	decoder := NewQueryDecoder[resources.PilotCertification, response](accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		userID := httpio.Param[string](r, router.PilotCertificationUserID)
		certificationID := httpio.Param[string](r, router.PilotCertificationCertificationID)

		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.GlobalScope())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewPilotCertificationQueryFromQuerySet(querySet).SetUserID(userID).SetCertificationID(certificationID)

		row, err := res.Read(ctx, a.ResourceClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		rec := (*response)(&row.Data)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "UserID":
				if !row.Masked("userId") {
					rmap["userId"] = rec.UserID
				}
			case "CertificationID":
				if !row.Masked("certificationId") {
					rmap["certificationId"] = rec.CertificationID
				}
			}
		}
		if capabilities := row.Capabilities(); capabilities != nil {
			rmap[resource.CapabilitiesProperty] = capabilities
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}
