// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/computedresources

package app

import (
	"net/http"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource/lodestar/pkg/computedresources"
	"github.com/cccteam/ccc/resource/lodestar/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
)

func (a *App) SectorHazardBoards() http.HandlerFunc {
	type sectorHazardBoard struct {
		ShipID       ccc.UUID  `json:"shipId"       perm:"-"`
		Subsystem    string    `json:"subsystem"    perm:"-"`
		ShipName     string    `json:"shipName"`
		SectorID     string    `json:"sectorId"`
		WorstReading float64   `json:"worstReading"`
		RecordedAt   time.Time `json:"recordedAt"`
	}

	type response []map[string]any

	decoder := NewComputedQueryDecoder[computedresources.SectorHazardBoard, sectorHazardBoard](accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		resp := response{}
		for row, err := range computedresources.ListSectorHazardBoard(ctx, querySet, a.ResourceClient(), a.ComputedClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*sectorHazardBoard)(row)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "ShipID":
					rmap["shipId"] = rec.ShipID
				case "Subsystem":
					rmap["subsystem"] = rec.Subsystem
				case "ShipName":
					rmap["shipName"] = rec.ShipName
				case "SectorID":
					rmap["sectorId"] = rec.SectorID
				case "WorstReading":
					rmap["worstReading"] = rec.WorstReading
				case "RecordedAt":
					rmap["recordedAt"] = rec.RecordedAt
				}
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
func (a *App) SectorHazardBoard() http.HandlerFunc {
	type response struct {
		ShipID       ccc.UUID  `json:"shipId"       perm:"-"`
		Subsystem    string    `json:"subsystem"    perm:"-"`
		ShipName     string    `json:"shipName"`
		SectorID     string    `json:"sectorId"`
		WorstReading float64   `json:"worstReading"`
		RecordedAt   time.Time `json:"recordedAt"`
	}

	decoder := NewComputedQueryDecoder[computedresources.SectorHazardBoard, response](accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		shipID := httpio.Param[ccc.UUID](r, router.SectorHazardBoardShipID)
		subsystem := httpio.Param[string](r, router.SectorHazardBoardSubsystem)

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		row, err := computedresources.ReadSectorHazardBoard(ctx, shipID, subsystem, querySet, a.ResourceClient(), a.ComputedClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		if row == nil {
			return httpio.NewEncoder(w).Ok(nil)
		}
		rec := (*response)(row)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "ShipID":
				rmap["shipId"] = rec.ShipID
			case "Subsystem":
				rmap["subsystem"] = rec.Subsystem
			case "ShipName":
				rmap["shipName"] = rec.ShipName
			case "SectorID":
				rmap["sectorId"] = rec.SectorID
			case "WorstReading":
				rmap["worstReading"] = rec.WorstReading
			case "RecordedAt":
				rmap["recordedAt"] = rec.RecordedAt
			}
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}
