// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/computedresources

package app

import (
	"net/http"
	"slices"

	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource/lodestar/pkg/computedresources"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
	"github.com/shopspring/decimal"
)

func (a *App) PilotCards() http.HandlerFunc {
	type pilotCard struct {
		UserID         string          `json:"userId"         perm:"-"`
		DisplayName    string          `json:"displayName"`
		Clearance      int64           `json:"clearance"`
		FeeLimit       decimal.Decimal `json:"feeLimit"`
		Certifications []string        `json:"certifications"`
		Squadrons      []string        `json:"squadrons"`
	}

	type response []map[string]any

	decoder := NewComputedQueryDecoder[computedresources.PilotCard, pilotCard](a, accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.GlobalScope())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		// The handler applies whatever part of the query the List function did not
		// take — the filter, the sort, the cursor, the page — over the rows it yields.
		page, err := querySet.Collect(computedresources.ListPilotCard(ctx, querySet, a.ResourceClient(), a.ComputedClient()))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		resp := response{}
		for _, row := range page.Rows() {
			rec := (*pilotCard)(row)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "UserID":
					rmap["userId"] = rec.UserID
				case "DisplayName":
					rmap["displayName"] = rec.DisplayName
				case "Clearance":
					rmap["clearance"] = rec.Clearance
				case "FeeLimit":
					rmap["feeLimit"] = rec.FeeLimit
				case "Certifications":
					rmap["certifications"] = rec.Certifications
				case "Squadrons":
					rmap["squadrons"] = rec.Squadrons
				}
			}
			resp = append(resp, rmap)
		}
		if page.Reversed() {
			slices.Reverse(resp)
		}
		if err := page.WriteHeaders(w, r); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
