// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/lodestar/pkg/resources"
	"github.com/cccteam/ccc/resource/lodestar/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
)

func (a *App) ShipClasses() http.HandlerFunc {
	type shipClass struct {
		ID          ccc.UUID `json:"id"          index:"true" perm:"-"`
		Designation string   `json:"designation" index:"true"`
		RoleID      string   `json:"roleId"      index:"true"`
		Tonnage     int64    `json:"tonnage"`
		Hardened    bool     `json:"hardened"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[resources.ShipClass, shipClass](accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.GlobalScope())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewShipClassQueryFromQuerySet(querySet)

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*shipClass)(&row.Data)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "ID":
					if !row.Masked("id") {
						rmap["id"] = rec.ID
					}
				case "Designation":
					if !row.Masked("designation") {
						rmap["designation"] = rec.Designation
					}
				case "RoleID":
					if !row.Masked("roleId") {
						rmap["roleId"] = rec.RoleID
					}
				case "Tonnage":
					if !row.Masked("tonnage") {
						rmap["tonnage"] = rec.Tonnage
					}
				case "Hardened":
					if !row.Masked("hardened") {
						rmap["hardened"] = rec.Hardened
					}
				}
			}
			if capabilities := row.Capabilities(); capabilities != nil {
				rmap[resource.CapabilitiesProperty] = capabilities
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}

func (a *App) ShipClass() http.HandlerFunc {
	type response struct {
		ID          ccc.UUID `json:"id"          index:"true" perm:"-"`
		Designation string   `json:"designation" index:"true"`
		RoleID      string   `json:"roleId"`
		Tonnage     int64    `json:"tonnage"`
		Hardened    bool     `json:"hardened"`
	}

	decoder := NewQueryDecoder[resources.ShipClass, response](accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		id := httpio.Param[ccc.UUID](r, router.ShipClassID)

		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.GlobalScope())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewShipClassQueryFromQuerySet(querySet).SetID(id)

		row, err := res.Read(ctx, a.ResourceClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		rec := (*response)(&row.Data)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "ID":
				if !row.Masked("id") {
					rmap["id"] = rec.ID
				}
			case "Designation":
				if !row.Masked("designation") {
					rmap["designation"] = rec.Designation
				}
			case "RoleID":
				if !row.Masked("roleId") {
					rmap["roleId"] = rec.RoleID
				}
			case "Tonnage":
				if !row.Masked("tonnage") {
					rmap["tonnage"] = rec.Tonnage
				}
			case "Hardened":
				if !row.Masked("hardened") {
					rmap["hardened"] = rec.Hardened
				}
			}
		}
		if capabilities := row.Capabilities(); capabilities != nil {
			rmap[resource.CapabilitiesProperty] = capabilities
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}
