// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"context"
	"net/http"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/lodestar/pkg/resources"
	"github.com/cccteam/ccc/resource/lodestar/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
	"github.com/go-playground/errors/v5"
	"github.com/shopspring/decimal"
)

func (a *App) PatchPortalResources() http.HandlerFunc {
	type clientContactRequest struct {
		ID          ccc.UUID `json:"-"`
		UserID      string   `json:"userId"`
		ClientID    ccc.UUID `json:"clientId"`
		DisplayName string   `json:"displayName"`
	}
	clientContactDecoder := NewDecoder[resources.ClientContact, clientContactRequest](a, accesstypes.Create, accesstypes.Update, accesstypes.Delete)

	type distressCallRequest struct {
		ID            ccc.UUID `json:"-"`
		SectorID      string   `json:"-"`
		Summary       string   `json:"summary"`
		Severity      int64    `json:"severity"`
		CallerContact *string  `json:"callerContact"`
		Transcript    *string  `json:"transcript"`
		CaseNumber    string   `json:"-"`
		FiledBy       string   `json:"-"`
	}
	distressCallDecoder := NewDecoder[resources.DistressCall, distressCallRequest](a, accesstypes.Create, accesstypes.Update, accesstypes.Delete)

	type missionRequest struct {
		ID                 ccc.UUID            `json:"-"`
		SectorID           string              `json:"-"`
		ClientID           ccc.UUID            `json:"clientId"`
		KindID             string              `json:"kindId"`
		Title              string              `json:"title"`
		Brief              *string             `json:"brief"`
		Hazard             int64               `json:"hazard"`
		Fee                decimal.Decimal     `json:"fee"`
		Deadline           time.Time           `json:"deadline"`
		RequiredCertID     *string             `json:"requiredCertId"`
		BookedBy           string              `json:"-"`
		AssignedSquadronID ccc.NullUUID        `json:"assignedSquadronId"`
		StatusID           string              `json:"-"`
		Notes              *string             `json:"notes"`
		Settlement         decimal.NullDecimal `json:"-"`
	}
	missionDecoder := NewDecoder[resources.Mission, missionRequest](a, accesstypes.Create, accesstypes.Update, accesstypes.Delete)

	type response map[string][]ccc.UUID

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		var (
			eventSource = resource.UserEvent(ctx)
			resp        response
		)
		userPermissions := a.UserPermissions(r)

		if err := a.ResourceClient().ExecuteFunc(ctx, func(ctx context.Context, txn resource.ReadWriteTransaction) error {
			resp = response{}
			r, err := resource.CloneRequest(r)
			if err != nil {
				return errors.Wrap(err, "resource.CloneRequest()")
			}

			for op, err := range resource.Operations(r, "/{resource}", resource.MatchPrefix()) {
				if err != nil {
					return errors.Wrap(err, "resource.Operations()")
				}

				switch httpio.Param[string](op.Req, "resource") {
				case "client-contacts":
					patchSet, err := clientContactDecoder.DecodeOperation(op, userPermissions, accesstypes.GlobalScope())
					if err != nil {
						return errors.Wrap(err, "clientContactDecoder.DecodeOperation()")
					}

					req, err := op.ReqWithPattern("/{resource}/{id}")
					if err != nil {
						return errors.Wrap(err, "op.ReqWithPattern()")
					}

					switch op.Type {
					case resource.OperationCreate:
						patch, err := resources.NewClientContactCreatePatchFromPatchSet(patchSet)
						if err != nil {
							return errors.Wrap(err, "clientContactCreatePatchFromPatchSet()")
						}
						if err := patch.Buffer(ctx, txn, eventSource); err != nil {
							return errors.Wrap(err, "resources.ClientContactCreatePatch.Buffer()")
						}
						resp["clientContacts"] = append(resp["clientContacts"], patch.ID())
					case resource.OperationUpdate:
						id := httpio.Param[ccc.UUID](req, "id")
						if err := resources.NewClientContactUpdatePatchFromPatchSet(id, patchSet).Buffer(ctx, txn, eventSource); err != nil {
							return errors.Wrap(err, "resources.ClientContactUpdatePatch.Buffer()")
						}
					case resource.OperationDelete:
						id := httpio.Param[ccc.UUID](req, "id")
						if err := resources.NewClientContactDeletePatchFromPatchSet(id, patchSet).Buffer(ctx, txn, eventSource); err != nil {
							return errors.Wrap(err, "resources.ClientContactDeletePatch.Buffer()")
						}
					}
				case "sectors":
					op, err := op.WithPrefixPattern("/sectors/{sectorID}/{resource}")
					if err != nil {
						return errors.Wrap(err, "resource.Operation.WithPrefixPattern()")
					}

					domain := httpio.Param[accesstypes.Domain](op.Req, router.Domain)
					if ok, err := a.DomainVisible(ctx, userPermissions.User(), domain); err != nil {
						return errors.Wrap(err, "DomainVisible()")
					} else if !ok {
						return httpio.NewBadRequestMessagef("unknown domain %q in operation path", domain)
					}

					switch httpio.Param[string](op.Req, "resource") {
					case "distress-calls":
						patchSet, err := distressCallDecoder.DecodeOperation(op, userPermissions, accesstypes.DomainScope(domain))
						if err != nil {
							return errors.Wrap(err, "distressCallDecoder.DecodeOperation()")
						}

						req, err := op.ReqWithPattern("/sectors/{sectorID}/{resource}/{id}")
						if err != nil {
							return errors.Wrap(err, "op.ReqWithPattern()")
						}

						switch op.Type {
						case resource.OperationCreate:
							patch, err := resources.NewDistressCallCreatePatchFromPatchSet(patchSet)
							if err != nil {
								return errors.Wrap(err, "distressCallCreatePatchFromPatchSet()")
							}
							if err := patch.Buffer(ctx, txn, eventSource); err != nil {
								return errors.Wrap(err, "resources.DistressCallCreatePatch.Buffer()")
							}
							resp["distressCalls"] = append(resp["distressCalls"], patch.ID())
						case resource.OperationUpdate:
							id := httpio.Param[ccc.UUID](req, "id")
							if err := resources.NewDistressCallUpdatePatchFromPatchSet(id, patchSet).Buffer(ctx, txn, eventSource); err != nil {
								return errors.Wrap(err, "resources.DistressCallUpdatePatch.Buffer()")
							}
						case resource.OperationDelete:
							id := httpio.Param[ccc.UUID](req, "id")
							if err := resources.NewDistressCallDeletePatchFromPatchSet(id, patchSet).Buffer(ctx, txn, eventSource); err != nil {
								return errors.Wrap(err, "resources.DistressCallDeletePatch.Buffer()")
							}
						}
					case "missions":
						patchSet, err := missionDecoder.DecodeOperation(op, userPermissions, accesstypes.DomainScope(domain))
						if err != nil {
							return errors.Wrap(err, "missionDecoder.DecodeOperation()")
						}

						req, err := op.ReqWithPattern("/sectors/{sectorID}/{resource}/{id}")
						if err != nil {
							return errors.Wrap(err, "op.ReqWithPattern()")
						}

						switch op.Type {
						case resource.OperationCreate:
							patch, err := resources.NewMissionCreatePatchFromPatchSet(patchSet)
							if err != nil {
								return errors.Wrap(err, "missionCreatePatchFromPatchSet()")
							}
							if err := patch.Buffer(ctx, txn, eventSource); err != nil {
								return errors.Wrap(err, "resources.MissionCreatePatch.Buffer()")
							}
							resp["missions"] = append(resp["missions"], patch.ID())
						case resource.OperationUpdate:
							id := httpio.Param[ccc.UUID](req, "id")
							if err := resources.NewMissionUpdatePatchFromPatchSet(id, patchSet).Buffer(ctx, txn, eventSource); err != nil {
								return errors.Wrap(err, "resources.MissionUpdatePatch.Buffer()")
							}
						case resource.OperationDelete:
							id := httpio.Param[ccc.UUID](req, "id")
							if err := resources.NewMissionDeletePatchFromPatchSet(id, patchSet).Buffer(ctx, txn, eventSource); err != nil {
								return errors.Wrap(err, "resources.MissionDeletePatch.Buffer()")
							}
						}
					default:
						return httpio.NewBadRequestMessagef("unknown domain-scoped resource %q in operation path", httpio.Param[string](op.Req, "resource"))
					}
				default:
					return httpio.NewBadRequestMessagef("unknown resource %q", httpio.Param[string](op.Req, "resource"))
				}
			}

			return nil
		}); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
