// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"
	"slices"

	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/lodestar/pkg/virtualresources"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
	"github.com/shopspring/decimal"
)

func (a *App) FeeByKinds() http.HandlerFunc {
	type feeByKind struct {
		KindID       string          `json:"kindId"       index:"true" perm:"-"`
		MissionCount int64           `json:"missionCount"`
		TotalFee     decimal.Decimal `json:"totalFee"`
		TopFee       decimal.Decimal `json:"topFee"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[virtualresources.FeeByKind, feeByKind](a, accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.GlobalScope())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := virtualresources.NewFeeByKindQueryFromQuerySet(querySet)

		// The page: a count first when asked, then the rows, one past the page size
		// so the Link header knows whether a next page exists.
		page := querySet.Page()
		if err := page.Count(ctx, a.ResourceClient()); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			if !page.Add(&row.Data) {
				break
			}
			rec := (*feeByKind)(&row.Data)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "KindID":
					if !row.Masked("kindId") {
						rmap["kindId"] = rec.KindID
					}
				case "MissionCount":
					if !row.Masked("missionCount") {
						rmap["missionCount"] = rec.MissionCount
					}
				case "TotalFee":
					if !row.Masked("totalFee") {
						rmap["totalFee"] = rec.TotalFee
					}
				case "TopFee":
					if !row.Masked("topFee") {
						rmap["topFee"] = rec.TopFee
					}
				}
			}
			if capabilities := row.Capabilities(); capabilities != nil {
				rmap[resource.CapabilitiesProperty] = capabilities
			}
			resp = append(resp, rmap)
		}
		if page.Reversed() {
			slices.Reverse(resp)
		}
		if err := page.WriteHeaders(w, r); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
