// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/resource/lodestar/pkg/resources"
	"github.com/cccteam/ccc/resource/lodestar/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
	"github.com/shopspring/decimal"
)

func (a *App) Refits() http.HandlerFunc {
	type refit struct {
		ID          ccc.UUID            `json:"id"          index:"true" perm:"-"`
		ShipID      ccc.UUID            `json:"shipId"      index:"true"`
		StatusID    string              `json:"statusId"    index:"true"`
		Estimate    decimal.NullDecimal `json:"estimate"`
		InspectedAt *time.Time          `json:"inspectedAt"`
		OpenedBy    string              `json:"openedBy"`
		Notes       *string             `json:"notes"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[resources.Refit, refit](accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewRefitQueryFromQuerySet(querySet)

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*refit)(&row.Data)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "ID":
					if !row.Masked("id") {
						rmap["id"] = rec.ID
					}
				case "ShipID":
					if !row.Masked("shipId") {
						rmap["shipId"] = rec.ShipID
					}
				case "StatusID":
					if !row.Masked("statusId") {
						rmap["statusId"] = rec.StatusID
					}
				case "Estimate":
					if !row.Masked("estimate") {
						rmap["estimate"] = rec.Estimate
					}
				case "InspectedAt":
					if !row.Masked("inspectedAt") {
						rmap["inspectedAt"] = rec.InspectedAt
					}
				case "OpenedBy":
					if !row.Masked("openedBy") {
						rmap["openedBy"] = rec.OpenedBy
					}
				case "Notes":
					if !row.Masked("notes") {
						rmap["notes"] = rec.Notes
					}
				}
			}
			if capabilities := row.Capabilities(); capabilities != nil {
				rmap[resource.CapabilitiesProperty] = capabilities
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}

func (a *App) Refit() http.HandlerFunc {
	type response struct {
		ID          ccc.UUID            `json:"id"          index:"true" perm:"-"`
		ShipID      ccc.UUID            `json:"shipId"`
		StatusID    string              `json:"statusId"`
		Estimate    decimal.NullDecimal `json:"estimate"`
		InspectedAt *time.Time          `json:"inspectedAt"`
		OpenedBy    string              `json:"openedBy"`
		Notes       *string             `json:"notes"`
	}

	decoder := NewQueryDecoder[resources.Refit, response](accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		id := httpio.Param[ccc.UUID](r, router.RefitID)

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewRefitQueryFromQuerySet(querySet).SetID(id)

		row, err := res.Read(ctx, a.ResourceClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		rec := (*response)(&row.Data)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "ID":
				if !row.Masked("id") {
					rmap["id"] = rec.ID
				}
			case "ShipID":
				if !row.Masked("shipId") {
					rmap["shipId"] = rec.ShipID
				}
			case "StatusID":
				if !row.Masked("statusId") {
					rmap["statusId"] = rec.StatusID
				}
			case "Estimate":
				if !row.Masked("estimate") {
					rmap["estimate"] = rec.Estimate
				}
			case "InspectedAt":
				if !row.Masked("inspectedAt") {
					rmap["inspectedAt"] = rec.InspectedAt
				}
			case "OpenedBy":
				if !row.Masked("openedBy") {
					rmap["openedBy"] = rec.OpenedBy
				}
			case "Notes":
				if !row.Masked("notes") {
					rmap["notes"] = rec.Notes
				}
			}
		}
		if capabilities := row.Capabilities(); capabilities != nil {
			rmap[resource.CapabilitiesProperty] = capabilities
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}
