// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package resources

import (
	"context"
	"iter"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/go-playground/errors/v5"
	"github.com/google/go-cmp/cmp"
)

func (Facility) Resource() accesstypes.Resource {
	return "Facilities"
}

func (Facility) DefaultConfig() resource.Config {
	return defaultConfig()
}

type FacilityQuery struct {
	qSet *resource.QuerySet[Facility]
}

func NewFacilityQuery() *FacilityQuery {
	return &FacilityQuery{qSet: resource.NewQuerySet(resource.NewMetadata[Facility]())}
}

func NewFacilityQueryFromQuerySet(qSet *resource.QuerySet[Facility]) *FacilityQuery {
	return &FacilityQuery{qSet: qSet}
}

func (q *FacilityQuery) SetID(v ccc.UUID) *FacilityQuery {
	q.qSet.SetKey("ID", v)

	return q
}

func (q *FacilityQuery) ID() ccc.UUID {
	v, _ := q.qSet.Key("ID").(ccc.UUID)

	return v
}

func (q *FacilityQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[Facility], error) {
	return q.qSet.Read(ctx, txn)
}

func (q *FacilityQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[Facility], error] {
	return q.qSet.List(ctx, txn)
}

func (q *FacilityQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[Facility], error]] {
	return q.qSet.BatchList(ctx, client, size)
}

func (q *FacilityQuery) AddColumns(c *FacilityColumns) *FacilityQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *FacilityQuery) Where(c FacilityQueryClause) *FacilityQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *FacilityQuery) Sort(sort *FacilitySort) *FacilityQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *FacilityQuery) Limit(n uint64) *FacilityQuery {
	q.qSet.SetLimit(&n)

	return q
}

func (q *FacilityQuery) Offset(n uint64) *FacilityQuery {
	q.qSet.SetOffset(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *FacilityQuery) Diff(got *FacilityQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type FacilityColumns struct {
	fields []accesstypes.Field
}

func NewFacilityColumns() *FacilityColumns {
	return &FacilityColumns{}
}

func (c *FacilityColumns) All() *FacilityColumns {
	c.fields = []accesstypes.Field{
		"ID",
		"ModuleID",
		"Name",
		"Kind",
	}

	return c
}

func (c *FacilityColumns) ID() *FacilityColumns {
	c.fields = append(c.fields, "ID")

	return c
}

func (c *FacilityColumns) ModuleID() *FacilityColumns {
	c.fields = append(c.fields, "ModuleID")

	return c
}

func (c *FacilityColumns) Name() *FacilityColumns {
	c.fields = append(c.fields, "Name")

	return c
}

func (c *FacilityColumns) Kind() *FacilityColumns {
	c.fields = append(c.fields, "Kind")

	return c
}

type FacilityQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewFacilityQueryClause() FacilityQueryPartialClause {
	return FacilityQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p FacilityQueryPartialClause) Group(qc FacilityQueryClause) FacilityQueryClause {
	return FacilityQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p FacilityQueryPartialClause) ID() FacilityQueryIdent[ccc.UUID] {
	return FacilityQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("ID", p.partialClause, true)}
}

func (p FacilityQueryPartialClause) ModuleID() FacilityQueryIdent[ccc.UUID] {
	return FacilityQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("ModuleID", p.partialClause, true)}
}

type FacilityQueryClause struct {
	clause resource.QueryClause
}

func (qc FacilityQueryClause) And() FacilityQueryPartialClause {
	return FacilityQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc FacilityQueryClause) Or() FacilityQueryPartialClause {
	return FacilityQueryPartialClause{partialClause: qc.clause.Or()}
}

type FacilityQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i FacilityQueryIdent[T]) Equal(v ...T) FacilityQueryClause {
	return FacilityQueryClause{clause: i.Ident.Equal(v...)}
}

func (i FacilityQueryIdent[T]) NotEqual(v ...T) FacilityQueryClause {
	return FacilityQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i FacilityQueryIdent[T]) GreaterThan(v T) FacilityQueryClause {
	return FacilityQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i FacilityQueryIdent[T]) GreaterThanEq(v T) FacilityQueryClause {
	return FacilityQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i FacilityQueryIdent[T]) LessThan(v T) FacilityQueryClause {
	return FacilityQueryClause{clause: i.Ident.LessThan(v)}
}

func (i FacilityQueryIdent[T]) LessThanEq(v T) FacilityQueryClause {
	return FacilityQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i FacilityQueryIdent[T]) IsNull() FacilityQueryClause {
	return FacilityQueryClause{clause: i.Ident.IsNull()}
}

func (i FacilityQueryIdent[T]) IsNotNull() FacilityQueryClause {
	return FacilityQueryClause{clause: i.Ident.IsNotNull()}
}

type FacilitySortBuilder struct {
	*facilitySort
}

func NewFacilitySort() *FacilitySortBuilder {
	return &FacilitySortBuilder{facilitySort: &facilitySort{}}
}

type facilitySort struct {
	sortFields []resource.SortField
}

func (c *facilitySort) addField(field string) *FacilitySort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &FacilitySort{facilitySort: c}
}

func (c *facilitySort) ID() *FacilitySort {
	return c.addField("ID")
}

func (c *facilitySort) ModuleID() *FacilitySort {
	return c.addField("ModuleID")
}

func (c *facilitySort) Name() *FacilitySort {
	return c.addField("Name")
}

func (c *facilitySort) Kind() *FacilitySort {
	return c.addField("Kind")
}

type FacilitySort struct {
	*facilitySort
}

func (s *FacilitySort) Asc() *FacilitySort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *FacilitySort) Desc() *FacilitySort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}

type FacilityCreatePatch struct {
	patchSet *resource.PatchSet[Facility]
}

func NewFacilityCreatePatchFromPatchSet(patchSet *resource.PatchSet[Facility]) (*FacilityCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &FacilityCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func NewFacilityCreatePatch() (*FacilityCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet := resource.NewPatchSet(resource.NewMetadata[Facility]()).
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &FacilityCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func (p *FacilityCreatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *FacilityCreatePatch) ToStruct() *Facility {
	return p.patchSet.ToStruct()
}

func (p *FacilityCreatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *FacilityCreatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *FacilityCreatePatch) registerDefaultFuncs() {
}

func (p *FacilityCreatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *FacilityCreatePatch) SetModuleID(v ccc.UUID) *FacilityCreatePatch {
	p.patchSet.Set("ModuleID", v)

	return p
}

func (p *FacilityCreatePatch) ModuleID() ccc.UUID {
	v, _ := p.patchSet.Get("ModuleID").(ccc.UUID)

	return v
}

func (p *FacilityCreatePatch) ModuleIDIsSet() bool {
	return p.patchSet.IsSet("ModuleID")
}

func (p *FacilityCreatePatch) SetName(v string) *FacilityCreatePatch {
	p.patchSet.Set("Name", v)

	return p
}

func (p *FacilityCreatePatch) Name() string {
	v, _ := p.patchSet.Get("Name").(string)

	return v
}

func (p *FacilityCreatePatch) NameIsSet() bool {
	return p.patchSet.IsSet("Name")
}

func (p *FacilityCreatePatch) SetKind(v string) *FacilityCreatePatch {
	p.patchSet.Set("Kind", v)

	return p
}

func (p *FacilityCreatePatch) Kind() string {
	v, _ := p.patchSet.Get("Kind").(string)

	return v
}

func (p *FacilityCreatePatch) KindIsSet() bool {
	return p.patchSet.IsSet("Kind")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *FacilityCreatePatch) Diff(got *FacilityCreatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type FacilityUpdatePatch struct {
	patchSet *resource.PatchSet[Facility]
}

func NewFacilityUpdatePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[Facility]) *FacilityUpdatePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &FacilityUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func NewFacilityUpdatePatch(id ccc.UUID) *FacilityUpdatePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Facility]()).
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &FacilityUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func (p *FacilityUpdatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *FacilityUpdatePatch) ToStruct() *Facility {
	return p.patchSet.ToStruct()
}

func (p *FacilityUpdatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *FacilityUpdatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *FacilityUpdatePatch) registerDefaultFuncs() {
}

func (p *FacilityUpdatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *FacilityUpdatePatch) SetModuleID(v ccc.UUID) *FacilityUpdatePatch {
	p.patchSet.Set("ModuleID", v)

	return p
}

func (p *FacilityUpdatePatch) ModuleID() ccc.UUID {
	v, _ := p.patchSet.Get("ModuleID").(ccc.UUID)

	return v
}

func (p *FacilityUpdatePatch) ModuleIDIsSet() bool {
	return p.patchSet.IsSet("ModuleID")
}

func (p *FacilityUpdatePatch) SetName(v string) *FacilityUpdatePatch {
	p.patchSet.Set("Name", v)

	return p
}

func (p *FacilityUpdatePatch) Name() string {
	v, _ := p.patchSet.Get("Name").(string)

	return v
}

func (p *FacilityUpdatePatch) NameIsSet() bool {
	return p.patchSet.IsSet("Name")
}

func (p *FacilityUpdatePatch) SetKind(v string) *FacilityUpdatePatch {
	p.patchSet.Set("Kind", v)

	return p
}

func (p *FacilityUpdatePatch) Kind() string {
	v, _ := p.patchSet.Get("Kind").(string)

	return v
}

func (p *FacilityUpdatePatch) KindIsSet() bool {
	return p.patchSet.IsSet("Kind")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *FacilityUpdatePatch) Diff(got *FacilityUpdatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type FacilityDeletePatch struct {
	patchSet *resource.PatchSet[Facility]
}

func NewFacilityDeletePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[Facility]) *FacilityDeletePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &FacilityDeletePatch{patchSet: patchSet}
}

func NewFacilityDeletePatch(id ccc.UUID) *FacilityDeletePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Facility]()).
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &FacilityDeletePatch{patchSet: patchSet}
}

func (p *FacilityDeletePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *FacilityDeletePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *FacilityDeletePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *FacilityDeletePatch) Diff(got *FacilityDeletePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}
