// Code generated by resourcegeneration. DO NOT EDIT.
// Source: apps/console/pkg/resources

package resources

import (
	"context"
	"iter"

	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/google/go-cmp/cmp"
)

func (Tenant) Resource() accesstypes.Resource {
	return "Tenants"
}

func (Tenant) DefaultConfig() resource.Config {
	return defaultConfig()
}

// tenantRead mirrors the wire shape the resource routes list
// and read, so a query armed with Enforce meets the field permissions the routes
// enforce; tenantReadSets holds one Set per read operation.
type tenantRead struct {
	ID   string `json:"id"   perm:"-"`
	Name string `json:"name"`
}

var tenantReadSets resource.SetCache[Tenant, tenantRead]

// tenantWrite mirrors the wire shape the resource routes
// accept on a mutation, so a patch armed with Enforce meets the field permissions the
// routes enforce; tenantWriteSets holds one Set per mutation.
type tenantWrite struct {
	ID   string `json:"-"`
	Name string `json:"name"`
}

var tenantWriteSets resource.SetCache[Tenant, tenantWrite]

type TenantQuery struct {
	qSet *resource.QuerySet[Tenant]
	// caller arms Read and List against a request's caller; nil runs them trusted.
	caller *resource.Caller
}

func NewTenantQuery() *TenantQuery {
	return &TenantQuery{qSet: resource.NewQuerySet(resource.NewMetadata[Tenant]())}
}

func NewTenantQueryFromQuerySet(qSet *resource.QuerySet[Tenant]) *TenantQuery {
	return &TenantQuery{qSet: qSet}
}

func (q *TenantQuery) SetID(v string) *TenantQuery {
	q.qSet.SetKey("ID", v)

	return q
}

func (q *TenantQuery) ID() string {
	v, _ := q.qSet.Key("ID").(string)

	return v
}

func (q *TenantQuery) SetName(v string) *TenantQuery {
	q.qSet.SetKey("Name", v)

	return q
}

func (q *TenantQuery) Name() string {
	v, _ := q.qSet.Key("Name").(string)

	return v
}

// Enforce arms the query against the caller a generated handler stamped on the
// context (resource.CallerFrom): Read runs the routes' Read permission gate and List
// the List gate — resource, then the requested fields, conditional grants riding the
// query — before touching the database. Without it the query runs trusted.
func (q *TenantQuery) Enforce(caller *resource.Caller) *TenantQuery {
	q.caller = caller

	return q
}

func (q *TenantQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[Tenant], error) {
	if q.caller != nil {
		q.qSet.Enforce(q.caller, tenantReadSets.For(accesstypes.Read), accesstypes.Read)
	}

	return q.qSet.Read(ctx, txn)
}

func (q *TenantQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[Tenant], error] {
	if q.caller != nil {
		q.qSet.Enforce(q.caller, tenantReadSets.For(accesstypes.List), accesstypes.List)
	}

	return q.qSet.List(ctx, txn)
}

func (q *TenantQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[Tenant], error]] {
	if q.caller != nil {
		q.qSet.Enforce(q.caller, tenantReadSets.For(accesstypes.List), accesstypes.List)
	}

	return q.qSet.BatchList(ctx, client, size)
}

func (q *TenantQuery) AddColumns(c *TenantColumns) *TenantQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *TenantQuery) Where(c TenantQueryClause) *TenantQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *TenantQuery) Sort(sort *TenantSort) *TenantQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *TenantQuery) Limit(n uint64) *TenantQuery {
	q.qSet.SetLimit(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *TenantQuery) Diff(got *TenantQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type TenantColumns struct {
	fields []accesstypes.Field
}

func NewTenantColumns() *TenantColumns {
	return &TenantColumns{}
}

func (c *TenantColumns) All() *TenantColumns {
	c.fields = []accesstypes.Field{
		"ID",
		"Name",
	}

	return c
}

func (c *TenantColumns) ID() *TenantColumns {
	c.fields = append(c.fields, "ID")

	return c
}

func (c *TenantColumns) Name() *TenantColumns {
	c.fields = append(c.fields, "Name")

	return c
}

type TenantQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewTenantQueryClause() TenantQueryPartialClause {
	return TenantQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p TenantQueryPartialClause) Group(qc TenantQueryClause) TenantQueryClause {
	return TenantQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p TenantQueryPartialClause) ID() TenantQueryIdent[string] {
	return TenantQueryIdent[string]{Ident: resource.NewIdent[string]("ID", p.partialClause, true)}
}

func (p TenantQueryPartialClause) Name() TenantQueryIdent[string] {
	return TenantQueryIdent[string]{Ident: resource.NewIdent[string]("Name", p.partialClause, true)}
}

type TenantQueryClause struct {
	clause resource.QueryClause
}

func (qc TenantQueryClause) And() TenantQueryPartialClause {
	return TenantQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc TenantQueryClause) Or() TenantQueryPartialClause {
	return TenantQueryPartialClause{partialClause: qc.clause.Or()}
}

type TenantQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i TenantQueryIdent[T]) Equal(v ...T) TenantQueryClause {
	return TenantQueryClause{clause: i.Ident.Equal(v...)}
}

func (i TenantQueryIdent[T]) NotEqual(v ...T) TenantQueryClause {
	return TenantQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i TenantQueryIdent[T]) GreaterThan(v T) TenantQueryClause {
	return TenantQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i TenantQueryIdent[T]) GreaterThanEq(v T) TenantQueryClause {
	return TenantQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i TenantQueryIdent[T]) LessThan(v T) TenantQueryClause {
	return TenantQueryClause{clause: i.Ident.LessThan(v)}
}

func (i TenantQueryIdent[T]) LessThanEq(v T) TenantQueryClause {
	return TenantQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i TenantQueryIdent[T]) IsNull() TenantQueryClause {
	return TenantQueryClause{clause: i.Ident.IsNull()}
}

func (i TenantQueryIdent[T]) IsNotNull() TenantQueryClause {
	return TenantQueryClause{clause: i.Ident.IsNotNull()}
}

type TenantSortBuilder struct {
	*tenantSort
}

func NewTenantSort() *TenantSortBuilder {
	return &TenantSortBuilder{tenantSort: &tenantSort{}}
}

type tenantSort struct {
	sortFields []resource.SortField
}

func (c *tenantSort) addField(field string) *TenantSort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &TenantSort{tenantSort: c}
}

func (c *tenantSort) ID() *TenantSort {
	return c.addField("ID")
}

func (c *tenantSort) Name() *TenantSort {
	return c.addField("Name")
}

type TenantSort struct {
	*tenantSort
}

func (s *TenantSort) Asc() *TenantSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *TenantSort) Desc() *TenantSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}

type TenantCreatePatch struct {
	patchSet *resource.PatchSet[Tenant]
}

func NewTenantCreatePatchFromPatchSet(id string, patchSet *resource.PatchSet[Tenant]) *TenantCreatePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &TenantCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func NewTenantCreatePatch(id string) *TenantCreatePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Tenant]()).
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &TenantCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func (p *TenantCreatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *TenantCreatePatch) ToStruct() *Tenant {
	return p.patchSet.ToStruct()
}

func (p *TenantCreatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *TenantCreatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

// Enforce arms the mutation against the caller a generated handler stamped on the
// context (resource.CallerFrom): Apply and Buffer run the full pipeline the resource
// routes run for Create — the static field gate, the fold of conditional grants,
// the live check against the real row inside the transaction, and the tenancy
// check — and refuse with the same Forbidden the routes answer. Without it the
// mutation runs trusted.
func (p *TenantCreatePatch) Enforce(caller *resource.Caller) *TenantCreatePatch {
	p.patchSet.Enforce(caller, tenantWriteSets.For(accesstypes.Create), accesstypes.Create)

	return p
}

func (p *TenantCreatePatch) registerDefaultFuncs() {
}

func (p *TenantCreatePatch) ID() string {
	v, _ := p.patchSet.Key("ID").(string)

	return v
}

func (p *TenantCreatePatch) SetName(v string) *TenantCreatePatch {
	p.patchSet.Set("Name", v)

	return p
}

func (p *TenantCreatePatch) Name() string {
	v, _ := p.patchSet.Get("Name").(string)

	return v
}

func (p *TenantCreatePatch) NameIsSet() bool {
	return p.patchSet.IsSet("Name")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *TenantCreatePatch) Diff(got *TenantCreatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type TenantUpdatePatch struct {
	patchSet *resource.PatchSet[Tenant]
}

func NewTenantUpdatePatchFromPatchSet(id string, patchSet *resource.PatchSet[Tenant]) *TenantUpdatePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &TenantUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func NewTenantUpdatePatch(id string) *TenantUpdatePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Tenant]()).
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &TenantUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func (p *TenantUpdatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *TenantUpdatePatch) ToStruct() *Tenant {
	return p.patchSet.ToStruct()
}

func (p *TenantUpdatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *TenantUpdatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

// Enforce arms the mutation against the caller a generated handler stamped on the
// context (resource.CallerFrom): Apply and Buffer run the full pipeline the resource
// routes run for Update — the static field gate, the fold of conditional grants,
// the live check against the real row inside the transaction, and the tenancy
// check — and refuse with the same Forbidden the routes answer. Without it the
// mutation runs trusted.
func (p *TenantUpdatePatch) Enforce(caller *resource.Caller) *TenantUpdatePatch {
	p.patchSet.Enforce(caller, tenantWriteSets.For(accesstypes.Update), accesstypes.Update)

	return p
}

func (p *TenantUpdatePatch) registerDefaultFuncs() {
}

func (p *TenantUpdatePatch) ID() string {
	v, _ := p.patchSet.Key("ID").(string)

	return v
}

func (p *TenantUpdatePatch) SetName(v string) *TenantUpdatePatch {
	p.patchSet.Set("Name", v)

	return p
}

func (p *TenantUpdatePatch) Name() string {
	v, _ := p.patchSet.Get("Name").(string)

	return v
}

func (p *TenantUpdatePatch) NameIsSet() bool {
	return p.patchSet.IsSet("Name")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *TenantUpdatePatch) Diff(got *TenantUpdatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type TenantDeletePatch struct {
	patchSet *resource.PatchSet[Tenant]
}

func NewTenantDeletePatchFromPatchSet(id string, patchSet *resource.PatchSet[Tenant]) *TenantDeletePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &TenantDeletePatch{patchSet: patchSet}
}

func NewTenantDeletePatch(id string) *TenantDeletePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Tenant]()).
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &TenantDeletePatch{patchSet: patchSet}
}

func (p *TenantDeletePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *TenantDeletePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

// Enforce arms the mutation against the caller a generated handler stamped on the
// context (resource.CallerFrom): Apply and Buffer run the full pipeline the resource
// routes run for Delete — the static field gate, the fold of conditional grants,
// the live check against the real row inside the transaction, and the tenancy
// check — and refuse with the same Forbidden the routes answer. Without it the
// mutation runs trusted.
func (p *TenantDeletePatch) Enforce(caller *resource.Caller) *TenantDeletePatch {
	p.patchSet.Enforce(caller, tenantWriteSets.For(accesstypes.Delete), accesstypes.Delete)

	return p
}

func (p *TenantDeletePatch) ID() string {
	v, _ := p.patchSet.Key("ID").(string)

	return v
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *TenantDeletePatch) Diff(got *TenantDeletePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}
