// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package virtualresources

import (
	"context"
	"iter"

	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/google/go-cmp/cmp"
)

func (SpendByCategory) Resource() accesstypes.Resource {
	return "SpendByCategories"
}

func (SpendByCategory) DefaultConfig() resource.Config {
	return resource.Config{}
}

type SpendByCategoryQuery struct {
	qSet *resource.QuerySet[SpendByCategory]
}

func NewSpendByCategoryQuery() *SpendByCategoryQuery {
	return &SpendByCategoryQuery{qSet: resource.NewQuerySet(resource.NewMetadata[SpendByCategory]())}
}

func NewSpendByCategoryQueryFromQuerySet(qSet *resource.QuerySet[SpendByCategory]) *SpendByCategoryQuery {
	return &SpendByCategoryQuery{qSet: qSet}
}

func (q *SpendByCategoryQuery) SetCategory(v string) *SpendByCategoryQuery {
	q.qSet.SetKey("Category", v)

	return q
}

func (q *SpendByCategoryQuery) Category() string {
	v, _ := q.qSet.Key("Category").(string)

	return v
}

func (q *SpendByCategoryQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[SpendByCategory], error) {
	return q.qSet.Read(ctx, txn)
}

func (q *SpendByCategoryQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[SpendByCategory], error] {
	return q.qSet.List(ctx, txn)
}

func (q *SpendByCategoryQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[SpendByCategory], error]] {
	return q.qSet.BatchList(ctx, client, size)
}

func (q *SpendByCategoryQuery) AddColumns(c *SpendByCategoryColumns) *SpendByCategoryQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *SpendByCategoryQuery) Where(c SpendByCategoryQueryClause) *SpendByCategoryQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *SpendByCategoryQuery) Sort(sort *SpendByCategorySort) *SpendByCategoryQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *SpendByCategoryQuery) Limit(n uint64) *SpendByCategoryQuery {
	q.qSet.SetLimit(&n)

	return q
}

func (q *SpendByCategoryQuery) Offset(n uint64) *SpendByCategoryQuery {
	q.qSet.SetOffset(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *SpendByCategoryQuery) Diff(got *SpendByCategoryQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type SpendByCategoryColumns struct {
	fields []accesstypes.Field
}

func NewSpendByCategoryColumns() *SpendByCategoryColumns {
	return &SpendByCategoryColumns{}
}

func (c *SpendByCategoryColumns) All() *SpendByCategoryColumns {
	c.fields = []accesstypes.Field{
		"Category",
		"LineCount",
		"TotalQuantity",
		"TotalSpend",
	}

	return c
}

func (c *SpendByCategoryColumns) Category() *SpendByCategoryColumns {
	c.fields = append(c.fields, "Category")

	return c
}

func (c *SpendByCategoryColumns) LineCount() *SpendByCategoryColumns {
	c.fields = append(c.fields, "LineCount")

	return c
}

func (c *SpendByCategoryColumns) TotalQuantity() *SpendByCategoryColumns {
	c.fields = append(c.fields, "TotalQuantity")

	return c
}

func (c *SpendByCategoryColumns) TotalSpend() *SpendByCategoryColumns {
	c.fields = append(c.fields, "TotalSpend")

	return c
}

type SpendByCategoryQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewSpendByCategoryQueryClause() SpendByCategoryQueryPartialClause {
	return SpendByCategoryQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p SpendByCategoryQueryPartialClause) Group(qc SpendByCategoryQueryClause) SpendByCategoryQueryClause {
	return SpendByCategoryQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p SpendByCategoryQueryPartialClause) Category() SpendByCategoryQueryIdent[string] {
	return SpendByCategoryQueryIdent[string]{Ident: resource.NewIdent[string]("Category", p.partialClause, true)}
}

type SpendByCategoryQueryClause struct {
	clause resource.QueryClause
}

func (qc SpendByCategoryQueryClause) And() SpendByCategoryQueryPartialClause {
	return SpendByCategoryQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc SpendByCategoryQueryClause) Or() SpendByCategoryQueryPartialClause {
	return SpendByCategoryQueryPartialClause{partialClause: qc.clause.Or()}
}

type SpendByCategoryQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i SpendByCategoryQueryIdent[T]) Equal(v ...T) SpendByCategoryQueryClause {
	return SpendByCategoryQueryClause{clause: i.Ident.Equal(v...)}
}

func (i SpendByCategoryQueryIdent[T]) NotEqual(v ...T) SpendByCategoryQueryClause {
	return SpendByCategoryQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i SpendByCategoryQueryIdent[T]) GreaterThan(v T) SpendByCategoryQueryClause {
	return SpendByCategoryQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i SpendByCategoryQueryIdent[T]) GreaterThanEq(v T) SpendByCategoryQueryClause {
	return SpendByCategoryQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i SpendByCategoryQueryIdent[T]) LessThan(v T) SpendByCategoryQueryClause {
	return SpendByCategoryQueryClause{clause: i.Ident.LessThan(v)}
}

func (i SpendByCategoryQueryIdent[T]) LessThanEq(v T) SpendByCategoryQueryClause {
	return SpendByCategoryQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i SpendByCategoryQueryIdent[T]) IsNull() SpendByCategoryQueryClause {
	return SpendByCategoryQueryClause{clause: i.Ident.IsNull()}
}

func (i SpendByCategoryQueryIdent[T]) IsNotNull() SpendByCategoryQueryClause {
	return SpendByCategoryQueryClause{clause: i.Ident.IsNotNull()}
}

type SpendByCategorySortBuilder struct {
	*spendByCategorySort
}

func NewSpendByCategorySort() *SpendByCategorySortBuilder {
	return &SpendByCategorySortBuilder{spendByCategorySort: &spendByCategorySort{}}
}

type spendByCategorySort struct {
	sortFields []resource.SortField
}

func (c *spendByCategorySort) addField(field string) *SpendByCategorySort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &SpendByCategorySort{spendByCategorySort: c}
}

func (c *spendByCategorySort) Category() *SpendByCategorySort {
	return c.addField("Category")
}

func (c *spendByCategorySort) LineCount() *SpendByCategorySort {
	return c.addField("LineCount")
}

func (c *spendByCategorySort) TotalQuantity() *SpendByCategorySort {
	return c.addField("TotalQuantity")
}

func (c *spendByCategorySort) TotalSpend() *SpendByCategorySort {
	return c.addField("TotalSpend")
}

type SpendByCategorySort struct {
	*spendByCategorySort
}

func (s *SpendByCategorySort) Asc() *SpendByCategorySort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *SpendByCategorySort) Desc() *SpendByCategorySort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}
