// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"

	"github.com/cccteam/ccc/impulse/internal/skeleton/_candidates/outlets/pkg/router"
	"github.com/cccteam/ccc/resource"
)

// Features serves the names of the enabled feature flags, {"enabled": [...]}, to
// anyone signed in: what the browser reads at start and again after a flip. The
// generated router registers it at GET /console/api/features and, for each
// additional outlet, under that outlet's prefix.
func (a *App) Features() http.HandlerFunc {
	return resource.FeaturesHandler(a.FeatureSet())
}

// FeatureFlags serves the FeatureFlags resource's list, every declared flag with its
// description, state and last change, ordered by name, to a caller holding List on
// FeatureFlags in the global scope. The generated router registers it at
// GET /console/api/feature-flags and, for each additional session-serving outlet,
// under that outlet's prefix.
func (a *App) FeatureFlags() http.HandlerFunc {
	return resource.FeatureFlagsHandler(a, router.Collection())
}

// FeatureFlag serves one flag by name to a caller holding Read on FeatureFlags in the
// global scope. The generated router registers it at
// GET /console/api/feature-flags/{featureFlagName} and, for each additional
// session-serving outlet, under that outlet's prefix.
func (a *App) FeatureFlag() http.HandlerFunc {
	return resource.FeatureFlagHandler(a, router.Collection())
}

// SetFeature flips a flag for a caller holding Execute on SetFeature in the global
// scope: the row and its change record are written in one transaction, the other
// instances are signaled through the live service (the features kind of the signals
// document), this instance's FeatureSet is reloaded, and the flag is answered as
// written. A flag the
// package does not declare is 404. The generated router registers it at
// POST /console/api/set-feature and, for each additional session-serving outlet,
// under that outlet's prefix.
func (a *App) SetFeature() http.HandlerFunc {
	return resource.SetFeatureHandler(a, router.Collection(), a.LiveService())
}
