// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"
	"slices"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/impulse/internal/skeleton/_candidates/outlets/pkg/resources"
	"github.com/cccteam/ccc/impulse/internal/skeleton/_candidates/outlets/pkg/router"
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
)

func (a *App) Readings() http.HandlerFunc {
	type reading struct {
		ID         ccc.UUID  `json:"id"         index:"true" perm:"-"`
		TenantID   string    `json:"tenantId"   index:"true"`
		Source     string    `json:"source"`
		Value      float64   `json:"value"`
		RecordedAt time.Time `json:"recordedAt"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[resources.Reading, reading](a, accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewReadingQueryFromQuerySet(querySet)

		// The page: a count first when asked, then the rows, one past the page size
		// so the Link header knows whether a next page exists.
		page := querySet.Page()
		if err := page.Count(ctx, a.ResourceClient()); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			if !page.Add(row) {
				break
			}
			rec := (*reading)(&row.Data)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "ID":
					if !row.Masked("id") {
						rmap["id"] = rec.ID
					}
				case "TenantID":
					if !row.Masked("tenantId") {
						rmap["tenantId"] = rec.TenantID
					}
				case "Source":
					if !row.Masked("source") {
						rmap["source"] = rec.Source
					}
				case "Value":
					if !row.Masked("value") {
						rmap["value"] = rec.Value
					}
				case "RecordedAt":
					if !row.Masked("recordedAt") {
						rmap["recordedAt"] = rec.RecordedAt
					}
				}
			}
			if capabilities := row.Capabilities(); capabilities != nil {
				rmap[resource.CapabilitiesProperty] = capabilities
			}
			resp = append(resp, rmap)
		}
		if page.Reversed() {
			slices.Reverse(resp)
		}
		if err := page.WriteHeaders(w, r); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}

func (a *App) Reading() http.HandlerFunc {
	type response struct {
		ID         ccc.UUID  `json:"id"         index:"true" perm:"-"`
		TenantID   string    `json:"tenantId"`
		Source     string    `json:"source"`
		Value      float64   `json:"value"`
		RecordedAt time.Time `json:"recordedAt"`
	}

	decoder := NewQueryDecoder[resources.Reading, response](a, accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		id := httpio.Param[ccc.UUID](r, router.ReadingID)

		domain := httpio.Param[accesstypes.Domain](r, router.Domain)
		querySet, err := decoder.Decode(r, a.UserPermissions(r), accesstypes.DomainScope(domain))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewReadingQueryFromQuerySet(querySet).SetID(id)

		row, err := res.Read(ctx, a.ResourceClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		rec := (*response)(&row.Data)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "ID":
				if !row.Masked("id") {
					rmap["id"] = rec.ID
				}
			case "TenantID":
				if !row.Masked("tenantId") {
					rmap["tenantId"] = rec.TenantID
				}
			case "Source":
				if !row.Masked("source") {
					rmap["source"] = rec.Source
				}
			case "Value":
				if !row.Masked("value") {
					rmap["value"] = rec.Value
				}
			case "RecordedAt":
				if !row.Masked("recordedAt") {
					rmap["recordedAt"] = rec.RecordedAt
				}
			}
		}
		if capabilities := row.Capabilities(); capabilities != nil {
			rmap[resource.CapabilitiesProperty] = capabilities
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}
