// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/impulse/internal/skeleton/_candidates/outlets/pkg/router"
	"github.com/cccteam/ccc/resource"
)

// NewQueryDecoder builds a query decoder for a generated resource and request pair,
// wired to the generated collection so conditional grants render into the query.
// The Resourcer union keeps construction inside the generated universe: a decoder
// over any other struct is a compile error.
func NewQueryDecoder[Resource Resourcer, Request any](permissions ...accesstypes.Permission) *resource.QueryDecoder[Resource, Request] {
	return resource.MustNewQueryDecoder[Resource, Request](router.Collection(), permissions...)
}

// NewDecoder builds a patch decoder for a generated resource and request pair,
// wired to the generated collection so conditional grants render into the
// mutations' live check. The Resourcer union keeps construction inside the
// generated universe: a decoder over any other struct is a compile error.
func NewDecoder[Resource Resourcer, Request any](a *App, permissions ...accesstypes.Permission) *resource.Decoder[Resource, Request] {
	return resource.MustNewDecoder[Resource, Request](a, router.Collection(), permissions...)
}
