// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"github.com/cccteam/ccc/impulse/internal/skeleton/_candidates/outlets/pkg/resources"
	"github.com/cccteam/ccc/resource"
)

type Resourcer interface {
	resource.Resourcer
	resources.Announcement | resources.Reading | resources.Tenant
}
