DELETE FROM FailReasons WHERE TRUE;
DELETE FROM Certifications WHERE TRUE;
DELETE FROM ShipRoles WHERE TRUE;
DELETE FROM MissionKinds WHERE TRUE;
DELETE FROM RefitStatuses WHERE TRUE;
DELETE FROM MissionStatuses WHERE TRUE;
