CREATE TABLE Missions (
  Id STRING(36) NOT NULL,
  SectorId STRING(64) NOT NULL,
  ClientId STRING(36) NOT NULL,
  KindId STRING(64) NOT NULL,
  Title STRING(MAX) NOT NULL,
  Brief STRING(MAX),
  Hazard INT64 NOT NULL,
  Fee NUMERIC NOT NULL,
  Deadline TIMESTAMP NOT NULL,
  RequiredCertId STRING(64),
  BookedBy STRING(320) NOT NULL,
  AssignedSquadronId STRING(36),
  StatusId STRING(64) NOT NULL,
  Notes STRING(MAX),
  Settlement NUMERIC,

  CONSTRAINT CK_Missions_Id CHECK (REGEXP_CONTAINS(Id, r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')),
  CONSTRAINT FK_Missions_SectorId FOREIGN KEY (SectorId) REFERENCES Sectors(Id),
  CONSTRAINT FK_Missions_ClientId FOREIGN KEY (ClientId) REFERENCES Clients(Id),
  CONSTRAINT FK_Missions_KindId FOREIGN KEY (KindId) REFERENCES MissionKinds(Id),
  CONSTRAINT FK_Missions_RequiredCertId FOREIGN KEY (RequiredCertId) REFERENCES Certifications(Id),
  CONSTRAINT FK_Missions_AssignedSquadronId FOREIGN KEY (AssignedSquadronId) REFERENCES Squadrons(Id),
  CONSTRAINT FK_Missions_StatusId FOREIGN KEY (StatusId) REFERENCES MissionStatuses(Id),
) PRIMARY KEY (Id);
