CREATE TABLE RefitTasks (
  Id STRING(36) NOT NULL,
  TaskNumber INT64 NOT NULL,
  Instructions STRING(MAX) NOT NULL,
  Done BOOL NOT NULL,
  Notes STRING(MAX),

  CONSTRAINT FK_RefitTasks_Id FOREIGN KEY (Id) REFERENCES Refits(Id),
) PRIMARY KEY (Id, TaskNumber),
  INTERLEAVE IN PARENT Refits ON DELETE CASCADE;
