// Code generated by resourcegeneration. DO NOT EDIT.
import { Resource, ResourceMap, ResourceMeta } from '@cccteam/resource';
import { PermissionScope, PermissionScopes, Resources } from './zz_gen_constants';

export interface Announcements {
  id: string;
  tenantId?: string;
  kindId?: string;
  title?: string;
  body?: string;
}

export interface Tenants {
  id: string;
  name?: string;
}

const resourceMap: ResourceMap = {
  [Resources.Announcements]: {
    route: 'tenants/{tenantID}/announcements',
    consolidatedRoute: 'resources',
    fields: [
      { fieldName: 'id', primaryKey: { ordinalPosition: 0 }, displayType: 'uuid', required: false, isIndex: true, filterable: 'always' },
      { fieldName: 'tenantId', displayType: 'enumerated', required: true, isIndex: true, filterable: 'always', enumeratedResource: Resources.Tenants, readOnly: true },
      { fieldName: 'kindId', displayType: 'string', required: true, isIndex: true, filterable: 'always', maxLength: 64 },
      { fieldName: 'title', displayType: 'string', required: true, isIndex: true, filterable: 'always' },
      { fieldName: 'body', displayType: 'string', required: true, isIndex: false },
    ],
  },
  [Resources.Tenants]: {
    route: 'tenants',
    consolidatedRoute: 'resources',
    fields: [
      { fieldName: 'id', primaryKey: { ordinalPosition: 0 }, displayType: 'string', required: true, isIndex: true, filterable: 'always' },
      { fieldName: 'name', displayType: 'string', required: true, isIndex: true, filterable: 'always' },
    ],
  },
};

export function resourceMeta(resource: Resource): ResourceMeta {
  if (resourceMap[resource] !== undefined) {
    return resourceMap[resource];
  } else {
    console.error('Resource not found in resourceMap:', resource);
    return {} as ResourceMeta;
  }
}

export const DomainRouteParam = 'tenantID';

export const ResourceScopes: Record<Resource, PermissionScope> = {
  [Resources.Announcements]: PermissionScopes.domain,
  [Resources.Tenants]: PermissionScopes.global,
};
