// Code generated by resourcegeneration. DO NOT EDIT.
import { FieldName, Method, Permission, Resource } from '@cccteam/resource';

export const Permissions = {
  Create: 'Create' as Permission,
  Delete: 'Delete' as Permission,
  Execute: 'Execute' as Permission,
  List: 'List' as Permission,
  Read: 'Read' as Permission,
  Update: 'Update' as Permission,
};

export type PermissionScope = 'global' | 'domain';

export const PermissionScopes = {
  domain: 'domain' as PermissionScope,
  global: 'global' as PermissionScope,
};

export const Resources = {
  Announcements: 'Announcements' as Resource,
  FeatureFlags: 'FeatureFlags' as Resource,
  Tenants: 'Tenants' as Resource,
};

export const Methods = {
  SetFeature: 'SetFeature' as Method,
};

export namespace Announcements {
  export const fieldName = {
    body: 'body' as FieldName,
    id: 'id' as FieldName,
    kindId: 'kindId' as FieldName,
    tenantId: 'tenantId' as FieldName,
    title: 'title' as FieldName,
  };
  export const resourceName = {
    body: 'Announcements.body' as Resource,
    id: 'Announcements.id' as Resource,
    kindId: 'Announcements.kindId' as Resource,
    tenantId: 'Announcements.tenantId' as Resource,
    title: 'Announcements.title' as Resource,
  };
}

export namespace FeatureFlags {
  export const fieldName = {
    description: 'description' as FieldName,
    enabled: 'enabled' as FieldName,
    name: 'name' as FieldName,
    updatedAt: 'updatedAt' as FieldName,
    updatedBy: 'updatedBy' as FieldName,
  };
  export const resourceName = {
    description: 'FeatureFlags.description' as Resource,
    enabled: 'FeatureFlags.enabled' as Resource,
    name: 'FeatureFlags.name' as Resource,
    updatedAt: 'FeatureFlags.updatedAt' as Resource,
    updatedBy: 'FeatureFlags.updatedBy' as Resource,
  };
}

export namespace Tenants {
  export const fieldName = {
    id: 'id' as FieldName,
    name: 'name' as FieldName,
  };
  export const resourceName = {
    id: 'Tenants.id' as Resource,
    name: 'Tenants.name' as Resource,
  };
}

