// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package app

import (
	"net/http"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource/starport/pkg/resources"
	"github.com/cccteam/ccc/resource/starport/pkg/router"
	"github.com/cccteam/ccc/tracer"
	"github.com/cccteam/httpio"
)

func (a *App) CrewMembers() http.HandlerFunc {
	type crewMember struct {
		ID             ccc.UUID `json:"id"             index:"true"`
		ShipID         ccc.UUID `json:"shipId"         index:"true" perm:"List"`
		Name           string   `json:"name"           perm:"List"`
		Rank           string   `json:"rank"           perm:"List"`
		ClearanceLevel int64    `json:"clearanceLevel" perm:"List"`
		MedicalNotes   *string  `json:"medicalNotes"   perm:"List"  pii:"true"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[resources.CrewMember, crewMember](a, accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		querySet, err := decoder.Decode(r, a.UserPermissions(r))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewCrewMemberQueryFromQuerySet(querySet)

		resp := response{}
		for row, err := range res.List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*crewMember)(row)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "ID":
					rmap["id"] = rec.ID
				case "ShipID":
					rmap["shipId"] = rec.ShipID
				case "Name":
					rmap["name"] = rec.Name
				case "Rank":
					rmap["rank"] = rec.Rank
				case "ClearanceLevel":
					rmap["clearanceLevel"] = rec.ClearanceLevel
				case "MedicalNotes":
					rmap["medicalNotes"] = rec.MedicalNotes
				}
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}

func (a *App) CrewMember() http.HandlerFunc {
	type response struct {
		ID             ccc.UUID `json:"id"             index:"true"`
		ShipID         ccc.UUID `json:"shipId"         perm:"Read"`
		Name           string   `json:"name"           perm:"Read"`
		Rank           string   `json:"rank"           perm:"Read"`
		ClearanceLevel int64    `json:"clearanceLevel" perm:"Read"`
		MedicalNotes   *string  `json:"medicalNotes"   perm:"Read"  pii:"true"`
	}

	decoder := NewQueryDecoder[resources.CrewMember, response](a, accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := tracer.Start(r.Context())
		defer span.End()

		id := httpio.Param[ccc.UUID](r, router.CrewMemberID)

		querySet, err := decoder.Decode(r, a.UserPermissions(r))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewCrewMemberQueryFromQuerySet(querySet).SetID(id)

		row, err := res.Read(ctx, a.ResourceClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		rec := (*response)(row)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "ID":
				rmap["id"] = rec.ID
			case "ShipID":
				rmap["shipId"] = rec.ShipID
			case "Name":
				rmap["name"] = rec.Name
			case "Rank":
				rmap["rank"] = rec.Rank
			case "ClearanceLevel":
				rmap["clearanceLevel"] = rec.ClearanceLevel
			case "MedicalNotes":
				rmap["medicalNotes"] = rec.MedicalNotes
			}
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}
