// Code generated by resourcegeneration. DO NOT EDIT.
import { Resource, ResourceMap, ResourceMeta } from '@cccteam/ccc-lib/types';
import { PermissionScope, PermissionScopes, Resources } from './zz_gen_constants';

export interface Berths {
  id: string;
  designation: string;
  sizeClass: number;
  occupied: boolean;
}

export interface CargoManifests {
  shipId: string;
  lineNumber: number;
  details: string;
  quantity: number;
  declaredValue: number;
}

export interface CrewMembers {
  id: string;
  shipId: string;
  name: string;
  rank: string;
  clearanceLevel: number;
  medicalNotes: string;
}

export interface DockingBays {
  id: string;
  name: string;
  deckLevel: number;
  maxTonnage: number;
}

export interface Ships {
  id: string;
  registryCode: string;
  name: string;
  dockingBayId: string;
  cargoValue: number;
  updatedAt: Date;
}

export interface SupplyCrates {
  id: string;
  label: string;
  quantity: number;
  priority: number;
  status: string;
  barcode: string;
  notes: string;
  inspectorBadge: string;
  assignedShipId: string;
}

const resourceMap: ResourceMap = {
  [Resources.Berths]: {
    route: 'stations/{stationID}/berths',
    fields: [
      { fieldName: 'id', primaryKey: { ordinalPosition: 0 }, displayType: 'uuid', required: false, isIndex: true },
      { fieldName: 'designation', displayType: 'string', required: true, isIndex: true },
      { fieldName: 'sizeClass', displayType: 'number', required: true, isIndex: false },
      { fieldName: 'occupied', displayType: 'boolean', required: true, isIndex: false },
    ],
  },
  [Resources.CargoManifests]: {
    route: 'cargo-manifests',
    consolidatedRoute: 'resources',
    fields: [
      { fieldName: 'shipId', primaryKey: { ordinalPosition: 0 }, displayType: 'enumerated', required: true, isIndex: true, enumeratedResource: Resources.Ships },
      { fieldName: 'lineNumber', primaryKey: { ordinalPosition: 1 }, displayType: 'number', required: true, isIndex: true },
      { fieldName: 'details', displayType: 'string', required: true, isIndex: false },
      { fieldName: 'quantity', displayType: 'number', required: true, isIndex: false },
      { fieldName: 'declaredValue', displayType: 'number', required: true, isIndex: false },
    ],
  },
  [Resources.CrewMembers]: {
    route: 'crew-members',
    fields: [
      { fieldName: 'id', primaryKey: { ordinalPosition: 0 }, displayType: 'uuid', required: false, isIndex: true },
      { fieldName: 'shipId', displayType: 'enumerated', required: true, isIndex: true, enumeratedResource: Resources.Ships },
      { fieldName: 'name', displayType: 'string', required: true, isIndex: false },
      { fieldName: 'rank', displayType: 'string', required: true, isIndex: false },
      { fieldName: 'clearanceLevel', displayType: 'number', required: true, isIndex: false },
      { fieldName: 'medicalNotes', displayType: 'string', required: false, isIndex: false },
    ],
  },
  [Resources.DockingBays]: {
    route: 'docking-bays',
    consolidatedRoute: 'resources',
    fields: [
      { fieldName: 'id', primaryKey: { ordinalPosition: 0 }, displayType: 'uuid', required: false, isIndex: true },
      { fieldName: 'name', displayType: 'string', required: true, isIndex: true },
      { fieldName: 'deckLevel', displayType: 'number', required: true, isIndex: false },
      { fieldName: 'maxTonnage', displayType: 'number', required: true, isIndex: false },
    ],
  },
  [Resources.Ships]: {
    route: 'ships',
    consolidatedRoute: 'resources',
    fields: [
      { fieldName: 'id', primaryKey: { ordinalPosition: 0 }, displayType: 'uuid', required: false, isIndex: true },
      { fieldName: 'registryCode', displayType: 'string', required: true, isIndex: true },
      { fieldName: 'name', displayType: 'string', required: true, isIndex: true },
      { fieldName: 'dockingBayId', displayType: 'enumerated', required: false, isIndex: true, enumeratedResource: Resources.DockingBays },
      { fieldName: 'cargoValue', displayType: 'number', required: true, isIndex: false },
      { fieldName: 'updatedAt', displayType: 'date', required: false, isIndex: false },
    ],
  },
  [Resources.SupplyCrates]: {
    route: 'supply-crates',
    consolidatedRoute: 'resources',
    fields: [
      { fieldName: 'id', primaryKey: { ordinalPosition: 0 }, displayType: 'uuid', required: false, isIndex: true },
      { fieldName: 'label', displayType: 'string', required: true, isIndex: true },
      { fieldName: 'quantity', displayType: 'number', required: true, isIndex: false },
      { fieldName: 'priority', displayType: 'number', required: true, isIndex: false },
      { fieldName: 'status', displayType: 'string', required: false, isIndex: false },
      { fieldName: 'barcode', displayType: 'string', required: false, isIndex: false },
      { fieldName: 'notes', displayType: 'string', required: false, isIndex: false },
      { fieldName: 'inspectorBadge', displayType: 'string', required: false, isIndex: false },
      { fieldName: 'assignedShipId', displayType: 'enumerated', required: false, isIndex: true, enumeratedResource: Resources.Ships },
    ],
  },
};

export function resourceMeta(resource: Resource): ResourceMeta {
  if (resourceMap[resource] !== undefined) {
    return resourceMap[resource];
  } else {
    console.error('Resource not found in resourceMap:', resource);
    return {} as ResourceMeta;
  }
}

export const DomainRouteParam = 'stationID';

export const ResourceScopes: Record<Resource, PermissionScope> = {
  [Resources.Berths]: PermissionScopes.domain,
  [Resources.CargoManifests]: PermissionScopes.global,
  [Resources.CrewMembers]: PermissionScopes.global,
  [Resources.DockingBays]: PermissionScopes.global,
  [Resources.Ships]: PermissionScopes.global,
  [Resources.SupplyCrates]: PermissionScopes.global,
};
