package check

import (
	"context"
	"fmt"
	"os"
	"path"
	"strings"

	"github.com/go-playground/errors/v5"
)

// prettierIgnore verifies that each browser app's .prettierignore covers the generated
// TypeScript written into it. Prettier reflowing zz_gen files breaks generate idempotence.
type prettierIgnore struct{}

func (prettierIgnore) Name() string { return "prettier-ignore" }

func (prettierIgnore) Describe() string {
	return "each browser app's .prettierignore excludes the generated TypeScript"
}

// probeFiles are generated TypeScript names a matching ignore pattern must cover.
var probeFiles = []string{"zz_gen_api.ts", "zz_gen_resources.ts"}

func (c prettierIgnore) Run(_ context.Context, env *Env) Result {
	a := env.App
	var details []string
	checked := 0
	fixes := map[string][]string{} // .prettierignore path -> lines to add

	for _, g := range a.Generators {
		for _, t := range g.TypescriptTargets() {
			checked++
			w, ok := a.WebAppFor(t.Dir)
			if !ok {
				details = append(details, fmt.Sprintf("%s: TypeScript target %s is not inside a browser app (no angular.json above it)", t.Pos, t.Dir))

				continue
			}
			relTarget := strings.TrimPrefix(strings.TrimPrefix(t.Dir, w.Dir), "/")
			ignoreFile := path.Join(w.Dir, ".prettierignore")
			patterns, err := readIgnore(a.Abs(ignoreFile))
			if err != nil {
				return fail(c.Name(), err.Error())
			}
			covered := true
			for _, probe := range probeFiles {
				if !ignored(patterns, path.Join(relTarget, probe)) {
					covered = false
				}
			}
			if covered {
				continue
			}
			line := path.Join(relTarget, "zz_gen_*.ts")
			details = append(details, fmt.Sprintf("%s does not cover %s (add: %s)", ignoreFile, path.Join(relTarget, "zz_gen_*.ts"), line))
			fixes[ignoreFile] = append(fixes[ignoreFile], line)
		}
	}

	if checked == 0 {
		return skip(c.Name(), "no GenerateTypescript targets")
	}
	if len(details) == 0 {
		return pass(c.Name(), fmt.Sprintf("%d TypeScript target(s) excluded from prettier", checked))
	}
	if env.Fix && len(fixes) > 0 {
		for file, lines := range fixes {
			if err := appendLines(a.Abs(file), "# Generated by the resource generator; reformatting it breaks generate idempotence.", lines); err != nil {
				return fail(c.Name(), err.Error())
			}
			details = append(details, "fixed: "+file)
		}

		return passWithDetails(c.Name(), fmt.Sprintf("%d .prettierignore file(s) updated", len(fixes)), details...)
	}

	return fail(c.Name(), fmt.Sprintf("%d TypeScript target(s) not excluded from prettier (--fix adds the entries)", len(details)), details...)
}

// pass with details, for the --fix outcome.
func passWithDetails(name, summary string, details ...string) Result {
	return Result{Name: name, Status: Pass, Summary: summary, Details: details}
}

// readIgnore returns the patterns of a .prettierignore file, or nil when it is absent.
func readIgnore(abs string) ([]string, error) {
	data, err := os.ReadFile(abs)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}

		return nil, errors.Wrap(err, "os.ReadFile()")
	}

	var patterns []string
	for line := range strings.Lines(string(data)) {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		patterns = append(patterns, line)
	}

	return patterns, nil
}

// appendLines appends a comment and lines to the file, creating it when absent.
func appendLines(abs, comment string, lines []string) error {
	f, err := os.OpenFile(abs, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return errors.Wrap(err, "os.OpenFile()")
	}
	defer f.Close()

	existing, err := os.ReadFile(abs)
	if err != nil {
		return errors.Wrap(err, "os.ReadFile()")
	}
	var b strings.Builder
	if len(existing) > 0 && !strings.HasSuffix(string(existing), "\n") {
		b.WriteString("\n")
	}
	if comment != "" {
		b.WriteString(comment + "\n")
	}
	for _, l := range lines {
		b.WriteString(l + "\n")
	}
	if _, err := f.WriteString(b.String()); err != nil {
		return errors.Wrap(err, "os.File.WriteString()")
	}

	return nil
}

// ignored reports whether a gitignore-style pattern list ignores the slash-separated
// path (relative to the ignore file's directory). Later patterns win; "!" negates.
func ignored(patterns []string, rel string) bool {
	result := false
	for _, p := range patterns {
		negate := strings.HasPrefix(p, "!")
		if negate {
			p = p[1:]
		}
		if matchIgnore(p, rel) {
			result = !negate
		}
	}

	return result
}

// matchIgnore matches one gitignore-style pattern against a relative path. A pattern that
// matches a directory matches everything beneath it.
func matchIgnore(pattern, rel string) bool {
	dirOnly := strings.HasSuffix(pattern, "/")
	pattern = strings.Trim(pattern, "/")
	if pattern == "" {
		return false
	}
	pathSegs := strings.Split(rel, "/")
	patSegs := strings.Split(pattern, "/")

	if len(patSegs) == 1 {
		// No slash: the pattern matches a name at any depth.
		limit := len(pathSegs)
		if dirOnly {
			limit-- // the final segment is a file, which a directory pattern cannot match
		}
		for _, seg := range pathSegs[:limit] {
			if ok, _ := path.Match(patSegs[0], seg); ok {
				return true
			}
		}

		return false
	}

	return matchSegs(patSegs, pathSegs, dirOnly)
}

// matchSegs matches pattern segments against path segments from the root. Consuming all
// pattern segments while path segments remain means the pattern named a directory.
func matchSegs(pat, segs []string, dirOnly bool) bool {
	if len(pat) == 0 {
		return len(segs) > 0 || !dirOnly
	}
	if pat[0] == "**" {
		for i := 0; i <= len(segs); i++ {
			if matchSegs(pat[1:], segs[i:], dirOnly) {
				return true
			}
		}

		return false
	}
	if len(segs) == 0 {
		return false
	}
	if ok, _ := path.Match(pat[0], segs[0]); !ok {
		return false
	}

	return matchSegs(pat[1:], segs[1:], dirOnly)
}
