// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package resources

import "github.com/cccteam/ccc/resource"

// Features lists the feature flags this package declares, one per resource.Feature
// constant, in constant order: the flag's name is the constant's value and its
// description the constant's doc comment. The deploy step migrates the FeatureFlags
// table to this list (resource.MigrateFeatures). Nil when the package declares none.
func Features() []resource.FeatureDeclaration {
	return []resource.FeatureDeclaration{
		{Name: Commendations, Description: "Commendations lets headquarters cite a pilot for a sortie flown well: the commendations desk lists and files the citations, and every crew member's card counts their own.", Constant: "Commendations"},
	}
}

// FeatureGates maps every resource, field ("Resource.field") and method gated behind a
// feature flag (@feature) to its flag: what the permission digest filters by, so a
// gated-off target is absent from the digest exactly as a denied one is. Nil when
// nothing is gated.
func FeatureGates() resource.FeatureGates {
	return resource.FeatureGates{
		"Commendations":            Commendations,
		"PilotCards.commendations": Commendations,
	}
}
