// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package resources

import (
	"context"
	"iter"

	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/google/go-cmp/cmp"
)

func (PilotCertification) Resource() accesstypes.Resource {
	return "PilotCertifications"
}

func (PilotCertification) DefaultConfig() resource.Config {
	return defaultConfig()
}

type PilotCertificationQuery struct {
	qSet *resource.QuerySet[PilotCertification]
}

func NewPilotCertificationQuery() *PilotCertificationQuery {
	return &PilotCertificationQuery{qSet: resource.NewQuerySet(resource.NewMetadata[PilotCertification]())}
}

func NewPilotCertificationQueryFromQuerySet(qSet *resource.QuerySet[PilotCertification]) *PilotCertificationQuery {
	return &PilotCertificationQuery{qSet: qSet}
}

func (q *PilotCertificationQuery) SetUserID(v string) *PilotCertificationQuery {
	q.qSet.SetKey("UserID", v)

	return q
}

func (q *PilotCertificationQuery) UserID() string {
	v, _ := q.qSet.Key("UserID").(string)

	return v
}

func (q *PilotCertificationQuery) SetCertificationID(v string) *PilotCertificationQuery {
	q.qSet.SetKey("CertificationID", v)

	return q
}

func (q *PilotCertificationQuery) CertificationID() string {
	v, _ := q.qSet.Key("CertificationID").(string)

	return v
}

func (q *PilotCertificationQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[PilotCertification], error) {
	return q.qSet.Read(ctx, txn)
}

func (q *PilotCertificationQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[PilotCertification], error] {
	return q.qSet.List(ctx, txn)
}

func (q *PilotCertificationQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[PilotCertification], error]] {
	return q.qSet.BatchList(ctx, client, size)
}

func (q *PilotCertificationQuery) AddColumns(c *PilotCertificationColumns) *PilotCertificationQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *PilotCertificationQuery) Where(c PilotCertificationQueryClause) *PilotCertificationQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *PilotCertificationQuery) Sort(sort *PilotCertificationSort) *PilotCertificationQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *PilotCertificationQuery) Limit(n uint64) *PilotCertificationQuery {
	q.qSet.SetLimit(&n)

	return q
}

func (q *PilotCertificationQuery) Offset(n uint64) *PilotCertificationQuery {
	q.qSet.SetOffset(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *PilotCertificationQuery) Diff(got *PilotCertificationQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type PilotCertificationColumns struct {
	fields []accesstypes.Field
}

func NewPilotCertificationColumns() *PilotCertificationColumns {
	return &PilotCertificationColumns{}
}

func (c *PilotCertificationColumns) All() *PilotCertificationColumns {
	c.fields = []accesstypes.Field{
		"UserID",
		"CertificationID",
	}

	return c
}

func (c *PilotCertificationColumns) UserID() *PilotCertificationColumns {
	c.fields = append(c.fields, "UserID")

	return c
}

func (c *PilotCertificationColumns) CertificationID() *PilotCertificationColumns {
	c.fields = append(c.fields, "CertificationID")

	return c
}

type PilotCertificationQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewPilotCertificationQueryClause() PilotCertificationQueryPartialClause {
	return PilotCertificationQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p PilotCertificationQueryPartialClause) Group(qc PilotCertificationQueryClause) PilotCertificationQueryClause {
	return PilotCertificationQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p PilotCertificationQueryPartialClause) UserID() PilotCertificationQueryIdent[string] {
	return PilotCertificationQueryIdent[string]{Ident: resource.NewIdent[string]("UserID", p.partialClause, true)}
}

func (p PilotCertificationQueryPartialClause) CertificationID() PilotCertificationQueryIdent[string] {
	return PilotCertificationQueryIdent[string]{Ident: resource.NewIdent[string]("CertificationID", p.partialClause, true)}
}

type PilotCertificationQueryClause struct {
	clause resource.QueryClause
}

func (qc PilotCertificationQueryClause) And() PilotCertificationQueryPartialClause {
	return PilotCertificationQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc PilotCertificationQueryClause) Or() PilotCertificationQueryPartialClause {
	return PilotCertificationQueryPartialClause{partialClause: qc.clause.Or()}
}

type PilotCertificationQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i PilotCertificationQueryIdent[T]) Equal(v ...T) PilotCertificationQueryClause {
	return PilotCertificationQueryClause{clause: i.Ident.Equal(v...)}
}

func (i PilotCertificationQueryIdent[T]) NotEqual(v ...T) PilotCertificationQueryClause {
	return PilotCertificationQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i PilotCertificationQueryIdent[T]) GreaterThan(v T) PilotCertificationQueryClause {
	return PilotCertificationQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i PilotCertificationQueryIdent[T]) GreaterThanEq(v T) PilotCertificationQueryClause {
	return PilotCertificationQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i PilotCertificationQueryIdent[T]) LessThan(v T) PilotCertificationQueryClause {
	return PilotCertificationQueryClause{clause: i.Ident.LessThan(v)}
}

func (i PilotCertificationQueryIdent[T]) LessThanEq(v T) PilotCertificationQueryClause {
	return PilotCertificationQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i PilotCertificationQueryIdent[T]) IsNull() PilotCertificationQueryClause {
	return PilotCertificationQueryClause{clause: i.Ident.IsNull()}
}

func (i PilotCertificationQueryIdent[T]) IsNotNull() PilotCertificationQueryClause {
	return PilotCertificationQueryClause{clause: i.Ident.IsNotNull()}
}

type PilotCertificationSortBuilder struct {
	*pilotCertificationSort
}

func NewPilotCertificationSort() *PilotCertificationSortBuilder {
	return &PilotCertificationSortBuilder{pilotCertificationSort: &pilotCertificationSort{}}
}

type pilotCertificationSort struct {
	sortFields []resource.SortField
}

func (c *pilotCertificationSort) addField(field string) *PilotCertificationSort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &PilotCertificationSort{pilotCertificationSort: c}
}

func (c *pilotCertificationSort) UserID() *PilotCertificationSort {
	return c.addField("UserID")
}

func (c *pilotCertificationSort) CertificationID() *PilotCertificationSort {
	return c.addField("CertificationID")
}

type PilotCertificationSort struct {
	*pilotCertificationSort
}

func (s *PilotCertificationSort) Asc() *PilotCertificationSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *PilotCertificationSort) Desc() *PilotCertificationSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}

type PilotCertificationCreatePatch struct {
	patchSet *resource.PatchSet[PilotCertification]
}

func NewPilotCertificationCreatePatchFromPatchSet(userID string, certificationID string, patchSet *resource.PatchSet[PilotCertification]) *PilotCertificationCreatePatch {
	patchSet.
		SetKey("UserID", userID).
		SetKey("CertificationID", certificationID).
		SetPatchType(resource.CreatePatchType)
	patch := &PilotCertificationCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func NewPilotCertificationCreatePatch(userID string, certificationID string) *PilotCertificationCreatePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[PilotCertification]()).
		SetKey("UserID", userID).
		SetKey("CertificationID", certificationID).
		SetPatchType(resource.CreatePatchType)
	patch := &PilotCertificationCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func (p *PilotCertificationCreatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *PilotCertificationCreatePatch) ToStruct() *PilotCertification {
	return p.patchSet.ToStruct()
}

func (p *PilotCertificationCreatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *PilotCertificationCreatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *PilotCertificationCreatePatch) registerDefaultFuncs() {
}

func (p *PilotCertificationCreatePatch) UserID() string {
	v, _ := p.patchSet.Key("UserID").(string)

	return v
}

func (p *PilotCertificationCreatePatch) CertificationID() string {
	v, _ := p.patchSet.Key("CertificationID").(string)

	return v
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *PilotCertificationCreatePatch) Diff(got *PilotCertificationCreatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type PilotCertificationUpdatePatch struct {
	patchSet *resource.PatchSet[PilotCertification]
}

func NewPilotCertificationUpdatePatchFromPatchSet(userID string, certificationID string, patchSet *resource.PatchSet[PilotCertification]) *PilotCertificationUpdatePatch {
	patchSet.
		SetKey("UserID", userID).
		SetKey("CertificationID", certificationID).
		SetPatchType(resource.UpdatePatchType)

	patch := &PilotCertificationUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func NewPilotCertificationUpdatePatch(userID string, certificationID string) *PilotCertificationUpdatePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[PilotCertification]()).
		SetKey("UserID", userID).
		SetKey("CertificationID", certificationID).
		SetPatchType(resource.UpdatePatchType)

	patch := &PilotCertificationUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func (p *PilotCertificationUpdatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *PilotCertificationUpdatePatch) ToStruct() *PilotCertification {
	return p.patchSet.ToStruct()
}

func (p *PilotCertificationUpdatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *PilotCertificationUpdatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *PilotCertificationUpdatePatch) registerDefaultFuncs() {
}

func (p *PilotCertificationUpdatePatch) UserID() string {
	v, _ := p.patchSet.Key("UserID").(string)

	return v
}

func (p *PilotCertificationUpdatePatch) CertificationID() string {
	v, _ := p.patchSet.Key("CertificationID").(string)

	return v
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *PilotCertificationUpdatePatch) Diff(got *PilotCertificationUpdatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type PilotCertificationDeletePatch struct {
	patchSet *resource.PatchSet[PilotCertification]
}

func NewPilotCertificationDeletePatchFromPatchSet(userID string, certificationID string, patchSet *resource.PatchSet[PilotCertification]) *PilotCertificationDeletePatch {
	patchSet.
		SetKey("UserID", userID).
		SetKey("CertificationID", certificationID).
		SetPatchType(resource.DeletePatchType)

	return &PilotCertificationDeletePatch{patchSet: patchSet}
}

func NewPilotCertificationDeletePatch(userID string, certificationID string) *PilotCertificationDeletePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[PilotCertification]()).
		SetKey("UserID", userID).
		SetKey("CertificationID", certificationID).
		SetPatchType(resource.DeletePatchType)

	return &PilotCertificationDeletePatch{patchSet: patchSet}
}

func (p *PilotCertificationDeletePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *PilotCertificationDeletePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *PilotCertificationDeletePatch) UserID() string {
	v, _ := p.patchSet.Key("UserID").(string)

	return v
}

func (p *PilotCertificationDeletePatch) CertificationID() string {
	v, _ := p.patchSet.Key("CertificationID").(string)

	return v
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *PilotCertificationDeletePatch) Diff(got *PilotCertificationDeletePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}
