// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package resources

import (
	"context"
	"iter"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/go-playground/errors/v5"
	"github.com/google/go-cmp/cmp"
)

func (Sortie) Resource() accesstypes.Resource {
	return "Sorties"
}

func (Sortie) DefaultConfig() resource.Config {
	return defaultConfig()
}

type SortieQuery struct {
	qSet *resource.QuerySet[Sortie]
}

func NewSortieQuery() *SortieQuery {
	return &SortieQuery{qSet: resource.NewQuerySet(resource.NewMetadata[Sortie]())}
}

func NewSortieQueryFromQuerySet(qSet *resource.QuerySet[Sortie]) *SortieQuery {
	return &SortieQuery{qSet: qSet}
}

func (q *SortieQuery) SetID(v ccc.UUID) *SortieQuery {
	q.qSet.SetKey("ID", v)

	return q
}

func (q *SortieQuery) ID() ccc.UUID {
	v, _ := q.qSet.Key("ID").(ccc.UUID)

	return v
}

func (q *SortieQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[Sortie], error) {
	return q.qSet.Read(ctx, txn)
}

func (q *SortieQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[Sortie], error] {
	return q.qSet.List(ctx, txn)
}

func (q *SortieQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[Sortie], error]] {
	return q.qSet.BatchList(ctx, client, size)
}

func (q *SortieQuery) AddColumns(c *SortieColumns) *SortieQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *SortieQuery) Where(c SortieQueryClause) *SortieQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *SortieQuery) Sort(sort *SortieSort) *SortieQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *SortieQuery) Limit(n uint64) *SortieQuery {
	q.qSet.SetLimit(&n)

	return q
}

func (q *SortieQuery) Offset(n uint64) *SortieQuery {
	q.qSet.SetOffset(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *SortieQuery) Diff(got *SortieQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type SortieColumns struct {
	fields []accesstypes.Field
}

func NewSortieColumns() *SortieColumns {
	return &SortieColumns{}
}

func (c *SortieColumns) All() *SortieColumns {
	c.fields = []accesstypes.Field{
		"ID",
		"MissionID",
		"ShipID",
		"PilotUserID",
		"LaunchedAt",
		"ReturnedAt",
		"Debrief",
	}

	return c
}

func (c *SortieColumns) ID() *SortieColumns {
	c.fields = append(c.fields, "ID")

	return c
}

func (c *SortieColumns) MissionID() *SortieColumns {
	c.fields = append(c.fields, "MissionID")

	return c
}

func (c *SortieColumns) ShipID() *SortieColumns {
	c.fields = append(c.fields, "ShipID")

	return c
}

func (c *SortieColumns) PilotUserID() *SortieColumns {
	c.fields = append(c.fields, "PilotUserID")

	return c
}

func (c *SortieColumns) LaunchedAt() *SortieColumns {
	c.fields = append(c.fields, "LaunchedAt")

	return c
}

func (c *SortieColumns) ReturnedAt() *SortieColumns {
	c.fields = append(c.fields, "ReturnedAt")

	return c
}

func (c *SortieColumns) Debrief() *SortieColumns {
	c.fields = append(c.fields, "Debrief")

	return c
}

type SortieQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewSortieQueryClause() SortieQueryPartialClause {
	return SortieQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p SortieQueryPartialClause) Group(qc SortieQueryClause) SortieQueryClause {
	return SortieQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p SortieQueryPartialClause) ID() SortieQueryIdent[ccc.UUID] {
	return SortieQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("ID", p.partialClause, true)}
}

func (p SortieQueryPartialClause) MissionID() SortieQueryIdent[ccc.UUID] {
	return SortieQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("MissionID", p.partialClause, true)}
}

func (p SortieQueryPartialClause) ShipID() SortieQueryIdent[ccc.UUID] {
	return SortieQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("ShipID", p.partialClause, true)}
}

type SortieQueryClause struct {
	clause resource.QueryClause
}

func (qc SortieQueryClause) And() SortieQueryPartialClause {
	return SortieQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc SortieQueryClause) Or() SortieQueryPartialClause {
	return SortieQueryPartialClause{partialClause: qc.clause.Or()}
}

type SortieQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i SortieQueryIdent[T]) Equal(v ...T) SortieQueryClause {
	return SortieQueryClause{clause: i.Ident.Equal(v...)}
}

func (i SortieQueryIdent[T]) NotEqual(v ...T) SortieQueryClause {
	return SortieQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i SortieQueryIdent[T]) GreaterThan(v T) SortieQueryClause {
	return SortieQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i SortieQueryIdent[T]) GreaterThanEq(v T) SortieQueryClause {
	return SortieQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i SortieQueryIdent[T]) LessThan(v T) SortieQueryClause {
	return SortieQueryClause{clause: i.Ident.LessThan(v)}
}

func (i SortieQueryIdent[T]) LessThanEq(v T) SortieQueryClause {
	return SortieQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i SortieQueryIdent[T]) IsNull() SortieQueryClause {
	return SortieQueryClause{clause: i.Ident.IsNull()}
}

func (i SortieQueryIdent[T]) IsNotNull() SortieQueryClause {
	return SortieQueryClause{clause: i.Ident.IsNotNull()}
}

type SortieSortBuilder struct {
	*sortieSort
}

func NewSortieSort() *SortieSortBuilder {
	return &SortieSortBuilder{sortieSort: &sortieSort{}}
}

type sortieSort struct {
	sortFields []resource.SortField
}

func (c *sortieSort) addField(field string) *SortieSort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &SortieSort{sortieSort: c}
}

func (c *sortieSort) ID() *SortieSort {
	return c.addField("ID")
}

func (c *sortieSort) MissionID() *SortieSort {
	return c.addField("MissionID")
}

func (c *sortieSort) ShipID() *SortieSort {
	return c.addField("ShipID")
}

func (c *sortieSort) PilotUserID() *SortieSort {
	return c.addField("PilotUserID")
}

func (c *sortieSort) LaunchedAt() *SortieSort {
	return c.addField("LaunchedAt")
}

func (c *sortieSort) ReturnedAt() *SortieSort {
	return c.addField("ReturnedAt")
}

func (c *sortieSort) Debrief() *SortieSort {
	return c.addField("Debrief")
}

type SortieSort struct {
	*sortieSort
}

func (s *SortieSort) Asc() *SortieSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *SortieSort) Desc() *SortieSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}

type SortieCreatePatch struct {
	patchSet *resource.PatchSet[Sortie]
}

func NewSortieCreatePatchFromPatchSet(patchSet *resource.PatchSet[Sortie]) (*SortieCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &SortieCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func NewSortieCreatePatch() (*SortieCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet := resource.NewPatchSet(resource.NewMetadata[Sortie]()).
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &SortieCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func (p *SortieCreatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *SortieCreatePatch) ToStruct() *Sortie {
	return p.patchSet.ToStruct()
}

func (p *SortieCreatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *SortieCreatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *SortieCreatePatch) registerDefaultFuncs() {
}

func (p *SortieCreatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *SortieCreatePatch) SetMissionID(v ccc.UUID) *SortieCreatePatch {
	p.patchSet.Set("MissionID", v)

	return p
}

func (p *SortieCreatePatch) MissionID() ccc.UUID {
	v, _ := p.patchSet.Get("MissionID").(ccc.UUID)

	return v
}

func (p *SortieCreatePatch) MissionIDIsSet() bool {
	return p.patchSet.IsSet("MissionID")
}

func (p *SortieCreatePatch) SetShipID(v ccc.UUID) *SortieCreatePatch {
	p.patchSet.Set("ShipID", v)

	return p
}

func (p *SortieCreatePatch) ShipID() ccc.UUID {
	v, _ := p.patchSet.Get("ShipID").(ccc.UUID)

	return v
}

func (p *SortieCreatePatch) ShipIDIsSet() bool {
	return p.patchSet.IsSet("ShipID")
}

func (p *SortieCreatePatch) SetPilotUserID(v string) *SortieCreatePatch {
	p.patchSet.Set("PilotUserID", v)

	return p
}

func (p *SortieCreatePatch) PilotUserID() string {
	v, _ := p.patchSet.Get("PilotUserID").(string)

	return v
}

func (p *SortieCreatePatch) PilotUserIDIsSet() bool {
	return p.patchSet.IsSet("PilotUserID")
}

func (p *SortieCreatePatch) SetLaunchedAt(v time.Time) *SortieCreatePatch {
	p.patchSet.Set("LaunchedAt", v)

	return p
}

func (p *SortieCreatePatch) LaunchedAt() time.Time {
	v, _ := p.patchSet.Get("LaunchedAt").(time.Time)

	return v
}

func (p *SortieCreatePatch) LaunchedAtIsSet() bool {
	return p.patchSet.IsSet("LaunchedAt")
}

func (p *SortieCreatePatch) SetReturnedAt(v *time.Time) *SortieCreatePatch {
	if v != nil {
		p.patchSet.Set("ReturnedAt", v)
	} else {
		p.patchSet.Set("ReturnedAt", nil)
	}

	return p
}

func (p *SortieCreatePatch) ReturnedAt() *time.Time {
	v, _ := p.patchSet.Get("ReturnedAt").(*time.Time)

	return v
}

func (p *SortieCreatePatch) ReturnedAtIsSet() bool {
	return p.patchSet.IsSet("ReturnedAt")
}

func (p *SortieCreatePatch) SetDebrief(v *string) *SortieCreatePatch {
	if v != nil {
		p.patchSet.Set("Debrief", v)
	} else {
		p.patchSet.Set("Debrief", nil)
	}

	return p
}

func (p *SortieCreatePatch) Debrief() *string {
	v, _ := p.patchSet.Get("Debrief").(*string)

	return v
}

func (p *SortieCreatePatch) DebriefIsSet() bool {
	return p.patchSet.IsSet("Debrief")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *SortieCreatePatch) Diff(got *SortieCreatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type SortieUpdatePatch struct {
	patchSet *resource.PatchSet[Sortie]
}

func NewSortieUpdatePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[Sortie]) *SortieUpdatePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &SortieUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func NewSortieUpdatePatch(id ccc.UUID) *SortieUpdatePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Sortie]()).
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &SortieUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func (p *SortieUpdatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *SortieUpdatePatch) ToStruct() *Sortie {
	return p.patchSet.ToStruct()
}

func (p *SortieUpdatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *SortieUpdatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *SortieUpdatePatch) registerDefaultFuncs() {
}

func (p *SortieUpdatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *SortieUpdatePatch) SetMissionID(v ccc.UUID) *SortieUpdatePatch {
	p.patchSet.Set("MissionID", v)

	return p
}

func (p *SortieUpdatePatch) MissionID() ccc.UUID {
	v, _ := p.patchSet.Get("MissionID").(ccc.UUID)

	return v
}

func (p *SortieUpdatePatch) MissionIDIsSet() bool {
	return p.patchSet.IsSet("MissionID")
}

func (p *SortieUpdatePatch) SetShipID(v ccc.UUID) *SortieUpdatePatch {
	p.patchSet.Set("ShipID", v)

	return p
}

func (p *SortieUpdatePatch) ShipID() ccc.UUID {
	v, _ := p.patchSet.Get("ShipID").(ccc.UUID)

	return v
}

func (p *SortieUpdatePatch) ShipIDIsSet() bool {
	return p.patchSet.IsSet("ShipID")
}

func (p *SortieUpdatePatch) SetPilotUserID(v string) *SortieUpdatePatch {
	p.patchSet.Set("PilotUserID", v)

	return p
}

func (p *SortieUpdatePatch) PilotUserID() string {
	v, _ := p.patchSet.Get("PilotUserID").(string)

	return v
}

func (p *SortieUpdatePatch) PilotUserIDIsSet() bool {
	return p.patchSet.IsSet("PilotUserID")
}

func (p *SortieUpdatePatch) SetLaunchedAt(v time.Time) *SortieUpdatePatch {
	p.patchSet.Set("LaunchedAt", v)

	return p
}

func (p *SortieUpdatePatch) LaunchedAt() time.Time {
	v, _ := p.patchSet.Get("LaunchedAt").(time.Time)

	return v
}

func (p *SortieUpdatePatch) LaunchedAtIsSet() bool {
	return p.patchSet.IsSet("LaunchedAt")
}

func (p *SortieUpdatePatch) SetReturnedAt(v *time.Time) *SortieUpdatePatch {
	if v != nil {
		p.patchSet.Set("ReturnedAt", v)
	} else {
		p.patchSet.Set("ReturnedAt", nil)
	}

	return p
}

func (p *SortieUpdatePatch) ReturnedAt() *time.Time {
	v, _ := p.patchSet.Get("ReturnedAt").(*time.Time)

	return v
}

func (p *SortieUpdatePatch) ReturnedAtIsSet() bool {
	return p.patchSet.IsSet("ReturnedAt")
}

func (p *SortieUpdatePatch) SetDebrief(v *string) *SortieUpdatePatch {
	if v != nil {
		p.patchSet.Set("Debrief", v)
	} else {
		p.patchSet.Set("Debrief", nil)
	}

	return p
}

func (p *SortieUpdatePatch) Debrief() *string {
	v, _ := p.patchSet.Get("Debrief").(*string)

	return v
}

func (p *SortieUpdatePatch) DebriefIsSet() bool {
	return p.patchSet.IsSet("Debrief")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *SortieUpdatePatch) Diff(got *SortieUpdatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type SortieDeletePatch struct {
	patchSet *resource.PatchSet[Sortie]
}

func NewSortieDeletePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[Sortie]) *SortieDeletePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &SortieDeletePatch{patchSet: patchSet}
}

func NewSortieDeletePatch(id ccc.UUID) *SortieDeletePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Sortie]()).
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &SortieDeletePatch{patchSet: patchSet}
}

func (p *SortieDeletePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *SortieDeletePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *SortieDeletePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *SortieDeletePatch) Diff(got *SortieDeletePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}
