// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package resources

import (
	"context"
	"iter"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/go-playground/errors/v5"
	"github.com/google/go-cmp/cmp"
)

func (DroidReport) Resource() accesstypes.Resource {
	return "DroidReports"
}

func (DroidReport) DefaultConfig() resource.Config {
	return defaultConfig()
}

type DroidReportQuery struct {
	qSet *resource.QuerySet[DroidReport]
}

func NewDroidReportQuery() *DroidReportQuery {
	return &DroidReportQuery{qSet: resource.NewQuerySet(resource.NewMetadata[DroidReport]())}
}

func NewDroidReportQueryFromQuerySet(qSet *resource.QuerySet[DroidReport]) *DroidReportQuery {
	return &DroidReportQuery{qSet: qSet}
}

func (q *DroidReportQuery) SetID(v ccc.UUID) *DroidReportQuery {
	q.qSet.SetKey("ID", v)

	return q
}

func (q *DroidReportQuery) ID() ccc.UUID {
	v, _ := q.qSet.Key("ID").(ccc.UUID)

	return v
}

func (q *DroidReportQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[DroidReport], error) {
	return q.qSet.Read(ctx, txn)
}

func (q *DroidReportQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[DroidReport], error] {
	return q.qSet.List(ctx, txn)
}

func (q *DroidReportQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[DroidReport], error]] {
	return q.qSet.BatchList(ctx, client, size)
}

func (q *DroidReportQuery) AddColumns(c *DroidReportColumns) *DroidReportQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *DroidReportQuery) Where(c DroidReportQueryClause) *DroidReportQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *DroidReportQuery) Sort(sort *DroidReportSort) *DroidReportQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *DroidReportQuery) Limit(n uint64) *DroidReportQuery {
	q.qSet.SetLimit(&n)

	return q
}

func (q *DroidReportQuery) Offset(n uint64) *DroidReportQuery {
	q.qSet.SetOffset(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *DroidReportQuery) Diff(got *DroidReportQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type DroidReportColumns struct {
	fields []accesstypes.Field
}

func NewDroidReportColumns() *DroidReportColumns {
	return &DroidReportColumns{}
}

func (c *DroidReportColumns) All() *DroidReportColumns {
	c.fields = []accesstypes.Field{
		"ID",
		"SectorID",
		"ShipID",
		"Subsystem",
		"Reading",
		"RecordedAt",
	}

	return c
}

func (c *DroidReportColumns) ID() *DroidReportColumns {
	c.fields = append(c.fields, "ID")

	return c
}

func (c *DroidReportColumns) SectorID() *DroidReportColumns {
	c.fields = append(c.fields, "SectorID")

	return c
}

func (c *DroidReportColumns) ShipID() *DroidReportColumns {
	c.fields = append(c.fields, "ShipID")

	return c
}

func (c *DroidReportColumns) Subsystem() *DroidReportColumns {
	c.fields = append(c.fields, "Subsystem")

	return c
}

func (c *DroidReportColumns) Reading() *DroidReportColumns {
	c.fields = append(c.fields, "Reading")

	return c
}

func (c *DroidReportColumns) RecordedAt() *DroidReportColumns {
	c.fields = append(c.fields, "RecordedAt")

	return c
}

type DroidReportQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewDroidReportQueryClause() DroidReportQueryPartialClause {
	return DroidReportQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p DroidReportQueryPartialClause) Group(qc DroidReportQueryClause) DroidReportQueryClause {
	return DroidReportQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p DroidReportQueryPartialClause) ID() DroidReportQueryIdent[ccc.UUID] {
	return DroidReportQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("ID", p.partialClause, true)}
}

func (p DroidReportQueryPartialClause) SectorID() DroidReportQueryIdent[string] {
	return DroidReportQueryIdent[string]{Ident: resource.NewIdent[string]("SectorID", p.partialClause, true)}
}

func (p DroidReportQueryPartialClause) ShipID() DroidReportQueryIdent[ccc.UUID] {
	return DroidReportQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("ShipID", p.partialClause, true)}
}

type DroidReportQueryClause struct {
	clause resource.QueryClause
}

func (qc DroidReportQueryClause) And() DroidReportQueryPartialClause {
	return DroidReportQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc DroidReportQueryClause) Or() DroidReportQueryPartialClause {
	return DroidReportQueryPartialClause{partialClause: qc.clause.Or()}
}

type DroidReportQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i DroidReportQueryIdent[T]) Equal(v ...T) DroidReportQueryClause {
	return DroidReportQueryClause{clause: i.Ident.Equal(v...)}
}

func (i DroidReportQueryIdent[T]) NotEqual(v ...T) DroidReportQueryClause {
	return DroidReportQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i DroidReportQueryIdent[T]) GreaterThan(v T) DroidReportQueryClause {
	return DroidReportQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i DroidReportQueryIdent[T]) GreaterThanEq(v T) DroidReportQueryClause {
	return DroidReportQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i DroidReportQueryIdent[T]) LessThan(v T) DroidReportQueryClause {
	return DroidReportQueryClause{clause: i.Ident.LessThan(v)}
}

func (i DroidReportQueryIdent[T]) LessThanEq(v T) DroidReportQueryClause {
	return DroidReportQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i DroidReportQueryIdent[T]) IsNull() DroidReportQueryClause {
	return DroidReportQueryClause{clause: i.Ident.IsNull()}
}

func (i DroidReportQueryIdent[T]) IsNotNull() DroidReportQueryClause {
	return DroidReportQueryClause{clause: i.Ident.IsNotNull()}
}

type DroidReportSortBuilder struct {
	*droidReportSort
}

func NewDroidReportSort() *DroidReportSortBuilder {
	return &DroidReportSortBuilder{droidReportSort: &droidReportSort{}}
}

type droidReportSort struct {
	sortFields []resource.SortField
}

func (c *droidReportSort) addField(field string) *DroidReportSort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &DroidReportSort{droidReportSort: c}
}

func (c *droidReportSort) ID() *DroidReportSort {
	return c.addField("ID")
}

func (c *droidReportSort) SectorID() *DroidReportSort {
	return c.addField("SectorID")
}

func (c *droidReportSort) ShipID() *DroidReportSort {
	return c.addField("ShipID")
}

func (c *droidReportSort) Subsystem() *DroidReportSort {
	return c.addField("Subsystem")
}

func (c *droidReportSort) Reading() *DroidReportSort {
	return c.addField("Reading")
}

func (c *droidReportSort) RecordedAt() *DroidReportSort {
	return c.addField("RecordedAt")
}

type DroidReportSort struct {
	*droidReportSort
}

func (s *DroidReportSort) Asc() *DroidReportSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *DroidReportSort) Desc() *DroidReportSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}

type DroidReportCreatePatch struct {
	patchSet *resource.PatchSet[DroidReport]
}

func NewDroidReportCreatePatchFromPatchSet(patchSet *resource.PatchSet[DroidReport]) (*DroidReportCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &DroidReportCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func NewDroidReportCreatePatch() (*DroidReportCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet := resource.NewPatchSet(resource.NewMetadata[DroidReport]()).
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &DroidReportCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func (p *DroidReportCreatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *DroidReportCreatePatch) ToStruct() *DroidReport {
	return p.patchSet.ToStruct()
}

func (p *DroidReportCreatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *DroidReportCreatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *DroidReportCreatePatch) registerDefaultFuncs() {
}

func (p *DroidReportCreatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *DroidReportCreatePatch) SetSectorID(v string) *DroidReportCreatePatch {
	p.patchSet.Set("SectorID", v)

	return p
}

func (p *DroidReportCreatePatch) SectorID() string {
	v, _ := p.patchSet.Get("SectorID").(string)

	return v
}

func (p *DroidReportCreatePatch) SectorIDIsSet() bool {
	return p.patchSet.IsSet("SectorID")
}

func (p *DroidReportCreatePatch) SetShipID(v ccc.UUID) *DroidReportCreatePatch {
	p.patchSet.Set("ShipID", v)

	return p
}

func (p *DroidReportCreatePatch) ShipID() ccc.UUID {
	v, _ := p.patchSet.Get("ShipID").(ccc.UUID)

	return v
}

func (p *DroidReportCreatePatch) ShipIDIsSet() bool {
	return p.patchSet.IsSet("ShipID")
}

func (p *DroidReportCreatePatch) SetSubsystem(v string) *DroidReportCreatePatch {
	p.patchSet.Set("Subsystem", v)

	return p
}

func (p *DroidReportCreatePatch) Subsystem() string {
	v, _ := p.patchSet.Get("Subsystem").(string)

	return v
}

func (p *DroidReportCreatePatch) SubsystemIsSet() bool {
	return p.patchSet.IsSet("Subsystem")
}

func (p *DroidReportCreatePatch) SetReading(v float64) *DroidReportCreatePatch {
	p.patchSet.Set("Reading", v)

	return p
}

func (p *DroidReportCreatePatch) Reading() float64 {
	v, _ := p.patchSet.Get("Reading").(float64)

	return v
}

func (p *DroidReportCreatePatch) ReadingIsSet() bool {
	return p.patchSet.IsSet("Reading")
}

func (p *DroidReportCreatePatch) SetRecordedAt(v time.Time) *DroidReportCreatePatch {
	p.patchSet.Set("RecordedAt", v)

	return p
}

func (p *DroidReportCreatePatch) RecordedAt() time.Time {
	v, _ := p.patchSet.Get("RecordedAt").(time.Time)

	return v
}

func (p *DroidReportCreatePatch) RecordedAtIsSet() bool {
	return p.patchSet.IsSet("RecordedAt")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *DroidReportCreatePatch) Diff(got *DroidReportCreatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type DroidReportUpdatePatch struct {
	patchSet *resource.PatchSet[DroidReport]
}

func NewDroidReportUpdatePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[DroidReport]) *DroidReportUpdatePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &DroidReportUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func NewDroidReportUpdatePatch(id ccc.UUID) *DroidReportUpdatePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[DroidReport]()).
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &DroidReportUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func (p *DroidReportUpdatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *DroidReportUpdatePatch) ToStruct() *DroidReport {
	return p.patchSet.ToStruct()
}

func (p *DroidReportUpdatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *DroidReportUpdatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *DroidReportUpdatePatch) registerDefaultFuncs() {
}

func (p *DroidReportUpdatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *DroidReportUpdatePatch) SetSectorID(v string) *DroidReportUpdatePatch {
	p.patchSet.Set("SectorID", v)

	return p
}

func (p *DroidReportUpdatePatch) SectorID() string {
	v, _ := p.patchSet.Get("SectorID").(string)

	return v
}

func (p *DroidReportUpdatePatch) SectorIDIsSet() bool {
	return p.patchSet.IsSet("SectorID")
}

func (p *DroidReportUpdatePatch) SetShipID(v ccc.UUID) *DroidReportUpdatePatch {
	p.patchSet.Set("ShipID", v)

	return p
}

func (p *DroidReportUpdatePatch) ShipID() ccc.UUID {
	v, _ := p.patchSet.Get("ShipID").(ccc.UUID)

	return v
}

func (p *DroidReportUpdatePatch) ShipIDIsSet() bool {
	return p.patchSet.IsSet("ShipID")
}

func (p *DroidReportUpdatePatch) SetSubsystem(v string) *DroidReportUpdatePatch {
	p.patchSet.Set("Subsystem", v)

	return p
}

func (p *DroidReportUpdatePatch) Subsystem() string {
	v, _ := p.patchSet.Get("Subsystem").(string)

	return v
}

func (p *DroidReportUpdatePatch) SubsystemIsSet() bool {
	return p.patchSet.IsSet("Subsystem")
}

func (p *DroidReportUpdatePatch) SetReading(v float64) *DroidReportUpdatePatch {
	p.patchSet.Set("Reading", v)

	return p
}

func (p *DroidReportUpdatePatch) Reading() float64 {
	v, _ := p.patchSet.Get("Reading").(float64)

	return v
}

func (p *DroidReportUpdatePatch) ReadingIsSet() bool {
	return p.patchSet.IsSet("Reading")
}

func (p *DroidReportUpdatePatch) SetRecordedAt(v time.Time) *DroidReportUpdatePatch {
	p.patchSet.Set("RecordedAt", v)

	return p
}

func (p *DroidReportUpdatePatch) RecordedAt() time.Time {
	v, _ := p.patchSet.Get("RecordedAt").(time.Time)

	return v
}

func (p *DroidReportUpdatePatch) RecordedAtIsSet() bool {
	return p.patchSet.IsSet("RecordedAt")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *DroidReportUpdatePatch) Diff(got *DroidReportUpdatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type DroidReportDeletePatch struct {
	patchSet *resource.PatchSet[DroidReport]
}

func NewDroidReportDeletePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[DroidReport]) *DroidReportDeletePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &DroidReportDeletePatch{patchSet: patchSet}
}

func NewDroidReportDeletePatch(id ccc.UUID) *DroidReportDeletePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[DroidReport]()).
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &DroidReportDeletePatch{patchSet: patchSet}
}

func (p *DroidReportDeletePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *DroidReportDeletePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *DroidReportDeletePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *DroidReportDeletePatch) Diff(got *DroidReportDeletePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}
