// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package resources

import (
	"context"
	"iter"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/go-playground/errors/v5"
	"github.com/google/go-cmp/cmp"
)

func (Squadron) Resource() accesstypes.Resource {
	return "Squadrons"
}

func (Squadron) DefaultConfig() resource.Config {
	return defaultConfig()
}

// squadronRead mirrors the wire shape the resource routes list
// and read, so a query armed with Enforce meets the field permissions the routes
// enforce; squadronReadSets holds one Set per read operation.
type squadronRead struct {
	ID     ccc.UUID `json:"id"     perm:"-"`
	WingID ccc.UUID `json:"wingId"`
	Name   string   `json:"name"`
}

var squadronReadSets resource.SetCache[Squadron, squadronRead]

// squadronWrite mirrors the wire shape the resource routes
// accept on a mutation, so a patch armed with Enforce meets the field permissions the
// routes enforce; squadronWriteSets holds one Set per mutation.
type squadronWrite struct {
	ID     ccc.UUID `json:"-"`
	WingID ccc.UUID `json:"wingId"`
	Name   string   `json:"name"`
}

var squadronWriteSets resource.SetCache[Squadron, squadronWrite]

type SquadronQuery struct {
	qSet *resource.QuerySet[Squadron]
	// caller arms Read and List against a request's caller; nil runs them trusted.
	caller *resource.Caller
}

func NewSquadronQuery() *SquadronQuery {
	return &SquadronQuery{qSet: resource.NewQuerySet(resource.NewMetadata[Squadron]())}
}

func NewSquadronQueryFromQuerySet(qSet *resource.QuerySet[Squadron]) *SquadronQuery {
	return &SquadronQuery{qSet: qSet}
}

func (q *SquadronQuery) SetID(v ccc.UUID) *SquadronQuery {
	q.qSet.SetKey("ID", v)

	return q
}

func (q *SquadronQuery) ID() ccc.UUID {
	v, _ := q.qSet.Key("ID").(ccc.UUID)

	return v
}

// Enforce arms the query against the caller a generated handler stamped on the
// context (resource.CallerFrom): Read runs the routes' Read permission gate and List
// the List gate — resource, then the requested fields, conditional grants riding the
// query — before touching the database. Without it the query runs trusted.
func (q *SquadronQuery) Enforce(caller *resource.Caller) *SquadronQuery {
	q.caller = caller

	return q
}

func (q *SquadronQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[Squadron], error) {
	if q.caller != nil {
		q.qSet.Enforce(q.caller, squadronReadSets.For(accesstypes.Read), accesstypes.Read)
	}

	return q.qSet.Read(ctx, txn)
}

func (q *SquadronQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[Squadron], error] {
	if q.caller != nil {
		q.qSet.Enforce(q.caller, squadronReadSets.For(accesstypes.List), accesstypes.List)
	}

	return q.qSet.List(ctx, txn)
}

func (q *SquadronQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[Squadron], error]] {
	if q.caller != nil {
		q.qSet.Enforce(q.caller, squadronReadSets.For(accesstypes.List), accesstypes.List)
	}

	return q.qSet.BatchList(ctx, client, size)
}

func (q *SquadronQuery) AddColumns(c *SquadronColumns) *SquadronQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *SquadronQuery) Where(c SquadronQueryClause) *SquadronQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *SquadronQuery) Sort(sort *SquadronSort) *SquadronQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *SquadronQuery) Limit(n uint64) *SquadronQuery {
	q.qSet.SetLimit(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *SquadronQuery) Diff(got *SquadronQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type SquadronColumns struct {
	fields []accesstypes.Field
}

func NewSquadronColumns() *SquadronColumns {
	return &SquadronColumns{}
}

func (c *SquadronColumns) All() *SquadronColumns {
	c.fields = []accesstypes.Field{
		"ID",
		"WingID",
		"Name",
	}

	return c
}

func (c *SquadronColumns) ID() *SquadronColumns {
	c.fields = append(c.fields, "ID")

	return c
}

func (c *SquadronColumns) WingID() *SquadronColumns {
	c.fields = append(c.fields, "WingID")

	return c
}

func (c *SquadronColumns) Name() *SquadronColumns {
	c.fields = append(c.fields, "Name")

	return c
}

type SquadronQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewSquadronQueryClause() SquadronQueryPartialClause {
	return SquadronQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p SquadronQueryPartialClause) Group(qc SquadronQueryClause) SquadronQueryClause {
	return SquadronQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p SquadronQueryPartialClause) ID() SquadronQueryIdent[ccc.UUID] {
	return SquadronQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("ID", p.partialClause, true)}
}

func (p SquadronQueryPartialClause) WingID() SquadronQueryIdent[ccc.UUID] {
	return SquadronQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("WingID", p.partialClause, true)}
}

func (p SquadronQueryPartialClause) Name() SquadronQueryIdent[string] {
	return SquadronQueryIdent[string]{Ident: resource.NewIdent[string]("Name", p.partialClause, true)}
}

type SquadronQueryClause struct {
	clause resource.QueryClause
}

func (qc SquadronQueryClause) And() SquadronQueryPartialClause {
	return SquadronQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc SquadronQueryClause) Or() SquadronQueryPartialClause {
	return SquadronQueryPartialClause{partialClause: qc.clause.Or()}
}

type SquadronQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i SquadronQueryIdent[T]) Equal(v ...T) SquadronQueryClause {
	return SquadronQueryClause{clause: i.Ident.Equal(v...)}
}

func (i SquadronQueryIdent[T]) NotEqual(v ...T) SquadronQueryClause {
	return SquadronQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i SquadronQueryIdent[T]) GreaterThan(v T) SquadronQueryClause {
	return SquadronQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i SquadronQueryIdent[T]) GreaterThanEq(v T) SquadronQueryClause {
	return SquadronQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i SquadronQueryIdent[T]) LessThan(v T) SquadronQueryClause {
	return SquadronQueryClause{clause: i.Ident.LessThan(v)}
}

func (i SquadronQueryIdent[T]) LessThanEq(v T) SquadronQueryClause {
	return SquadronQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i SquadronQueryIdent[T]) IsNull() SquadronQueryClause {
	return SquadronQueryClause{clause: i.Ident.IsNull()}
}

func (i SquadronQueryIdent[T]) IsNotNull() SquadronQueryClause {
	return SquadronQueryClause{clause: i.Ident.IsNotNull()}
}

type SquadronSortBuilder struct {
	*squadronSort
}

func NewSquadronSort() *SquadronSortBuilder {
	return &SquadronSortBuilder{squadronSort: &squadronSort{}}
}

type squadronSort struct {
	sortFields []resource.SortField
}

func (c *squadronSort) addField(field string) *SquadronSort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &SquadronSort{squadronSort: c}
}

func (c *squadronSort) ID() *SquadronSort {
	return c.addField("ID")
}

func (c *squadronSort) WingID() *SquadronSort {
	return c.addField("WingID")
}

func (c *squadronSort) Name() *SquadronSort {
	return c.addField("Name")
}

type SquadronSort struct {
	*squadronSort
}

func (s *SquadronSort) Asc() *SquadronSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *SquadronSort) Desc() *SquadronSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}

type SquadronCreatePatch struct {
	patchSet *resource.PatchSet[Squadron]
}

func NewSquadronCreatePatchFromPatchSet(patchSet *resource.PatchSet[Squadron]) (*SquadronCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &SquadronCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func NewSquadronCreatePatch() (*SquadronCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet := resource.NewPatchSet(resource.NewMetadata[Squadron]()).
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &SquadronCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func (p *SquadronCreatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *SquadronCreatePatch) ToStruct() *Squadron {
	return p.patchSet.ToStruct()
}

func (p *SquadronCreatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *SquadronCreatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

// Enforce arms the mutation against the caller a generated handler stamped on the
// context (resource.CallerFrom): Apply and Buffer run the full pipeline the resource
// routes run for Create — the static field gate, the fold of conditional grants,
// the live check against the real row inside the transaction, and the tenancy
// check — and refuse with the same Forbidden the routes answer. Without it the
// mutation runs trusted.
func (p *SquadronCreatePatch) Enforce(caller *resource.Caller) *SquadronCreatePatch {
	p.patchSet.Enforce(caller, squadronWriteSets.For(accesstypes.Create), accesstypes.Create)

	return p
}

func (p *SquadronCreatePatch) registerDefaultFuncs() {
}

func (p *SquadronCreatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *SquadronCreatePatch) SetWingID(v ccc.UUID) *SquadronCreatePatch {
	p.patchSet.Set("WingID", v)

	return p
}

func (p *SquadronCreatePatch) WingID() ccc.UUID {
	v, _ := p.patchSet.Get("WingID").(ccc.UUID)

	return v
}

func (p *SquadronCreatePatch) WingIDIsSet() bool {
	return p.patchSet.IsSet("WingID")
}

func (p *SquadronCreatePatch) SetName(v string) *SquadronCreatePatch {
	p.patchSet.Set("Name", v)

	return p
}

func (p *SquadronCreatePatch) Name() string {
	v, _ := p.patchSet.Get("Name").(string)

	return v
}

func (p *SquadronCreatePatch) NameIsSet() bool {
	return p.patchSet.IsSet("Name")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *SquadronCreatePatch) Diff(got *SquadronCreatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type SquadronUpdatePatch struct {
	patchSet *resource.PatchSet[Squadron]
}

func NewSquadronUpdatePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[Squadron]) *SquadronUpdatePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &SquadronUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func NewSquadronUpdatePatch(id ccc.UUID) *SquadronUpdatePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Squadron]()).
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &SquadronUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func (p *SquadronUpdatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *SquadronUpdatePatch) ToStruct() *Squadron {
	return p.patchSet.ToStruct()
}

func (p *SquadronUpdatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *SquadronUpdatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

// Enforce arms the mutation against the caller a generated handler stamped on the
// context (resource.CallerFrom): Apply and Buffer run the full pipeline the resource
// routes run for Update — the static field gate, the fold of conditional grants,
// the live check against the real row inside the transaction, and the tenancy
// check — and refuse with the same Forbidden the routes answer. Without it the
// mutation runs trusted.
func (p *SquadronUpdatePatch) Enforce(caller *resource.Caller) *SquadronUpdatePatch {
	p.patchSet.Enforce(caller, squadronWriteSets.For(accesstypes.Update), accesstypes.Update)

	return p
}

func (p *SquadronUpdatePatch) registerDefaultFuncs() {
}

func (p *SquadronUpdatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *SquadronUpdatePatch) SetWingID(v ccc.UUID) *SquadronUpdatePatch {
	p.patchSet.Set("WingID", v)

	return p
}

func (p *SquadronUpdatePatch) WingID() ccc.UUID {
	v, _ := p.patchSet.Get("WingID").(ccc.UUID)

	return v
}

func (p *SquadronUpdatePatch) WingIDIsSet() bool {
	return p.patchSet.IsSet("WingID")
}

func (p *SquadronUpdatePatch) SetName(v string) *SquadronUpdatePatch {
	p.patchSet.Set("Name", v)

	return p
}

func (p *SquadronUpdatePatch) Name() string {
	v, _ := p.patchSet.Get("Name").(string)

	return v
}

func (p *SquadronUpdatePatch) NameIsSet() bool {
	return p.patchSet.IsSet("Name")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *SquadronUpdatePatch) Diff(got *SquadronUpdatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type SquadronDeletePatch struct {
	patchSet *resource.PatchSet[Squadron]
}

func NewSquadronDeletePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[Squadron]) *SquadronDeletePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &SquadronDeletePatch{patchSet: patchSet}
}

func NewSquadronDeletePatch(id ccc.UUID) *SquadronDeletePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Squadron]()).
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &SquadronDeletePatch{patchSet: patchSet}
}

func (p *SquadronDeletePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *SquadronDeletePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

// Enforce arms the mutation against the caller a generated handler stamped on the
// context (resource.CallerFrom): Apply and Buffer run the full pipeline the resource
// routes run for Delete — the static field gate, the fold of conditional grants,
// the live check against the real row inside the transaction, and the tenancy
// check — and refuse with the same Forbidden the routes answer. Without it the
// mutation runs trusted.
func (p *SquadronDeletePatch) Enforce(caller *resource.Caller) *SquadronDeletePatch {
	p.patchSet.Enforce(caller, squadronWriteSets.For(accesstypes.Delete), accesstypes.Delete)

	return p
}

func (p *SquadronDeletePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *SquadronDeletePatch) Diff(got *SquadronDeletePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}
