// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package resources

import (
	"context"
	"iter"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/go-playground/errors/v5"
	"github.com/google/go-cmp/cmp"
	"github.com/shopspring/decimal"
)

func (Refit) Resource() accesstypes.Resource {
	return "Refits"
}

func (Refit) DefaultConfig() resource.Config {
	return defaultConfig()
}

type RefitQuery struct {
	qSet *resource.QuerySet[Refit]
}

func NewRefitQuery() *RefitQuery {
	return &RefitQuery{qSet: resource.NewQuerySet(resource.NewMetadata[Refit]())}
}

func NewRefitQueryFromQuerySet(qSet *resource.QuerySet[Refit]) *RefitQuery {
	return &RefitQuery{qSet: qSet}
}

func (q *RefitQuery) SetID(v ccc.UUID) *RefitQuery {
	q.qSet.SetKey("ID", v)

	return q
}

func (q *RefitQuery) ID() ccc.UUID {
	v, _ := q.qSet.Key("ID").(ccc.UUID)

	return v
}

func (q *RefitQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[Refit], error) {
	return q.qSet.Read(ctx, txn)
}

func (q *RefitQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[Refit], error] {
	return q.qSet.List(ctx, txn)
}

func (q *RefitQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[Refit], error]] {
	return q.qSet.BatchList(ctx, client, size)
}

func (q *RefitQuery) AddColumns(c *RefitColumns) *RefitQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *RefitQuery) Where(c RefitQueryClause) *RefitQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *RefitQuery) Sort(sort *RefitSort) *RefitQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *RefitQuery) Limit(n uint64) *RefitQuery {
	q.qSet.SetLimit(&n)

	return q
}

func (q *RefitQuery) Offset(n uint64) *RefitQuery {
	q.qSet.SetOffset(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *RefitQuery) Diff(got *RefitQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type RefitColumns struct {
	fields []accesstypes.Field
}

func NewRefitColumns() *RefitColumns {
	return &RefitColumns{}
}

func (c *RefitColumns) All() *RefitColumns {
	c.fields = []accesstypes.Field{
		"ID",
		"ShipID",
		"StatusID",
		"Estimate",
		"InspectedAt",
		"OpenedBy",
		"Notes",
	}

	return c
}

func (c *RefitColumns) ID() *RefitColumns {
	c.fields = append(c.fields, "ID")

	return c
}

func (c *RefitColumns) ShipID() *RefitColumns {
	c.fields = append(c.fields, "ShipID")

	return c
}

func (c *RefitColumns) StatusID() *RefitColumns {
	c.fields = append(c.fields, "StatusID")

	return c
}

func (c *RefitColumns) Estimate() *RefitColumns {
	c.fields = append(c.fields, "Estimate")

	return c
}

func (c *RefitColumns) InspectedAt() *RefitColumns {
	c.fields = append(c.fields, "InspectedAt")

	return c
}

func (c *RefitColumns) OpenedBy() *RefitColumns {
	c.fields = append(c.fields, "OpenedBy")

	return c
}

func (c *RefitColumns) Notes() *RefitColumns {
	c.fields = append(c.fields, "Notes")

	return c
}

type RefitQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewRefitQueryClause() RefitQueryPartialClause {
	return RefitQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p RefitQueryPartialClause) Group(qc RefitQueryClause) RefitQueryClause {
	return RefitQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p RefitQueryPartialClause) ID() RefitQueryIdent[ccc.UUID] {
	return RefitQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("ID", p.partialClause, true)}
}

func (p RefitQueryPartialClause) ShipID() RefitQueryIdent[ccc.UUID] {
	return RefitQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("ShipID", p.partialClause, true)}
}

func (p RefitQueryPartialClause) StatusID() RefitQueryIdent[string] {
	return RefitQueryIdent[string]{Ident: resource.NewIdent[string]("StatusID", p.partialClause, true)}
}

type RefitQueryClause struct {
	clause resource.QueryClause
}

func (qc RefitQueryClause) And() RefitQueryPartialClause {
	return RefitQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc RefitQueryClause) Or() RefitQueryPartialClause {
	return RefitQueryPartialClause{partialClause: qc.clause.Or()}
}

type RefitQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i RefitQueryIdent[T]) Equal(v ...T) RefitQueryClause {
	return RefitQueryClause{clause: i.Ident.Equal(v...)}
}

func (i RefitQueryIdent[T]) NotEqual(v ...T) RefitQueryClause {
	return RefitQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i RefitQueryIdent[T]) GreaterThan(v T) RefitQueryClause {
	return RefitQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i RefitQueryIdent[T]) GreaterThanEq(v T) RefitQueryClause {
	return RefitQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i RefitQueryIdent[T]) LessThan(v T) RefitQueryClause {
	return RefitQueryClause{clause: i.Ident.LessThan(v)}
}

func (i RefitQueryIdent[T]) LessThanEq(v T) RefitQueryClause {
	return RefitQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i RefitQueryIdent[T]) IsNull() RefitQueryClause {
	return RefitQueryClause{clause: i.Ident.IsNull()}
}

func (i RefitQueryIdent[T]) IsNotNull() RefitQueryClause {
	return RefitQueryClause{clause: i.Ident.IsNotNull()}
}

type RefitSortBuilder struct {
	*refitSort
}

func NewRefitSort() *RefitSortBuilder {
	return &RefitSortBuilder{refitSort: &refitSort{}}
}

type refitSort struct {
	sortFields []resource.SortField
}

func (c *refitSort) addField(field string) *RefitSort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &RefitSort{refitSort: c}
}

func (c *refitSort) ID() *RefitSort {
	return c.addField("ID")
}

func (c *refitSort) ShipID() *RefitSort {
	return c.addField("ShipID")
}

func (c *refitSort) StatusID() *RefitSort {
	return c.addField("StatusID")
}

func (c *refitSort) Estimate() *RefitSort {
	return c.addField("Estimate")
}

func (c *refitSort) InspectedAt() *RefitSort {
	return c.addField("InspectedAt")
}

func (c *refitSort) OpenedBy() *RefitSort {
	return c.addField("OpenedBy")
}

func (c *refitSort) Notes() *RefitSort {
	return c.addField("Notes")
}

type RefitSort struct {
	*refitSort
}

func (s *RefitSort) Asc() *RefitSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *RefitSort) Desc() *RefitSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}

type RefitCreatePatch struct {
	patchSet *resource.PatchSet[Refit]
}

func NewRefitCreatePatchFromPatchSet(patchSet *resource.PatchSet[Refit]) (*RefitCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &RefitCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func NewRefitCreatePatch() (*RefitCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet := resource.NewPatchSet(resource.NewMetadata[Refit]()).
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &RefitCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func (p *RefitCreatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *RefitCreatePatch) ToStruct() *Refit {
	return p.patchSet.ToStruct()
}

func (p *RefitCreatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *RefitCreatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *RefitCreatePatch) registerDefaultFuncs() {
	p.patchSet.RegisterDefaultCreateFunc("StatusID", func(context.Context, resource.ReadWriteTransaction) (any, error) {
		return string("docked"), nil
	})
	p.patchSet.RegisterDefaultCreateFunc("OpenedBy", currentUser)
}

func (p *RefitCreatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *RefitCreatePatch) SetShipID(v ccc.UUID) *RefitCreatePatch {
	p.patchSet.Set("ShipID", v)

	return p
}

func (p *RefitCreatePatch) ShipID() ccc.UUID {
	v, _ := p.patchSet.Get("ShipID").(ccc.UUID)

	return v
}

func (p *RefitCreatePatch) ShipIDIsSet() bool {
	return p.patchSet.IsSet("ShipID")
}

func (p *RefitCreatePatch) SetStatusID(v string) *RefitCreatePatch {
	p.patchSet.Set("StatusID", v)

	return p
}

func (p *RefitCreatePatch) StatusID() string {
	v, _ := p.patchSet.Get("StatusID").(string)

	return v
}

func (p *RefitCreatePatch) StatusIDIsSet() bool {
	return p.patchSet.IsSet("StatusID")
}

func (p *RefitCreatePatch) SetEstimate(v decimal.NullDecimal) *RefitCreatePatch {
	p.patchSet.Set("Estimate", v)

	return p
}

func (p *RefitCreatePatch) Estimate() decimal.NullDecimal {
	v, _ := p.patchSet.Get("Estimate").(decimal.NullDecimal)

	return v
}

func (p *RefitCreatePatch) EstimateIsSet() bool {
	return p.patchSet.IsSet("Estimate")
}

func (p *RefitCreatePatch) SetInspectedAt(v *time.Time) *RefitCreatePatch {
	if v != nil {
		p.patchSet.Set("InspectedAt", v)
	} else {
		p.patchSet.Set("InspectedAt", nil)
	}

	return p
}

func (p *RefitCreatePatch) InspectedAt() *time.Time {
	v, _ := p.patchSet.Get("InspectedAt").(*time.Time)

	return v
}

func (p *RefitCreatePatch) InspectedAtIsSet() bool {
	return p.patchSet.IsSet("InspectedAt")
}

func (p *RefitCreatePatch) SetOpenedBy(v string) *RefitCreatePatch {
	p.patchSet.Set("OpenedBy", v)

	return p
}

func (p *RefitCreatePatch) OpenedBy() string {
	v, _ := p.patchSet.Get("OpenedBy").(string)

	return v
}

func (p *RefitCreatePatch) OpenedByIsSet() bool {
	return p.patchSet.IsSet("OpenedBy")
}

func (p *RefitCreatePatch) SetNotes(v *string) *RefitCreatePatch {
	if v != nil {
		p.patchSet.Set("Notes", v)
	} else {
		p.patchSet.Set("Notes", nil)
	}

	return p
}

func (p *RefitCreatePatch) Notes() *string {
	v, _ := p.patchSet.Get("Notes").(*string)

	return v
}

func (p *RefitCreatePatch) NotesIsSet() bool {
	return p.patchSet.IsSet("Notes")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *RefitCreatePatch) Diff(got *RefitCreatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type RefitUpdatePatch struct {
	patchSet *resource.PatchSet[Refit]
}

func NewRefitUpdatePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[Refit]) *RefitUpdatePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &RefitUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func NewRefitUpdatePatch(id ccc.UUID) *RefitUpdatePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Refit]()).
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &RefitUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func (p *RefitUpdatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *RefitUpdatePatch) ToStruct() *Refit {
	return p.patchSet.ToStruct()
}

func (p *RefitUpdatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *RefitUpdatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *RefitUpdatePatch) registerDefaultFuncs() {
	p.patchSet.RegisterDefaultsUpdateFunc(func(ctx context.Context, txn resource.ReadWriteTransaction) error {
		return new(RefitUpdateDefaults).Defaults(ctx, txn, p)
	})
	p.patchSet.RegisterValidateUpdateFunc(func(ctx context.Context, txn resource.ReadWriteTransaction) error {
		return new(RefitUpdateValidator).Validate(ctx, txn, p)
	})
}

func (p *RefitUpdatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *RefitUpdatePatch) SetShipID(v ccc.UUID) *RefitUpdatePatch {
	p.patchSet.Set("ShipID", v)

	return p
}

func (p *RefitUpdatePatch) ShipID() ccc.UUID {
	v, _ := p.patchSet.Get("ShipID").(ccc.UUID)

	return v
}

func (p *RefitUpdatePatch) ShipIDIsSet() bool {
	return p.patchSet.IsSet("ShipID")
}

func (p *RefitUpdatePatch) SetStatusID(v string) *RefitUpdatePatch {
	p.patchSet.Set("StatusID", v)

	return p
}

func (p *RefitUpdatePatch) StatusID() string {
	v, _ := p.patchSet.Get("StatusID").(string)

	return v
}

func (p *RefitUpdatePatch) StatusIDIsSet() bool {
	return p.patchSet.IsSet("StatusID")
}

func (p *RefitUpdatePatch) SetEstimate(v decimal.NullDecimal) *RefitUpdatePatch {
	p.patchSet.Set("Estimate", v)

	return p
}

func (p *RefitUpdatePatch) Estimate() decimal.NullDecimal {
	v, _ := p.patchSet.Get("Estimate").(decimal.NullDecimal)

	return v
}

func (p *RefitUpdatePatch) EstimateIsSet() bool {
	return p.patchSet.IsSet("Estimate")
}

func (p *RefitUpdatePatch) SetInspectedAt(v *time.Time) *RefitUpdatePatch {
	if v != nil {
		p.patchSet.Set("InspectedAt", v)
	} else {
		p.patchSet.Set("InspectedAt", nil)
	}

	return p
}

func (p *RefitUpdatePatch) InspectedAt() *time.Time {
	v, _ := p.patchSet.Get("InspectedAt").(*time.Time)

	return v
}

func (p *RefitUpdatePatch) InspectedAtIsSet() bool {
	return p.patchSet.IsSet("InspectedAt")
}

func (p *RefitUpdatePatch) SetOpenedBy(v string) *RefitUpdatePatch {
	p.patchSet.Set("OpenedBy", v)

	return p
}

func (p *RefitUpdatePatch) OpenedBy() string {
	v, _ := p.patchSet.Get("OpenedBy").(string)

	return v
}

func (p *RefitUpdatePatch) OpenedByIsSet() bool {
	return p.patchSet.IsSet("OpenedBy")
}

func (p *RefitUpdatePatch) SetNotes(v *string) *RefitUpdatePatch {
	if v != nil {
		p.patchSet.Set("Notes", v)
	} else {
		p.patchSet.Set("Notes", nil)
	}

	return p
}

func (p *RefitUpdatePatch) Notes() *string {
	v, _ := p.patchSet.Get("Notes").(*string)

	return v
}

func (p *RefitUpdatePatch) NotesIsSet() bool {
	return p.patchSet.IsSet("Notes")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *RefitUpdatePatch) Diff(got *RefitUpdatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type RefitDeletePatch struct {
	patchSet *resource.PatchSet[Refit]
}

func NewRefitDeletePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[Refit]) *RefitDeletePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &RefitDeletePatch{patchSet: patchSet}
}

func NewRefitDeletePatch(id ccc.UUID) *RefitDeletePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[Refit]()).
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &RefitDeletePatch{patchSet: patchSet}
}

func (p *RefitDeletePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *RefitDeletePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *RefitDeletePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *RefitDeletePatch) Diff(got *RefitDeletePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}
