// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/resources

package resources

import (
	"context"
	"iter"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource"
	"github.com/go-playground/errors/v5"
	"github.com/google/go-cmp/cmp"
	"github.com/shopspring/decimal"
)

func (SortieExpense) Resource() accesstypes.Resource {
	return "SortieExpenses"
}

func (SortieExpense) DefaultConfig() resource.Config {
	return defaultConfig()
}

type SortieExpenseQuery struct {
	qSet *resource.QuerySet[SortieExpense]
}

func NewSortieExpenseQuery() *SortieExpenseQuery {
	return &SortieExpenseQuery{qSet: resource.NewQuerySet(resource.NewMetadata[SortieExpense]())}
}

func NewSortieExpenseQueryFromQuerySet(qSet *resource.QuerySet[SortieExpense]) *SortieExpenseQuery {
	return &SortieExpenseQuery{qSet: qSet}
}

func (q *SortieExpenseQuery) SetID(v ccc.UUID) *SortieExpenseQuery {
	q.qSet.SetKey("ID", v)

	return q
}

func (q *SortieExpenseQuery) ID() ccc.UUID {
	v, _ := q.qSet.Key("ID").(ccc.UUID)

	return v
}

func (q *SortieExpenseQuery) Read(ctx context.Context, txn resource.ReadOnlyTransaction) (*resource.Row[SortieExpense], error) {
	return q.qSet.Read(ctx, txn)
}

func (q *SortieExpenseQuery) List(ctx context.Context, txn resource.ReadOnlyTransaction) iter.Seq2[*resource.Row[SortieExpense], error] {
	return q.qSet.List(ctx, txn)
}

func (q *SortieExpenseQuery) BatchList(ctx context.Context, client resource.Client, size int) iter.Seq[iter.Seq2[*resource.Row[SortieExpense], error]] {
	return q.qSet.BatchList(ctx, client, size)
}

func (q *SortieExpenseQuery) AddColumns(c *SortieExpenseColumns) *SortieExpenseQuery {
	for _, field := range c.fields {
		q.qSet.AddField(field)
	}

	return q
}

func (q *SortieExpenseQuery) Where(c SortieExpenseQueryClause) *SortieExpenseQuery {
	if err := c.clause.Validate(); err != nil {
		panic(err)
	}
	q.qSet.SetWhereClause(c.clause)

	return q
}

func (q *SortieExpenseQuery) Sort(sort *SortieExpenseSort) *SortieExpenseQuery {
	q.qSet.SetSortFields(sort.sortFields)

	return q
}

func (q *SortieExpenseQuery) Limit(n uint64) *SortieExpenseQuery {
	q.qSet.SetLimit(&n)

	return q
}

func (q *SortieExpenseQuery) Offset(n uint64) *SortieExpenseQuery {
	q.qSet.SetOffset(&n)

	return q
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (q *SortieExpenseQuery) Diff(got *SortieExpenseQuery, opts ...cmp.Option) string {
	return resource.QuerySetDiff(opts...)(q.qSet, got.qSet)
}

type SortieExpenseColumns struct {
	fields []accesstypes.Field
}

func NewSortieExpenseColumns() *SortieExpenseColumns {
	return &SortieExpenseColumns{}
}

func (c *SortieExpenseColumns) All() *SortieExpenseColumns {
	c.fields = []accesstypes.Field{
		"ID",
		"SortieID",
		"Category",
		"Amount",
		"Note",
	}

	return c
}

func (c *SortieExpenseColumns) ID() *SortieExpenseColumns {
	c.fields = append(c.fields, "ID")

	return c
}

func (c *SortieExpenseColumns) SortieID() *SortieExpenseColumns {
	c.fields = append(c.fields, "SortieID")

	return c
}

func (c *SortieExpenseColumns) Category() *SortieExpenseColumns {
	c.fields = append(c.fields, "Category")

	return c
}

func (c *SortieExpenseColumns) Amount() *SortieExpenseColumns {
	c.fields = append(c.fields, "Amount")

	return c
}

func (c *SortieExpenseColumns) Note() *SortieExpenseColumns {
	c.fields = append(c.fields, "Note")

	return c
}

type SortieExpenseQueryPartialClause struct {
	partialClause resource.PartialQueryClause
}

func NewSortieExpenseQueryClause() SortieExpenseQueryPartialClause {
	return SortieExpenseQueryPartialClause{partialClause: resource.NewPartialQueryClause()}
}

func (p SortieExpenseQueryPartialClause) Group(qc SortieExpenseQueryClause) SortieExpenseQueryClause {
	return SortieExpenseQueryClause{clause: p.partialClause.Group(qc.clause)}
}

func (p SortieExpenseQueryPartialClause) ID() SortieExpenseQueryIdent[ccc.UUID] {
	return SortieExpenseQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("ID", p.partialClause, true)}
}

func (p SortieExpenseQueryPartialClause) SortieID() SortieExpenseQueryIdent[ccc.UUID] {
	return SortieExpenseQueryIdent[ccc.UUID]{Ident: resource.NewIdent[ccc.UUID]("SortieID", p.partialClause, true)}
}

type SortieExpenseQueryClause struct {
	clause resource.QueryClause
}

func (qc SortieExpenseQueryClause) And() SortieExpenseQueryPartialClause {
	return SortieExpenseQueryPartialClause{partialClause: qc.clause.And()}
}

func (qc SortieExpenseQueryClause) Or() SortieExpenseQueryPartialClause {
	return SortieExpenseQueryPartialClause{partialClause: qc.clause.Or()}
}

type SortieExpenseQueryIdent[T comparable] struct {
	resource.Ident[T]
}

func (i SortieExpenseQueryIdent[T]) Equal(v ...T) SortieExpenseQueryClause {
	return SortieExpenseQueryClause{clause: i.Ident.Equal(v...)}
}

func (i SortieExpenseQueryIdent[T]) NotEqual(v ...T) SortieExpenseQueryClause {
	return SortieExpenseQueryClause{clause: i.Ident.NotEqual(v...)}
}

func (i SortieExpenseQueryIdent[T]) GreaterThan(v T) SortieExpenseQueryClause {
	return SortieExpenseQueryClause{clause: i.Ident.GreaterThan(v)}
}

func (i SortieExpenseQueryIdent[T]) GreaterThanEq(v T) SortieExpenseQueryClause {
	return SortieExpenseQueryClause{clause: i.Ident.GreaterThanEq(v)}
}

func (i SortieExpenseQueryIdent[T]) LessThan(v T) SortieExpenseQueryClause {
	return SortieExpenseQueryClause{clause: i.Ident.LessThan(v)}
}

func (i SortieExpenseQueryIdent[T]) LessThanEq(v T) SortieExpenseQueryClause {
	return SortieExpenseQueryClause{clause: i.Ident.LessThanEq(v)}
}

func (i SortieExpenseQueryIdent[T]) IsNull() SortieExpenseQueryClause {
	return SortieExpenseQueryClause{clause: i.Ident.IsNull()}
}

func (i SortieExpenseQueryIdent[T]) IsNotNull() SortieExpenseQueryClause {
	return SortieExpenseQueryClause{clause: i.Ident.IsNotNull()}
}

type SortieExpenseSortBuilder struct {
	*sortieExpenseSort
}

func NewSortieExpenseSort() *SortieExpenseSortBuilder {
	return &SortieExpenseSortBuilder{sortieExpenseSort: &sortieExpenseSort{}}
}

type sortieExpenseSort struct {
	sortFields []resource.SortField
}

func (c *sortieExpenseSort) addField(field string) *SortieExpenseSort {
	c.sortFields = append(c.sortFields, resource.SortField{Field: field, Direction: resource.SortAscending})

	return &SortieExpenseSort{sortieExpenseSort: c}
}

func (c *sortieExpenseSort) ID() *SortieExpenseSort {
	return c.addField("ID")
}

func (c *sortieExpenseSort) SortieID() *SortieExpenseSort {
	return c.addField("SortieID")
}

func (c *sortieExpenseSort) Category() *SortieExpenseSort {
	return c.addField("Category")
}

func (c *sortieExpenseSort) Amount() *SortieExpenseSort {
	return c.addField("Amount")
}

func (c *sortieExpenseSort) Note() *SortieExpenseSort {
	return c.addField("Note")
}

type SortieExpenseSort struct {
	*sortieExpenseSort
}

func (s *SortieExpenseSort) Asc() *SortieExpenseSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortAscending

	return s
}

func (s *SortieExpenseSort) Desc() *SortieExpenseSort {
	s.sortFields[len(s.sortFields)-1].Direction = resource.SortDescending

	return s
}

type SortieExpenseCreatePatch struct {
	patchSet *resource.PatchSet[SortieExpense]
}

func NewSortieExpenseCreatePatchFromPatchSet(patchSet *resource.PatchSet[SortieExpense]) (*SortieExpenseCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &SortieExpenseCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func NewSortieExpenseCreatePatch() (*SortieExpenseCreatePatch, error) {
	id, err := ccc.NewUUID()
	if err != nil {
		return nil, errors.Wrap(err, "ccc.NewUUID()")
	}

	patchSet := resource.NewPatchSet(resource.NewMetadata[SortieExpense]()).
		SetKey("ID", id).
		SetPatchType(resource.CreatePatchType)
	patch := &SortieExpenseCreatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch, nil
}

func (p *SortieExpenseCreatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *SortieExpenseCreatePatch) ToStruct() *SortieExpense {
	return p.patchSet.ToStruct()
}

func (p *SortieExpenseCreatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *SortieExpenseCreatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *SortieExpenseCreatePatch) registerDefaultFuncs() {
}

func (p *SortieExpenseCreatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *SortieExpenseCreatePatch) SetSortieID(v ccc.UUID) *SortieExpenseCreatePatch {
	p.patchSet.Set("SortieID", v)

	return p
}

func (p *SortieExpenseCreatePatch) SortieID() ccc.UUID {
	v, _ := p.patchSet.Get("SortieID").(ccc.UUID)

	return v
}

func (p *SortieExpenseCreatePatch) SortieIDIsSet() bool {
	return p.patchSet.IsSet("SortieID")
}

func (p *SortieExpenseCreatePatch) SetCategory(v string) *SortieExpenseCreatePatch {
	p.patchSet.Set("Category", v)

	return p
}

func (p *SortieExpenseCreatePatch) Category() string {
	v, _ := p.patchSet.Get("Category").(string)

	return v
}

func (p *SortieExpenseCreatePatch) CategoryIsSet() bool {
	return p.patchSet.IsSet("Category")
}

func (p *SortieExpenseCreatePatch) SetAmount(v decimal.Decimal) *SortieExpenseCreatePatch {
	p.patchSet.Set("Amount", v)

	return p
}

func (p *SortieExpenseCreatePatch) Amount() decimal.Decimal {
	v, _ := p.patchSet.Get("Amount").(decimal.Decimal)

	return v
}

func (p *SortieExpenseCreatePatch) AmountIsSet() bool {
	return p.patchSet.IsSet("Amount")
}

func (p *SortieExpenseCreatePatch) SetNote(v *string) *SortieExpenseCreatePatch {
	if v != nil {
		p.patchSet.Set("Note", v)
	} else {
		p.patchSet.Set("Note", nil)
	}

	return p
}

func (p *SortieExpenseCreatePatch) Note() *string {
	v, _ := p.patchSet.Get("Note").(*string)

	return v
}

func (p *SortieExpenseCreatePatch) NoteIsSet() bool {
	return p.patchSet.IsSet("Note")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *SortieExpenseCreatePatch) Diff(got *SortieExpenseCreatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type SortieExpenseUpdatePatch struct {
	patchSet *resource.PatchSet[SortieExpense]
}

func NewSortieExpenseUpdatePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[SortieExpense]) *SortieExpenseUpdatePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &SortieExpenseUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func NewSortieExpenseUpdatePatch(id ccc.UUID) *SortieExpenseUpdatePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[SortieExpense]()).
		SetKey("ID", id).
		SetPatchType(resource.UpdatePatchType)

	patch := &SortieExpenseUpdatePatch{patchSet: patchSet}
	patch.registerDefaultFuncs()

	return patch
}

func (p *SortieExpenseUpdatePatch) FromStruct(s any) error {
	return p.patchSet.FromStruct(s)
}

func (p *SortieExpenseUpdatePatch) ToStruct() *SortieExpense {
	return p.patchSet.ToStruct()
}

func (p *SortieExpenseUpdatePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *SortieExpenseUpdatePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *SortieExpenseUpdatePatch) registerDefaultFuncs() {
}

func (p *SortieExpenseUpdatePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

func (p *SortieExpenseUpdatePatch) SetSortieID(v ccc.UUID) *SortieExpenseUpdatePatch {
	p.patchSet.Set("SortieID", v)

	return p
}

func (p *SortieExpenseUpdatePatch) SortieID() ccc.UUID {
	v, _ := p.patchSet.Get("SortieID").(ccc.UUID)

	return v
}

func (p *SortieExpenseUpdatePatch) SortieIDIsSet() bool {
	return p.patchSet.IsSet("SortieID")
}

func (p *SortieExpenseUpdatePatch) SetCategory(v string) *SortieExpenseUpdatePatch {
	p.patchSet.Set("Category", v)

	return p
}

func (p *SortieExpenseUpdatePatch) Category() string {
	v, _ := p.patchSet.Get("Category").(string)

	return v
}

func (p *SortieExpenseUpdatePatch) CategoryIsSet() bool {
	return p.patchSet.IsSet("Category")
}

func (p *SortieExpenseUpdatePatch) SetAmount(v decimal.Decimal) *SortieExpenseUpdatePatch {
	p.patchSet.Set("Amount", v)

	return p
}

func (p *SortieExpenseUpdatePatch) Amount() decimal.Decimal {
	v, _ := p.patchSet.Get("Amount").(decimal.Decimal)

	return v
}

func (p *SortieExpenseUpdatePatch) AmountIsSet() bool {
	return p.patchSet.IsSet("Amount")
}

func (p *SortieExpenseUpdatePatch) SetNote(v *string) *SortieExpenseUpdatePatch {
	if v != nil {
		p.patchSet.Set("Note", v)
	} else {
		p.patchSet.Set("Note", nil)
	}

	return p
}

func (p *SortieExpenseUpdatePatch) Note() *string {
	v, _ := p.patchSet.Get("Note").(*string)

	return v
}

func (p *SortieExpenseUpdatePatch) NoteIsSet() bool {
	return p.patchSet.IsSet("Note")
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *SortieExpenseUpdatePatch) Diff(got *SortieExpenseUpdatePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}

type SortieExpenseDeletePatch struct {
	patchSet *resource.PatchSet[SortieExpense]
}

func NewSortieExpenseDeletePatchFromPatchSet(id ccc.UUID, patchSet *resource.PatchSet[SortieExpense]) *SortieExpenseDeletePatch {
	patchSet.
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &SortieExpenseDeletePatch{patchSet: patchSet}
}

func NewSortieExpenseDeletePatch(id ccc.UUID) *SortieExpenseDeletePatch {
	patchSet := resource.NewPatchSet(resource.NewMetadata[SortieExpense]()).
		SetKey("ID", id).
		SetPatchType(resource.DeletePatchType)

	return &SortieExpenseDeletePatch{patchSet: patchSet}
}

func (p *SortieExpenseDeletePatch) Apply(ctx context.Context, client resource.Client, eventSource ...string) error {
	return p.patchSet.Apply(ctx, client, eventSource...)
}

func (p *SortieExpenseDeletePatch) Buffer(ctx context.Context, txn resource.ReadWriteTransaction, eventSource ...string) error {
	return p.patchSet.Buffer(ctx, txn, eventSource...)
}

func (p *SortieExpenseDeletePatch) ID() ccc.UUID {
	v, _ := p.patchSet.Key("ID").(ccc.UUID)

	return v
}

// Diff is intended for unit testing, and reports the differences between two values using github.com/google/go-cmp/cmp
func (p *SortieExpenseDeletePatch) Diff(got *SortieExpenseDeletePatch, opts ...cmp.Option) string {
	return resource.PatchSetDiff(opts...)(p.patchSet, got.patchSet)
}
