// Code generated by resourcegeneration. DO NOT EDIT.
import { FieldName, Method, Resource, Meta, ValidRPCTypes } from '@cccteam/resource';
import { Methods, Resources } from './zz_gen_constants';

export interface FieldPointer {
  field: FieldName;
}

export interface AttachMissionDocumentConfig {
  missionId: string | FieldPointer;
  title: string | FieldPointer;
}
export interface AttachMissionDocument {
  missionId: string;
  title: string;
}
/** The result AttachMissionDocument answers with. */
export interface AttachMissionDocumentResult {
  documentIDs: string[];
}

export interface BeginRefitConfig {
  refitId: string | FieldPointer;
}
export interface BeginRefit {
  refitId: string;
}

export interface ClaimMissionConfig {
  missionId: string | FieldPointer;
  squadronId: string | FieldPointer;
}
export interface ClaimMission {
  missionId: string;
  squadronId: string;
}

export interface CompileBriefingConfig {
  includeHazards: boolean | FieldPointer;
}
export interface CompileBriefing {
  includeHazards: boolean;
}
/** The result CompileBriefing answers with. */
export interface CompileBriefingResult {
  sector: string;
  compiledAt: Date;
  missions: number;
  openMissions: number;
  worstHazard: number;
  feesOutstanding: number;
  feesRedacted: number;
  overdue: string[];
  hazardBoard: CompileBriefing.HazardLine[];
  hazardWithheld: boolean;
}
export namespace CompileBriefing {
  export interface HazardLine {
    shipName: string;
    subsystem: string;
    worstReading: number;
  }
}

export interface CompleteMissionConfig {
  missionId: string | FieldPointer;
}
export interface CompleteMission {
  missionId: string;
}
/** The result CompleteMission answers with. */
export interface CompleteMissionResult {
  fee: number;
  expenses: number;
  net: number;
  sorties: CompleteMission.SortieCost[];
}
/** The statuses CompleteMission declares; the method chooses one per response. */
export type CompleteMissionStatus = 200 | 409;
/** The answer CompleteMission resolves with: the status the method chose and its typed result. */
export interface CompleteMissionAnswer {
  status: CompleteMissionStatus;
  result: CompleteMissionResult;
}
export namespace CompleteMission {
  export interface SortieCost {
    sortieId: string;
    expenses: number;
  }
}

export interface FailFlightTestConfig {
  refitId: string | FieldPointer;
}
export interface FailFlightTest {
  refitId: string;
}

export interface FailMissionConfig {
  missionId: string | FieldPointer;
  reasonId: string | FieldPointer;
}
export interface FailMission {
  missionId: string;
  reasonId: string;
}

export interface HailShipConfig {
  shipId: string | FieldPointer;
}
export interface HailShip {
  shipId: string;
}
/** The statuses HailShip declares; the method chooses one per response. */
export type HailShipStatus = 204;

export interface HoldMissionConfig {
  missionId: string | FieldPointer;
  reason: string | FieldPointer;
}
export interface HoldMission {
  missionId: string;
  reason: string;
}

export interface InspectShipConfig {
  refitId: string | FieldPointer;
}
export interface InspectShip {
  refitId: string;
}
/** The result InspectShip answers with. */
export interface InspectShipResult {
  refitId: string;
  shipId: string;
  shipName: string;
  subsystems: InspectShip.SubsystemReport[];
}
export namespace InspectShip {
  export interface Reading {
    value: number;
    recordedAt: Date;
  }

  export interface SubsystemReport {
    name: string;
    readings: InspectShip.Reading[];
  }
}

export interface IssueBulletinConfig {
  announcement: string | FieldPointer;
}
export interface IssueBulletin {
  announcement: string;
}

export interface LaunchMissionConfig {
  missionId: string | FieldPointer;
  shipId: string | FieldPointer;
  pilotUserId: string | FieldPointer;
}
export interface LaunchMission {
  missionId: string;
  shipId: string;
  pilotUserId: string;
}

export interface PassFlightTestConfig {
  refitId: string | FieldPointer;
}
export interface PassFlightTest {
  refitId: string;
}

export interface ReleaseConsignmentConfig {
  consignmentId: string | FieldPointer;
}
export interface ReleaseConsignment {
  consignmentId: string;
}
/** The result ReleaseConsignment answers with. */
export interface ReleaseConsignmentResult {
  consignmentId: string;
  bondCode: string;
  releasedAt: Date;
}

export interface ResumeMissionConfig {
  missionId: string | FieldPointer;
}
export interface ResumeMission {
  missionId: string;
}

export interface ScrapShipConfig {
  refitId: string | FieldPointer;
}
export interface ScrapShip {
  refitId: string;
}

export interface StandDownMissionConfig {
  missionId: string | FieldPointer;
}
export interface StandDownMission {
  missionId: string;
}

export interface StartFlightTestConfig {
  refitId: string | FieldPointer;
}
export interface StartFlightTest {
  refitId: string;
}

export interface RPCFieldMeta {
  fieldName: string;
  displayType: ValidRPCTypes;
  enumeratedResource?: Resource;
}

/** A declared workflow transition: the resource the method moves, the states it runs from, and the state it stamps. */
export interface MethodTransition {
  target: Resource;
  from: string[];
  to: string;
}

export interface MethodMeta {
  route: string;
  transition?: MethodTransition;
  /** Set when the method answers with a result body; absent methods resolve with nothing. */
  answers?: true;
  /** The statuses the method declares with @answers; a listed 4xx is the method's own answer, not a refusal by the frame. */
  statuses?: number[];
  /** Set on an @upload method: the request is multipart, and the whole body is bounded by maxBytes. */
  upload?: { maxBytes: number };
  fields: RPCFieldMeta[];
}

export type MethodMap = Record<Method, MethodMeta>;

const methodMap: MethodMap = {
  [Methods.AttachMissionDocument]: {
    route: 'attach-mission-document',
    answers: true,
    upload: { maxBytes: 5242880 },
    fields: [
      { fieldName: 'missionId', displayType: 'uuid' },
      { fieldName: 'title', displayType: 'string' },
    ],
  },
  [Methods.BeginRefit]: {
    route: 'begin-refit',
    transition: { target: Resources.Refits, from: ['inspected'], to: 'in_refit' },
    fields: [
      { fieldName: 'refitId', displayType: 'uuid' },
    ],
  },
  [Methods.ClaimMission]: {
    route: 'claim-mission',
    transition: { target: Resources.Missions, from: ['open'], to: 'claimed' },
    fields: [
      { fieldName: 'missionId', displayType: 'uuid' },
      { fieldName: 'squadronId', displayType: 'enumerated', enumeratedResource: Resources.Squadrons },
    ],
  },
  [Methods.CompileBriefing]: {
    route: 'compile-briefing',
    answers: true,
    fields: [
      { fieldName: 'includeHazards', displayType: 'boolean' },
    ],
  },
  [Methods.CompleteMission]: {
    route: 'complete-mission',
    transition: { target: Resources.Missions, from: ['underway'], to: 'completed' },
    answers: true,
    statuses: [200, 409],
    fields: [
      { fieldName: 'missionId', displayType: 'uuid' },
    ],
  },
  [Methods.FailFlightTest]: {
    route: 'fail-flight-test',
    transition: { target: Resources.Refits, from: ['flight_test'], to: 'in_refit' },
    fields: [
      { fieldName: 'refitId', displayType: 'uuid' },
    ],
  },
  [Methods.FailMission]: {
    route: 'fail-mission',
    transition: { target: Resources.Missions, from: ['underway'], to: 'failed' },
    fields: [
      { fieldName: 'missionId', displayType: 'uuid' },
      { fieldName: 'reasonId', displayType: 'string' },
    ],
  },
  [Methods.HailShip]: {
    route: 'hail-ship',
    statuses: [204],
    fields: [
      { fieldName: 'shipId', displayType: 'uuid' },
    ],
  },
  [Methods.HoldMission]: {
    route: 'hold-mission',
    transition: { target: Resources.Missions, from: ['underway'], to: 'on_hold' },
    fields: [
      { fieldName: 'missionId', displayType: 'uuid' },
      { fieldName: 'reason', displayType: 'string' },
    ],
  },
  [Methods.InspectShip]: {
    route: 'inspect-ship',
    transition: { target: Resources.Refits, from: ['docked'], to: 'inspected' },
    answers: true,
    fields: [
      { fieldName: 'refitId', displayType: 'uuid' },
    ],
  },
  [Methods.IssueBulletin]: {
    route: 'issue-bulletin',
    fields: [
      { fieldName: 'announcement', displayType: 'string' },
    ],
  },
  [Methods.LaunchMission]: {
    route: 'launch-mission',
    transition: { target: Resources.Missions, from: ['claimed'], to: 'underway' },
    fields: [
      { fieldName: 'missionId', displayType: 'uuid' },
      { fieldName: 'shipId', displayType: 'enumerated', enumeratedResource: Resources.Ships },
      { fieldName: 'pilotUserId', displayType: 'string' },
    ],
  },
  [Methods.PassFlightTest]: {
    route: 'pass-flight-test',
    transition: { target: Resources.Refits, from: ['flight_test'], to: 'cleared' },
    fields: [
      { fieldName: 'refitId', displayType: 'uuid' },
    ],
  },
  [Methods.ReleaseConsignment]: {
    route: 'release-consignment',
    answers: true,
    fields: [
      { fieldName: 'consignmentId', displayType: 'uuid' },
    ],
  },
  [Methods.ResumeMission]: {
    route: 'resume-mission',
    transition: { target: Resources.Missions, from: ['on_hold'], to: 'underway' },
    fields: [
      { fieldName: 'missionId', displayType: 'uuid' },
    ],
  },
  [Methods.ScrapShip]: {
    route: 'scrap-ship',
    transition: { target: Resources.Refits, from: ['inspected', 'in_refit', 'flight_test'], to: 'scrapped' },
    fields: [
      { fieldName: 'refitId', displayType: 'uuid' },
    ],
  },
  [Methods.StandDownMission]: {
    route: 'stand-down-mission',
    transition: { target: Resources.Missions, from: ['open', 'claimed', 'on_hold'], to: 'stood_down' },
    fields: [
      { fieldName: 'missionId', displayType: 'uuid' },
    ],
  },
  [Methods.StartFlightTest]: {
    route: 'start-flight-test',
    transition: { target: Resources.Refits, from: ['in_refit'], to: 'flight_test' },
    fields: [
      { fieldName: 'refitId', displayType: 'uuid' },
    ],
  },
};

export function methodMeta(method: Method): Meta {
  if (methodMap[method] !== undefined) {
    return methodMap[method];
  } else {
    console.error('Method not found in methodMap:', method);
    return {} as Meta;
  }
}
