// Code generated by resourcegeneration. DO NOT EDIT.
import { FieldName, Method, Permission, Resource } from '@cccteam/resource';

export const Permissions = {
  Create: 'Create' as Permission,
  Delete: 'Delete' as Permission,
  Execute: 'Execute' as Permission,
  List: 'List' as Permission,
  Read: 'Read' as Permission,
  Update: 'Update' as Permission,
};

export type PermissionScope = 'global' | 'domain';

export const PermissionScopes = {
  domain: 'domain' as PermissionScope,
  global: 'global' as PermissionScope,
};

export const Resources = {
  ClientContacts: 'ClientContacts' as Resource,
  Clients: 'Clients' as Resource,
  Consignments: 'Consignments' as Resource,
  DistressCalls: 'DistressCalls' as Resource,
  FeeByKinds: 'FeeByKinds' as Resource,
  Hangars: 'Hangars' as Resource,
  Missions: 'Missions' as Resource,
  OpenMissionsBySquadrons: 'OpenMissionsBySquadrons' as Resource,
  PilotCertifications: 'PilotCertifications' as Resource,
  Pilots: 'Pilots' as Resource,
  RefitTasks: 'RefitTasks' as Resource,
  Refits: 'Refits' as Resource,
  SectorHazardBoards: 'SectorHazardBoards' as Resource,
  Sectors: 'Sectors' as Resource,
  ServiceLedgers: 'ServiceLedgers' as Resource,
  ShipClasses: 'ShipClasses' as Resource,
  Ships: 'Ships' as Resource,
  ShipsLogEntries: 'ShipsLogEntries' as Resource,
  SortieExpenses: 'SortieExpenses' as Resource,
  Sorties: 'Sorties' as Resource,
  SquadronMemberships: 'SquadronMemberships' as Resource,
  Squadrons: 'Squadrons' as Resource,
  Wings: 'Wings' as Resource,
};

export const Methods = {
  BeginRefit: 'BeginRefit' as Method,
  ClaimMission: 'ClaimMission' as Method,
  CompleteMission: 'CompleteMission' as Method,
  FailFlightTest: 'FailFlightTest' as Method,
  FailMission: 'FailMission' as Method,
  HailShip: 'HailShip' as Method,
  HoldMission: 'HoldMission' as Method,
  InspectShip: 'InspectShip' as Method,
  IssueBulletin: 'IssueBulletin' as Method,
  LaunchMission: 'LaunchMission' as Method,
  PassFlightTest: 'PassFlightTest' as Method,
  ReleaseConsignment: 'ReleaseConsignment' as Method,
  ResumeMission: 'ResumeMission' as Method,
  ScrapShip: 'ScrapShip' as Method,
  StandDownMission: 'StandDownMission' as Method,
  StartFlightTest: 'StartFlightTest' as Method,
  AssumeRole: 'AssumeRole' as Method,
  ViewAsUser: 'ViewAsUser' as Method,
};

export namespace ClientContacts {
  export const fieldName = {
    clientId: 'clientId' as FieldName,
    displayName: 'displayName' as FieldName,
    id: 'id' as FieldName,
    userId: 'userId' as FieldName,
  };
  export const resourceName = {
    clientId: 'ClientContacts.clientId' as Resource,
    displayName: 'ClientContacts.displayName' as Resource,
    id: 'ClientContacts.id' as Resource,
    userId: 'ClientContacts.userId' as Resource,
  };
}

export namespace Clients {
  export const fieldName = {
    id: 'id' as FieldName,
    name: 'name' as FieldName,
    trusted: 'trusted' as FieldName,
  };
  export const piiFieldName = {
    contactEmail: 'contactEmail' as FieldName,
    contactName: 'contactName' as FieldName,
  };
  export const resourceName = {
    contactEmail: 'Clients.contactEmail' as Resource,
    contactName: 'Clients.contactName' as Resource,
    id: 'Clients.id' as Resource,
    name: 'Clients.name' as Resource,
    trusted: 'Clients.trusted' as Resource,
  };
}

export namespace Consignments {
  export const fieldName = {
    bondCode: 'bondCode' as FieldName,
    clientId: 'clientId' as FieldName,
    description: 'description' as FieldName,
    expiresOn: 'expiresOn' as FieldName,
    id: 'id' as FieldName,
    mass: 'mass' as FieldName,
    releasedAt: 'releasedAt' as FieldName,
    sectorId: 'sectorId' as FieldName,
  };
  export const resourceName = {
    bondCode: 'Consignments.bondCode' as Resource,
    clientId: 'Consignments.clientId' as Resource,
    description: 'Consignments.description' as Resource,
    expiresOn: 'Consignments.expiresOn' as Resource,
    id: 'Consignments.id' as Resource,
    mass: 'Consignments.mass' as Resource,
    releasedAt: 'Consignments.releasedAt' as Resource,
    sectorId: 'Consignments.sectorId' as Resource,
  };
}

export namespace DistressCalls {
  export const fieldName = {
    caseNumber: 'caseNumber' as FieldName,
    filedBy: 'filedBy' as FieldName,
    id: 'id' as FieldName,
    sectorId: 'sectorId' as FieldName,
    severity: 'severity' as FieldName,
    summary: 'summary' as FieldName,
    transcript: 'transcript' as FieldName,
  };
  export const piiFieldName = {
    callerContact: 'callerContact' as FieldName,
  };
  export const resourceName = {
    callerContact: 'DistressCalls.callerContact' as Resource,
    caseNumber: 'DistressCalls.caseNumber' as Resource,
    filedBy: 'DistressCalls.filedBy' as Resource,
    id: 'DistressCalls.id' as Resource,
    sectorId: 'DistressCalls.sectorId' as Resource,
    severity: 'DistressCalls.severity' as Resource,
    summary: 'DistressCalls.summary' as Resource,
    transcript: 'DistressCalls.transcript' as Resource,
  };
}

export namespace FeeByKinds {
  export const fieldName = {
    kindId: 'kindId' as FieldName,
    missionCount: 'missionCount' as FieldName,
    topFee: 'topFee' as FieldName,
    totalFee: 'totalFee' as FieldName,
  };
  export const resourceName = {
    kindId: 'FeeByKinds.kindId' as Resource,
    missionCount: 'FeeByKinds.missionCount' as Resource,
    topFee: 'FeeByKinds.topFee' as Resource,
    totalFee: 'FeeByKinds.totalFee' as Resource,
  };
}

export namespace Hangars {
  export const fieldName = {
    id: 'id' as FieldName,
    name: 'name' as FieldName,
    sectorId: 'sectorId' as FieldName,
    zone: 'zone' as FieldName,
  };
  export const resourceName = {
    id: 'Hangars.id' as Resource,
    name: 'Hangars.name' as Resource,
    sectorId: 'Hangars.sectorId' as Resource,
    zone: 'Hangars.zone' as Resource,
  };
}

export namespace Missions {
  export const fieldName = {
    assignedSquadronId: 'assignedSquadronId' as FieldName,
    bookedBy: 'bookedBy' as FieldName,
    brief: 'brief' as FieldName,
    clientId: 'clientId' as FieldName,
    deadline: 'deadline' as FieldName,
    fee: 'fee' as FieldName,
    hazard: 'hazard' as FieldName,
    id: 'id' as FieldName,
    kindId: 'kindId' as FieldName,
    notes: 'notes' as FieldName,
    requiredCertId: 'requiredCertId' as FieldName,
    sectorId: 'sectorId' as FieldName,
    settlement: 'settlement' as FieldName,
    statusId: 'statusId' as FieldName,
    title: 'title' as FieldName,
  };
  export const resourceName = {
    assignedSquadronId: 'Missions.assignedSquadronId' as Resource,
    bookedBy: 'Missions.bookedBy' as Resource,
    brief: 'Missions.brief' as Resource,
    clientId: 'Missions.clientId' as Resource,
    deadline: 'Missions.deadline' as Resource,
    fee: 'Missions.fee' as Resource,
    hazard: 'Missions.hazard' as Resource,
    id: 'Missions.id' as Resource,
    kindId: 'Missions.kindId' as Resource,
    notes: 'Missions.notes' as Resource,
    requiredCertId: 'Missions.requiredCertId' as Resource,
    sectorId: 'Missions.sectorId' as Resource,
    settlement: 'Missions.settlement' as Resource,
    statusId: 'Missions.statusId' as Resource,
    title: 'Missions.title' as Resource,
  };
}

export namespace OpenMissionsBySquadrons {
  export const fieldName = {
    nextDeadline: 'nextDeadline' as FieldName,
    openMissions: 'openMissions' as FieldName,
    sectorId: 'sectorId' as FieldName,
    squadronId: 'squadronId' as FieldName,
    squadronName: 'squadronName' as FieldName,
  };
  export const resourceName = {
    nextDeadline: 'OpenMissionsBySquadrons.nextDeadline' as Resource,
    openMissions: 'OpenMissionsBySquadrons.openMissions' as Resource,
    sectorId: 'OpenMissionsBySquadrons.sectorId' as Resource,
    squadronId: 'OpenMissionsBySquadrons.squadronId' as Resource,
    squadronName: 'OpenMissionsBySquadrons.squadronName' as Resource,
  };
}

export namespace PilotCertifications {
  export const fieldName = {
    certificationId: 'certificationId' as FieldName,
    userId: 'userId' as FieldName,
  };
  export const resourceName = {
    certificationId: 'PilotCertifications.certificationId' as Resource,
    userId: 'PilotCertifications.userId' as Resource,
  };
}

export namespace Pilots {
  export const fieldName = {
    clearance: 'clearance' as FieldName,
    displayName: 'displayName' as FieldName,
    feeLimit: 'feeLimit' as FieldName,
    id: 'id' as FieldName,
    userId: 'userId' as FieldName,
  };
  export const resourceName = {
    clearance: 'Pilots.clearance' as Resource,
    displayName: 'Pilots.displayName' as Resource,
    feeLimit: 'Pilots.feeLimit' as Resource,
    id: 'Pilots.id' as Resource,
    userId: 'Pilots.userId' as Resource,
  };
}

export namespace RefitTasks {
  export const fieldName = {
    done: 'done' as FieldName,
    instructions: 'instructions' as FieldName,
    notes: 'notes' as FieldName,
    refitId: 'refitId' as FieldName,
    taskNumber: 'taskNumber' as FieldName,
  };
  export const resourceName = {
    done: 'RefitTasks.done' as Resource,
    instructions: 'RefitTasks.instructions' as Resource,
    notes: 'RefitTasks.notes' as Resource,
    refitId: 'RefitTasks.refitId' as Resource,
    taskNumber: 'RefitTasks.taskNumber' as Resource,
  };
}

export namespace Refits {
  export const fieldName = {
    estimate: 'estimate' as FieldName,
    id: 'id' as FieldName,
    inspectedAt: 'inspectedAt' as FieldName,
    notes: 'notes' as FieldName,
    openedBy: 'openedBy' as FieldName,
    shipId: 'shipId' as FieldName,
    statusId: 'statusId' as FieldName,
  };
  export const resourceName = {
    estimate: 'Refits.estimate' as Resource,
    id: 'Refits.id' as Resource,
    inspectedAt: 'Refits.inspectedAt' as Resource,
    notes: 'Refits.notes' as Resource,
    openedBy: 'Refits.openedBy' as Resource,
    shipId: 'Refits.shipId' as Resource,
    statusId: 'Refits.statusId' as Resource,
  };
}

export namespace SectorHazardBoards {
  export const fieldName = {
    recordedAt: 'recordedAt' as FieldName,
    sectorId: 'sectorId' as FieldName,
    shipId: 'shipId' as FieldName,
    shipName: 'shipName' as FieldName,
    subsystem: 'subsystem' as FieldName,
    worstReading: 'worstReading' as FieldName,
  };
  export const resourceName = {
    recordedAt: 'SectorHazardBoards.recordedAt' as Resource,
    sectorId: 'SectorHazardBoards.sectorId' as Resource,
    shipId: 'SectorHazardBoards.shipId' as Resource,
    shipName: 'SectorHazardBoards.shipName' as Resource,
    subsystem: 'SectorHazardBoards.subsystem' as Resource,
    worstReading: 'SectorHazardBoards.worstReading' as Resource,
  };
}

export namespace Sectors {
  export const fieldName = {
    established: 'established' as FieldName,
    id: 'id' as FieldName,
    name: 'name' as FieldName,
    region: 'region' as FieldName,
  };
  export const resourceName = {
    established: 'Sectors.established' as Resource,
    id: 'Sectors.id' as Resource,
    name: 'Sectors.name' as Resource,
    region: 'Sectors.region' as Resource,
  };
}

export namespace ServiceLedgers {
  export const fieldName = {
    feesOutstanding: 'feesOutstanding' as FieldName,
    name: 'name' as FieldName,
    openMissions: 'openMissions' as FieldName,
    sectorId: 'sectorId' as FieldName,
    settlements: 'settlements' as FieldName,
  };
  export const resourceName = {
    feesOutstanding: 'ServiceLedgers.feesOutstanding' as Resource,
    name: 'ServiceLedgers.name' as Resource,
    openMissions: 'ServiceLedgers.openMissions' as Resource,
    sectorId: 'ServiceLedgers.sectorId' as Resource,
    settlements: 'ServiceLedgers.settlements' as Resource,
  };
}

export namespace ShipClasses {
  export const fieldName = {
    designation: 'designation' as FieldName,
    hardened: 'hardened' as FieldName,
    id: 'id' as FieldName,
    roleId: 'roleId' as FieldName,
    tonnage: 'tonnage' as FieldName,
  };
  export const resourceName = {
    designation: 'ShipClasses.designation' as Resource,
    hardened: 'ShipClasses.hardened' as Resource,
    id: 'ShipClasses.id' as Resource,
    roleId: 'ShipClasses.roleId' as Resource,
    tonnage: 'ShipClasses.tonnage' as Resource,
  };
}

export namespace Ships {
  export const fieldName = {
    classId: 'classId' as FieldName,
    hangarId: 'hangarId' as FieldName,
    id: 'id' as FieldName,
    lastRefitAt: 'lastRefitAt' as FieldName,
    name: 'name' as FieldName,
    registry: 'registry' as FieldName,
    updatedAt: 'updatedAt' as FieldName,
  };
  export const resourceName = {
    classId: 'Ships.classId' as Resource,
    hangarId: 'Ships.hangarId' as Resource,
    id: 'Ships.id' as Resource,
    lastRefitAt: 'Ships.lastRefitAt' as Resource,
    name: 'Ships.name' as Resource,
    registry: 'Ships.registry' as Resource,
    updatedAt: 'Ships.updatedAt' as Resource,
  };
}

export namespace SortieExpenses {
  export const fieldName = {
    amount: 'amount' as FieldName,
    category: 'category' as FieldName,
    id: 'id' as FieldName,
    note: 'note' as FieldName,
    sortieId: 'sortieId' as FieldName,
  };
  export const resourceName = {
    amount: 'SortieExpenses.amount' as Resource,
    category: 'SortieExpenses.category' as Resource,
    id: 'SortieExpenses.id' as Resource,
    note: 'SortieExpenses.note' as Resource,
    sortieId: 'SortieExpenses.sortieId' as Resource,
  };
}

export namespace Sorties {
  export const fieldName = {
    debrief: 'debrief' as FieldName,
    id: 'id' as FieldName,
    launchedAt: 'launchedAt' as FieldName,
    missionId: 'missionId' as FieldName,
    pilotUserId: 'pilotUserId' as FieldName,
    returnedAt: 'returnedAt' as FieldName,
    shipId: 'shipId' as FieldName,
  };
  export const resourceName = {
    debrief: 'Sorties.debrief' as Resource,
    id: 'Sorties.id' as Resource,
    launchedAt: 'Sorties.launchedAt' as Resource,
    missionId: 'Sorties.missionId' as Resource,
    pilotUserId: 'Sorties.pilotUserId' as Resource,
    returnedAt: 'Sorties.returnedAt' as Resource,
    shipId: 'Sorties.shipId' as Resource,
  };
}

export namespace SquadronMemberships {
  export const fieldName = {
    squadronId: 'squadronId' as FieldName,
    userId: 'userId' as FieldName,
  };
  export const resourceName = {
    squadronId: 'SquadronMemberships.squadronId' as Resource,
    userId: 'SquadronMemberships.userId' as Resource,
  };
}

export namespace Squadrons {
  export const fieldName = {
    id: 'id' as FieldName,
    name: 'name' as FieldName,
    wingId: 'wingId' as FieldName,
  };
  export const resourceName = {
    id: 'Squadrons.id' as Resource,
    name: 'Squadrons.name' as Resource,
    wingId: 'Squadrons.wingId' as Resource,
  };
}

export namespace Wings {
  export const fieldName = {
    id: 'id' as FieldName,
    name: 'name' as FieldName,
    sectorId: 'sectorId' as FieldName,
  };
  export const resourceName = {
    id: 'Wings.id' as Resource,
    name: 'Wings.name' as Resource,
    sectorId: 'Wings.sectorId' as Resource,
  };
}

export namespace BeginRefit {
  export const fieldName = {
    refitId: 'refitId' as FieldName,
  };
}

export namespace ClaimMission {
  export const fieldName = {
    missionId: 'missionId' as FieldName,
    squadronId: 'squadronId' as FieldName,
  };
}

export namespace CompleteMission {
  export const fieldName = {
    missionId: 'missionId' as FieldName,
  };
}

export namespace FailFlightTest {
  export const fieldName = {
    refitId: 'refitId' as FieldName,
  };
}

export namespace FailMission {
  export const fieldName = {
    missionId: 'missionId' as FieldName,
    reasonId: 'reasonId' as FieldName,
  };
}

export namespace HailShip {
  export const fieldName = {
    shipId: 'shipId' as FieldName,
  };
}

export namespace HoldMission {
  export const fieldName = {
    missionId: 'missionId' as FieldName,
    reason: 'reason' as FieldName,
  };
}

export namespace InspectShip {
  export const fieldName = {
    refitId: 'refitId' as FieldName,
  };
}

export namespace IssueBulletin {
  export const fieldName = {
    announcement: 'announcement' as FieldName,
  };
}

export namespace LaunchMission {
  export const fieldName = {
    missionId: 'missionId' as FieldName,
    shipId: 'shipId' as FieldName,
    pilotUserId: 'pilotUserId' as FieldName,
  };
}

export namespace PassFlightTest {
  export const fieldName = {
    refitId: 'refitId' as FieldName,
  };
}

export namespace ReleaseConsignment {
  export const fieldName = {
    consignmentId: 'consignmentId' as FieldName,
  };
}

export namespace ResumeMission {
  export const fieldName = {
    missionId: 'missionId' as FieldName,
  };
}

export namespace ScrapShip {
  export const fieldName = {
    refitId: 'refitId' as FieldName,
  };
}

export namespace StandDownMission {
  export const fieldName = {
    missionId: 'missionId' as FieldName,
  };
}

export namespace StartFlightTest {
  export const fieldName = {
    refitId: 'refitId' as FieldName,
  };
}

