package generation

import (
	"fmt"
	"iter"
	"net/http"
	"path/filepath"
	"slices"
	"strings"

	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/ccc/resource/generation/parser"
	"github.com/cccteam/ccc/resource/generation/parser/genlang"

	"github.com/ettle/strcase"
)

const (
	booleanStr = "boolean"
)

// Generator provides methods for generating Go or Typescript for a resource-driven web application.
type Generator interface {
	Generate() error
	Close() error
}

const (
	genPrefix = "zz_gen"

	// generationHeader marks a file as owned by this generator. Every file-level template
	// must start with it: removeGeneratedFileByHeaderComment only deletes files carrying
	// this exact header, so a template using a different header silently escapes cleanup.
	generationHeader = "// Code generated by resourcegeneration. DO NOT EDIT."
)

// HandlerType describes the possible handlers implemented in a resource-driven API.
type HandlerType string

const (
	// AllHandlers is create, update, read, delete, and list handlers.
	AllHandlers HandlerType = "allHandlers"
	// ListHandler is the list handler.
	ListHandler HandlerType = "listHandler"
	// ReadHandler is the read handler.
	ReadHandler HandlerType = "readHandler"
	// PatchHandler is the patch handler.
	PatchHandler HandlerType = "patchHandler"
)

// RouteType describes a route or set of routes for a resource-driven API.
type RouteType string

const (
	// AllRoutes encompasses every route for a resource.
	AllRoutes RouteType = "allRoutes"

	// Only supporting AllRoutes for now, but more granular route types could be added in the future as needed.
)

type packageDir string

func (p packageDir) Dir() string {
	if strings.HasSuffix(string(p), ".go") {
		s := strings.TrimSuffix(string(p), filepath.Base(string(p)))
		if s != "" {
			s = s[:len(s)-1]
		}

		return s
	}

	return string(p)
}

func (p packageDir) Package() string {
	if strings.HasSuffix(string(p), ".go") {
		return filepath.Base(filepath.Dir(string(p)))
	}

	return filepath.Base(string(p))
}

func handlerTypes() []HandlerType {
	return []HandlerType{
		AllHandlers,
		ListHandler,
		ReadHandler,
		PatchHandler,
	}
}

func routeTypes() []RouteType {
	return []RouteType{
		AllRoutes,
	}
}

// validSuppressArgs returns the set of valid arguments accepted by the @suppress() directive.
func validSuppressArgs() []string {
	args := make([]string, 0, len(handlerTypes())+len(routeTypes()))
	for _, ht := range handlerTypes() {
		args = append(args, string(ht))
	}
	for _, rt := range routeTypes() {
		args = append(args, string(rt))
	}

	return args
}

func validComputedSuppressArgs() []string {
	return []string{
		string(AllHandlers),
		string(ListHandler),
		string(ReadHandler),
		string(AllRoutes),
	}
}

func (h HandlerType) template() string {
	switch h {
	case ReadHandler:
		return readTemplate
	case ListHandler:
		return listTemplate
	case PatchHandler:
		return patchTemplate
	default:
		panic(fmt.Sprintf("template(): unknown handler type: %s", h))
	}
}

// method returns the proper http method type for a HandlerType
func (h HandlerType) method() string {
	switch h {
	case ReadHandler, ListHandler:
		return http.MethodGet
	case PatchHandler:
		return http.MethodPatch
	default:
		panic(fmt.Sprintf("Method(): unknown handler type: %s", h))
	}
}

// httpMethodConstant returns the net/http constant name for an http method
// (e.g. "GET" -> "http.MethodGet").
func httpMethodConstant(method string) string {
	return "http.Method" + strcase.ToPascal(method)
}

type patchType string

const (
	createPatch patchType = "Create"
	updatePatch patchType = "Update"
)

type consolidateConfig struct {
	// ConsolidatedResourceNames is an allowlist when ConsolidateAll is false
	// (only the named resources are consolidated) and a denylist when it is
	// true (every resource except the named ones is consolidated).
	ConsolidatedResourceNames []string
	ConsolidateAll            bool
	ConsolidatedRoute         string
}

func (c consolidateConfig) IsConsolidated(resourceName string) bool {
	return c.ConsolidateAll != slices.Contains(c.ConsolidatedResourceNames, resourceName)
}

type generatedFileDeleteMethod int

const (
	// Used to remove files with the genPrefix value instead of reading the contents of the file.
	prefix generatedFileDeleteMethod = iota
	// Used to remove files that contain the header comment "// Code generated by resourcegeneration. DO NOT EDIT."
	headerComment
)

const (
	resourceInterfaceOutputName   = "resources_iface"
	resourceEnumsFileName         = "enums"
	domainGuardOutputName         = "domain_guard"
	decodersOutputName            = "decoders"
	appContractOutputName         = "app_contract"
	routesOutputName              = "routes"
	routerTestOutputName          = "routes_test"
	consolidatedHandlerOutputName = "consolidated_handler"
	collectionOutputName          = "collection"
)

type informationSchemaResult struct {
	TableName            string  `spanner:"TABLE_NAME"`
	ColumnName           string  `spanner:"COLUMN_NAME"`
	ConstraintName       *string `spanner:"CONSTRAINT_NAME"`
	IsPrimaryKey         bool    `spanner:"IS_PRIMARY_KEY"`
	IsForeignKey         bool    `spanner:"IS_FOREIGN_KEY"`
	ReferencedTable      *string `spanner:"REFERENCED_TABLE"`
	ReferencedColumn     *string `spanner:"REFERENCED_COLUMN"`
	SpannerType          string  `spanner:"SPANNER_TYPE"`
	IsNullable           bool    `spanner:"IS_NULLABLE"`
	IsIndex              bool    `spanner:"IS_INDEX"`
	IsUniqueIndex        bool    `spanner:"IS_UNIQUE_INDEX"`
	GenerationExpression *string `spanner:"GENERATION_EXPRESSION"`
	OrdinalPosition      int64   `spanner:"ORDINAL_POSITION"`
	KeyOrdinalPosition   int64   `spanner:"KEY_ORDINAL_POSITION"`
	HasDefault           bool    `spanner:"HAS_DEFAULT"`
	IsInterleaved        bool    `spanner:"IS_INTERLEAVED"`
}

type enumData struct {
	ID          string `spanner:"id"`
	Description string `spanner:"description"`
}

type tableMetadata struct {
	Columns       map[string]columnMeta
	PkCount       int
	IsInterleaved bool
}

type columnMeta struct {
	IsPrimaryKey       bool
	IsForeignKey       bool
	IsNullable         bool
	IsIndex            bool
	IsUniqueIndex      bool
	OrdinalPosition    int64
	KeyOrdinalPosition int64
	ReferencedTable    string
	ReferencedColumn   string
	HasDefault         bool
}

type generatedRoute struct {
	Method      string
	Path        string
	HandlerFunc string
	HandlerType HandlerType
	// DomainScoped marks routes served under the domain segment pair; the generated
	// route registration wraps exactly these in the application's DomainGuard
	// middleware. It is per-route, never per-subtree: a tenant-record resource's
	// global read route shares the segment pair's position and must stay unguarded.
	DomainScoped bool
	// TestURL is Path with each {param} placeholder replaced by its routeTestParam value.
	TestURL    string
	TestParams []routeTestParam
}

// SharedHandler reports whether the route's handler is additionally registered
// for POST requests at the same path (read and list handlers accept POST bodies).
func (g *generatedRoute) SharedHandler() bool {
	return g.HandlerType == ReadHandler || g.HandlerType == ListHandler
}

// appendParamsToPaths appends each test parameter to the route's paths: the
// {param} placeholder onto Path and the test value onto TestURL.
func (g *generatedRoute) appendParamsToPaths() {
	for _, p := range g.TestParams {
		g.Path += fmt.Sprintf("/{%s}", p.Key)
		g.TestURL += "/" + p.Value
	}
}

// prependDomainTestParam registers the domain route parameter's test value for a
// domain-scoped route. The domain segment pair sits between the route prefix and the
// resource segment (already part of Path and TestURL), so it must never go through
// appendParamsToPaths; call this after appendParamsToPaths.
func (g *generatedRoute) prependDomainTestParam(paramKey string) {
	if !g.DomainScoped {
		return
	}

	g.TestParams = append([]routeTestParam{{Key: paramKey, Value: domainTestValue}}, g.TestParams...)
}

// TestMethods returns the net/http method constant names the generated router
// tests exercise for this route.
func (g *generatedRoute) TestMethods() []string {
	methods := []string{httpMethodConstant(g.Method)}
	if g.SharedHandler() {
		methods = append(methods, httpMethodConstant(http.MethodPost))
	}

	return methods
}

// routeTestParam is a single route parameter and the value the generated router
// tests pass for it. Key matches the {param} placeholder in the route path.
type routeTestParam struct {
	Key   string
	Value string
}

type rpcMethodInfo struct {
	*parser.Struct
	outletMembership
	Fields          []*rpcField
	SuppressHandler bool
	// PermissionScope is the scope the method's registration uses
	// (@permissionScope); empty means accesstypes.GlobalPermissionScope.
	PermissionScope accesstypes.PermissionScope
}

// IsDomainScoped reports whether the method's @permissionScope resolves to the
// domain scope (an absent annotation defaults to global).
func (r *rpcMethodInfo) IsDomainScoped() bool {
	return r.PermissionScope == accesstypes.DomainPermissionScope
}

func (r *rpcMethodInfo) IsTxnRunner() bool {
	return r.Implements("TxnRunner")
}

func (r *rpcMethodInfo) IsDBRunner() bool {
	return r.Implements("DBRunner")
}

func (r *rpcMethodInfo) hasEnumeratedResource() bool {
	for _, field := range r.Fields {
		if field.IsEnumerated() {
			return true
		}
	}

	return false
}

func (r *rpcMethodInfo) HasLocalType() bool {
	for _, field := range r.Fields {
		if field.IsLocalType() {
			return true
		}
	}

	return false
}

type rpcField struct {
	*parser.Field
	typescriptType     string
	enumeratedResource *string
}

func (r rpcField) JSONTag() string {
	caser := strcase.NewCaser(false, nil, nil)
	camelCaseName := caser.ToCamel(r.Name())

	return fmt.Sprintf("%s:%q", jsonTagKey, camelCaseName)
}

func (r *rpcField) TypescriptDataType() string {
	switch r.typescriptType {
	case uuidTSType:
		return stringGoType
	case uuidTSType + "[]":
		return stringGoType + "[]"
	case civilDateTSType:
		return dateTSType
	case civilDateTSType + "[]":
		return dateTSType + "[]"
	default:
		return r.typescriptType
	}
}

func (r *rpcField) IsEnumerated() bool {
	return r.enumeratedResource != nil
}

func (r *rpcField) EnumeratedResource() string {
	if r.enumeratedResource == nil {
		return ""
	}

	return *r.enumeratedResource
}

func (r *rpcField) TypescriptDisplayType() string {
	if r.IsEnumerated() {
		return "enumerated"
	}

	return r.typescriptType
}

type computedResource struct {
	*parser.Struct
	outletMembership
	Fields              []*computedField
	SuppressReadHandler bool
	SuppressListHandler bool
	SuppressedRoutes    []RouteType
	// PermissionScope is the scope all of this resource's registrations use
	// (@permissionScope); empty means accesstypes.GlobalPermissionScope.
	PermissionScope accesstypes.PermissionScope
}

// IsDomainScoped reports whether the resource's @permissionScope resolves to the
// domain scope (an absent annotation defaults to global).
func (c *computedResource) IsDomainScoped() bool {
	return c.PermissionScope == accesstypes.DomainPermissionScope
}

func (c *computedResource) HasCompoundPrimaryKey() bool {
	var count uint
	for _, field := range c.Fields {
		if field.IsPrimaryKey {
			count++
		}
	}

	return count > 0
}

func (c *computedResource) PrimaryKey() *computedField {
	for _, field := range c.Fields {
		if field.IsPrimaryKey {
			return field
		}
	}

	return nil
}

func (c *computedResource) PrimaryKeys() []*computedField {
	keys := make([]*computedField, 0)
	for _, field := range c.Fields {
		if field.IsPrimaryKey {
			keys = append(keys, field)
		}
	}

	return keys
}

func (c *computedResource) RoutingDisabled() bool {
	return slices.Contains(c.SuppressedRoutes, AllRoutes)
}

type computedField struct {
	*parser.Field
	typescriptType     string
	IsPrimaryKey       bool
	KeyOrdinalPosition int
}

func (c *computedField) JSONTag() string {
	camelCaseName := caser.ToCamel(c.Name())

	return fmt.Sprintf("%s:%q", jsonTagKey, camelCaseName)
}

func (c *computedField) IsPII() bool {
	tag, ok := c.LookupTag(conditionsTagKey)
	if !ok {
		return false
	}

	conditions := strings.Split(tag, ",")

	return slices.Contains(conditions, piiCondition)
}

func (c *computedField) PIITag() string {
	if c.IsPII() {
		return piiOutTagKey + `:"true"`
	}

	return ""
}

// PermTag renders the perm:"-" primary-key exemption marker on @primarykey fields; see
// resourceField.PermTag.
func (c *computedField) PermTag() string {
	if c.IsPrimaryKey {
		return permTagKey + `:"-"`
	}

	return ""
}

func (c *computedField) TypescriptDataType() string {
	if c.typescriptType == uuidTSType {
		return stringGoType
	}
	if c.typescriptType == civilDateTSType {
		return dateTSType
	}

	return c.typescriptType
}

type resourceInfo struct {
	*parser.TypeInfo
	outletMembership
	Fields             []*resourceField
	SuppressedHandlers []HandlerType
	SuppressedRoutes   []RouteType
	// ManualAddResourceSets lists the handler types whose permission Sets are
	// registered by hand-written handlers (@manualAddResourceSet), so the statically
	// computed collection includes them even though no handler is generated.
	ManualAddResourceSets []HandlerType
	// PermissionScope is the scope all of this resource's registrations use
	// (@permissionScope); empty means accesstypes.GlobalPermissionScope.
	PermissionScope    accesstypes.PermissionScope
	IsVirtual          bool // Determines how CreatePatch is rendered in resource generation.
	IsConsolidated     bool
	PkCount            int
	IsInterleaved      bool
	DefaultsCreateType string
	DefaultsUpdateType string
	ValidateCreateType string
	ValidateUpdateType string

	// The resource's compiled binding vocabulary (ABAC design plan §04):
	// Attributes are the row attributes conditions reference (@attribute),
	// DomainBinding resolves rows to their tenant (@domain), and SubjectSets /
	// SubjectValues are the subject-side vocabulary anchored at user-id
	// columns (@subjectSet / @subjectValue).
	Attributes    []*attributeBinding
	DomainBinding *domainBinding
	SubjectSets   []*subjectBinding
	SubjectValues []*subjectBinding
}

// IsDomainScoped reports whether the resource's @permissionScope resolves to the
// domain scope (an absent annotation defaults to global).
func (r *resourceInfo) IsDomainScoped() bool {
	return r.PermissionScope == accesstypes.DomainPermissionScope
}

func (r *resourceInfo) HasNullBool() bool {
	for _, field := range r.Fields {
		if field.IsNullable && field.typescriptType == booleanStr {
			return true
		}
	}

	return false
}

func (r *resourceInfo) RoutingDisabled() bool {
	return slices.Contains(r.SuppressedRoutes, AllRoutes)
}

func (r *resourceInfo) ListHandlerDisabled() bool {
	return slices.Contains(r.SuppressedHandlers, ListHandler)
}

func (r *resourceInfo) ReadHandlerDisabled() bool {
	return slices.Contains(r.SuppressedHandlers, ReadHandler)
}

func (r *resourceInfo) CreateHandlerDisabled() bool {
	return slices.Contains(r.SuppressedHandlers, PatchHandler)
}

func (r *resourceInfo) UpdateHandlerDisabled() bool {
	return slices.Contains(r.SuppressedHandlers, PatchHandler)
}

func (r *resourceInfo) DeleteHandlerDisabled() bool {
	return slices.Contains(r.SuppressedHandlers, PatchHandler)
}

// HasDefaultsCreateType indicates if a default create type has been registered
func (r *resourceInfo) HasDefaultsCreateType() bool {
	return r.DefaultsCreateType != ""
}

// HasDefaultsUpdateType indicates if a default update type has been registered
func (r *resourceInfo) HasDefaultsUpdateType() bool {
	return r.DefaultsUpdateType != ""
}

// HasValidateCreateType indicates if a validate create type has been registered
func (r *resourceInfo) HasValidateCreateType() bool {
	return r.ValidateCreateType != ""
}

// HasValidateUpdateType indicates if a validate update type has been registered
func (r *resourceInfo) HasValidateUpdateType() bool {
	return r.ValidateUpdateType != ""
}

func (r *resourceInfo) PrimaryKeys() iter.Seq2[int, *resourceField] {
	var i int

	return func(yield func(int, *resourceField) bool) {
		for _, f := range r.Fields {
			if !f.IsPrimaryKey {
				continue
			}

			if !yield(i, f) {
				return
			}

			i++
		}
	}
}

func (r *resourceInfo) HasCompoundPrimaryKey() bool {
	return r.PkCount > 1
}

func (r *resourceInfo) PrimaryKeyIsGeneratedUUID() bool {
	if r.IsInterleaved || r.PkCount > 1 {
		return false
	}

	for _, f := range r.Fields {
		if f.IsPrimaryKey {
			if f.IsForeignKey {
				return false
			}

			return f.Type() == "ccc.UUID"
		}
	}

	return false
}

func (r *resourceInfo) OperationPathPattern() string {
	if r.PkCount == 1 {
		return "/{id}"
	}

	var pattern strings.Builder
	for i := range r.PkCount {
		fmt.Fprintf(&pattern, "/{id%d}", i+1)
	}

	return pattern.String()
}

func (r *resourceInfo) PrimaryKeyType() string {
	for _, f := range r.Fields {
		if f.IsPrimaryKey {
			return f.Type()
		}
	}

	return ""
}

func (r *resourceInfo) PrimaryKey() *resourceField {
	for _, f := range r.Fields {
		if f.IsPrimaryKey {
			return f
		}
	}

	return nil
}

func (r *resourceInfo) IsQueryClauseEligible() bool {
	for _, field := range r.Fields {
		if field.IsQueryClauseEligible() {
			return true
		}
	}

	return false
}

type resourceField struct {
	*parser.Field
	Parent         *resourceInfo
	typescriptType string
	// Spanner stuff
	IsPrimaryKey       bool
	IsForeignKey       bool
	IsIndex            bool
	IsUniqueIndex      bool
	IsNullable         bool
	OrdinalPosition    int64 // Position of column in the table definition
	KeyOrdinalPosition int64 // Position of primary or foreign key in a compound key definition
	IsEnumerated       bool
	ReferencedResource string
	ReferencedField    string
	HasDefault         bool

	// The @state marker (design plan §09): IsState derives output-only decode
	// and the ungrantable Create/Update; StateDefault is the declared initial
	// state, applied on the insert path.
	IsState      bool
	StateDefault string
}

// When generating QueryClauses for Null-style wrapper types we want to use the underlying type
// i.e. ccc.NullUUID -> ccc.UUID, spanner.NullString -> string
func (f *resourceField) UnwrappedNullType() *string {
	if !strings.HasPrefix(f.DerefUnqualifiedType(), "Null") {
		return nil
	}

	pStruct := f.AsStruct()
	if pStruct == nil {
		return nil
	}

	fields := pStruct.Fields()
	if len(fields) != 2 {
		return nil
	}

	var hasValidColumn bool
	for i := range fields {
		if fields[i].Name() == "Valid" && fields[i].DerefUnqualifiedType() == "bool" {
			hasValidColumn = true
		}
	}

	if !hasValidColumn {
		return nil
	}

	for i := range fields {
		if fields[i].Name() != "Valid" {
			return new(fields[i].DerefResolvedType())
		}
	}

	return nil
}

func (f *resourceField) TypescriptDataType() string {
	if f.typescriptType == uuidTSType {
		return stringGoType
	}
	if f.typescriptType == civilDateTSType {
		return dateTSType
	}
	if f.IsNullable && f.typescriptType == booleanStr {
		return "NullBoolean"
	}

	return f.typescriptType
}

func (f *resourceField) TypescriptDisplayType() string {
	if f.IsEnumerated {
		return "enumerated"
	}

	if f.IsNullable && f.typescriptType == booleanStr {
		return "nullboolean"
	}

	return f.typescriptType
}

func (f *resourceField) JSONTag() string {
	if f.IsInputOnly() {
		return fmt.Sprintf("%s:%q", jsonTagKey, "-")
	}

	caser := strcase.NewCaser(false, nil, nil)
	camelCaseName := caser.ToCamel(f.Name())

	return fmt.Sprintf("%s:%q", jsonTagKey, camelCaseName)
}

func (f *resourceField) JSONTagForPatch() string {
	if f.IsPrimaryKey || f.IsOutputOnly() {
		return fmt.Sprintf("%s:%q", jsonTagKey, "-")
	}

	caser := strcase.NewCaser(false, nil, nil)
	camelCaseName := caser.ToCamel(f.Name())

	return fmt.Sprintf("%s:%q", jsonTagKey, camelCaseName)
}

const indexTrue string = indexTagKey + `:"true"`

func (f *resourceField) IndexTag() string {
	if f.IsIndex {
		return indexTrue
	}

	if f.Parent.IsVirtual {
		t, ok := f.LookupTag(indexTagKey)
		if ok && t == "true" {
			return indexTrue
		}
	}

	return ""
}

func (f *resourceField) PIITag() string {
	if f.IsPII() {
		return piiOutTagKey + `:"true"`
	}

	return ""
}

func (f *resourceField) UniqueIndexTag() string {
	if f.IsUniqueIndex {
		return indexTrue
	}

	return ""
}

func (f *resourceField) AllowFilterTag() string {
	if f.HasTag(allowFilterTagKey) {
		return allowFilterTagKey + `:"true"`
	}

	return ""
}

func (f *resourceField) IsPII() bool {
	tag, ok := f.LookupTag(conditionsTagKey)
	if !ok {
		return false
	}

	conditions := strings.Split(tag, ",")

	return slices.Contains(conditions, piiCondition)
}

func (f *resourceField) IsImmutable() bool {
	tag, ok := f.LookupTag(conditionsTagKey)
	if !ok {
		return false
	}

	conditions := strings.Split(tag, ",")

	return slices.Contains(conditions, immutableCondition)
}

func (f *resourceField) IsOutputOnly() bool {
	// A state field decodes output-only by derivation: the wire must not be
	// able to express a state write (transitions live in RPC bodies).
	if f.IsState {
		return true
	}

	tag, ok := f.LookupTag(conditionsTagKey)
	if !ok {
		return f.HasOutputOnlyUpdateFunc()
	}

	conditions := strings.Split(tag, ",")

	return slices.Contains(conditions, outputOnlyCondition) || f.HasOutputOnlyUpdateFunc()
}

func (f *resourceField) IsInputOnly() bool {
	tag, ok := f.LookupTag(conditionsTagKey)
	if !ok {
		return false
	}

	conditions := strings.Split(tag, ",")

	return slices.Contains(conditions, inputOnlyCondition)
}

func (f *resourceField) DefaultCreateFuncName() string {
	tag, ok := f.LookupTag(defaultCreateFnTagKey)
	if !ok {
		return ""
	}

	return tag
}

func (f *resourceField) HasDefaultCreateFunc() bool {
	return f.DefaultCreateFuncName() != ""
}

func (f *resourceField) OutputOnlyUpdateFuncName() string {
	tag, ok := f.LookupTag(outputOnlyUpdateFnTagKey)
	if !ok {
		return ""
	}

	return tag
}

func (f *resourceField) HasOutputOnlyUpdateFunc() bool {
	return f.OutputOnlyUpdateFuncName() != ""
}

// PermTag renders the perm:"-" primary-key exemption marker: an exempt field's
// readability follows the resource-level grant. Every other field carries no perm tag
// and is enforced structurally with the handler's permissions.
func (f *resourceField) PermTag() string {
	if f.IsPrimaryKey {
		return permTagKey + `:"-"`
	}

	return ""
}

func (f *resourceField) ImmutableTag() string {
	if f.IsImmutable() {
		return immutableOutTagKey + `:"true"`
	}

	return ""
}

func (f *resourceField) IsView() bool {
	return f.Parent.IsVirtual
}

func (f *resourceField) IsRequired() bool {
	if f.IsPrimaryKey && f.Parent.PkCount > 1 {
		return true
	}

	if f.IsPrimaryKey && f.Type() != "ccc.UUID" {
		return true
	}

	if !f.IsPrimaryKey && !f.IsNullable && !f.HasDefault && !f.HasDefaultCreateFunc() {
		return true
	}

	return false
}

func (f *resourceField) IsQueryClauseEligible() bool {
	if f.IsIndex || f.IsUniqueIndex {
		return true
	}

	return f.HasTag(allowFilterTagKey)
}

func generatedGoFileName(name string) string {
	return generatedFileName(name, "go")
}

func generatedTypescriptFileName(name string) string {
	return generatedFileName(name, "ts")
}

func generatedFileName(name, suffix string) string {
	return fmt.Sprintf("%s_%s.%s", genPrefix, name, suffix)
}

const (
	resourceKeyword             string = "resource"             // Designates a struct as a resource
	virtualKeyword              string = "virtual"              // Designates a struct as a virtual resource
	computedKeyword             string = "computed"             // Designates a struct as a computed resource
	rpcKeyword                  string = "rpc"                  // Designates a struct as an RPC method
	enumerateKeyword            string = "enumerate"            // Generate constants based on existing values in Spanner DB (from inserts in migrations directory)
	suppressKeyword             string = "suppress"             // Suppresses generation of specified handler types or routes for a resource
	defaultsCreateTypeKeyword   string = "defaultsCreateType"   // Specifies a type to call "Defaults()" on for setting defaults on resource creation
	defaultsUpdateTypeKeyword   string = "defaultsUpdateType"   // Specifies a type to call "Defaults()" on for setting defaults on resource update
	validateCreateTypeKeyword   string = "validateCreateType"   // Specifies a type to call "Validate()" on for validating a resource on creation
	validateUpdateTypeKeyword   string = "validateUpdateType"   // Specifies a type to call "Validate()" on for validating a resource on update
	primarykeyKeyword           string = "primarykey"           // Designates a field as (part of) the primary key in a Computed or Virtual Resource
	manualAddResourceKeyword    string = "manualAddResource"    // Declares a manual permission registration on an accesstypes.Resource constant
	manualAddResourceSetKeyword string = "manualAddResourceSet" // Declares that hand-written handlers register this resource's permission Sets for the given handler types
	permissionScopeKeyword      string = "permissionScope"      // Declares the permission scope (global or domain) all of a resource's registrations use
	outletKeyword               string = "outlet"               // Declares the router outlets a resource's routes are registered under
	attributeKeyword            string = "attribute"            // Declares an attribute binding on its anchor field: a column binding, or a join-path binding via a FK
	domainKeyword               string = "domain"               // Declares the structural tenancy binding on its anchor field (bare, or via: a FK path to the tenant key)
	subjectSetKeyword           string = "subjectSet"           // Declares subject-side set vocabulary (subject.<name>, used with IN) anchored on a user-id column
	subjectValueKeyword         string = "subjectValue"         // Declares subject-side scalar vocabulary (threshold comparisons) anchored on a unique user-id column
	stateKeyword                string = "state"                // Marks a resource's state column (FK to its state enum table) and declares the initial state
)

func resourceKeywords() map[string]genlang.KeywordOpts {
	return map[string]genlang.KeywordOpts{
		resourceKeyword:             {genlang.ScanStruct: genlang.NoArgs | genlang.Exclusive},
		virtualKeyword:              {genlang.ScanStruct: genlang.NoArgs | genlang.Exclusive},
		computedKeyword:             {genlang.ScanStruct: genlang.NoArgs | genlang.Exclusive},
		rpcKeyword:                  {genlang.ScanStruct: genlang.NoArgs | genlang.Exclusive},
		enumerateKeyword:            {genlang.ScanNamedType: genlang.ArgsRequired | genlang.Exclusive},
		suppressKeyword:             {genlang.ScanStruct: genlang.ArgsRequired},
		defaultsCreateTypeKeyword:   {genlang.ScanStruct: genlang.ArgsRequired | genlang.Exclusive},
		defaultsUpdateTypeKeyword:   {genlang.ScanStruct: genlang.ArgsRequired | genlang.Exclusive},
		validateCreateTypeKeyword:   {genlang.ScanStruct: genlang.ArgsRequired | genlang.Exclusive},
		validateUpdateTypeKeyword:   {genlang.ScanStruct: genlang.ArgsRequired | genlang.Exclusive},
		primarykeyKeyword:           {genlang.ScanField: genlang.NoArgs},
		manualAddResourceKeyword:    {genlang.ScanConstant: genlang.ArgsRequired},
		manualAddResourceSetKeyword: {genlang.ScanStruct: genlang.ArgsRequired},
		permissionScopeKeyword:      {genlang.ScanStruct: genlang.ArgsRequired | genlang.Exclusive},
		outletKeyword:               {genlang.ScanStruct: genlang.ArgsRequired},
		attributeKeyword:            {genlang.ScanField: genlang.ArgsRequired | genlang.Exclusive},
		domainKeyword:               {genlang.ScanField: genlang.Exclusive},
		subjectSetKeyword:           {genlang.ScanField: genlang.ArgsRequired},
		subjectValueKeyword:         {genlang.ScanField: genlang.ArgsRequired},
		stateKeyword:                {genlang.ScanField: genlang.ArgsRequired | genlang.Exclusive},
	}
}

// outletMembership records the router outlets a struct's @outlet annotation names.
// An empty list means the default outlet only; naming any outlet replaces that
// default entirely, so a resource on the default outlet and another lists both.
type outletMembership struct {
	OutletNames []string
}

// OnOutlet reports whether the struct's routes are registered under the named outlet.
func (o *outletMembership) OnOutlet(name string) bool {
	if len(o.OutletNames) == 0 {
		return name == defaultOutletName
	}

	return slices.Contains(o.OutletNames, name)
}
