// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/rpc

package rpc

import "github.com/cccteam/ccc/accesstypes"

func (FailMission) Method() accesstypes.Resource {
	return "FailMission"
}
