// Code generated by resourcegeneration. DO NOT EDIT.
// Source: pkg/rpc

package rpc

import "github.com/cccteam/ccc/accesstypes"

func (StartFlightTest) Method() accesstypes.Resource {
	return "StartFlightTest"
}
